 :========================================:
 :**   BEGIN FSTR Structural Analysis   **:
 :========================================:
         Total no. of processors:            1



  *    STAGE Initialization and input   **



  ***   STAGE Heat analysis    **
 =============================
   H E A T   T R A N S F E R  
 =============================
* Current step / Total step:        1/       1
* max iteration at each step:      100
* Transient anslysis
 ** Increment No. :       1, total time:  1.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  3.50310E-02, solve time:  2.63850E-03, relative residual:  4.65375E-18
### solver log, setup time:  2.06976E-02, solve time:  3.12920E-03, relative residual:  4.75888E-18
### solver log, setup time:  2.00964E-02, solve time:  3.22970E-03, relative residual:  4.93277E-18
### solver log, setup time:  2.06424E-02, solve time:  2.70990E-03, relative residual:  4.85631E-18
### solver log, setup time:  2.00373E-02, solve time:  2.54010E-03, relative residual:  4.84006E-18
### solver log, setup time:  2.13902E-02, solve time:  2.48890E-03, relative residual:  4.85274E-18
### solver log, setup time:  1.87081E-02, solve time:  2.57470E-03, relative residual:  4.65300E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       2, total time:  2.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.96818E-02, solve time:  2.48240E-03, relative residual:  4.82073E-18
### solver log, setup time:  2.08007E-02, solve time:  2.74480E-03, relative residual:  4.74941E-18
### solver log, setup time:  2.41331E-02, solve time:  2.82310E-03, relative residual:  4.69964E-18
### solver log, setup time:  2.16429E-02, solve time:  2.66810E-03, relative residual:  4.86884E-18
### solver log, setup time:  1.98360E-02, solve time:  2.73180E-03, relative residual:  5.08373E-18
### solver log, setup time:  1.94549E-02, solve time:  3.07080E-03, relative residual:  4.91386E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       3, total time:  3.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.84766E-02, solve time:  2.52500E-03, relative residual:  4.69302E-18
### solver log, setup time:  1.92621E-02, solve time:  2.62240E-03, relative residual:  4.72434E-18
### solver log, setup time:  1.84285E-02, solve time:  2.49870E-03, relative residual:  4.56801E-18
### solver log, setup time:  1.80189E-02, solve time:  2.41070E-03, relative residual:  4.62826E-18
### solver log, setup time:  1.93398E-02, solve time:  2.60030E-03, relative residual:  4.55498E-18
### solver log, setup time:  2.06431E-02, solve time:  2.34070E-03, relative residual:  4.53433E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       4, total time:  4.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.87364E-02, solve time:  2.04270E-03, relative residual:  4.50235E-18
### solver log, setup time:  2.23754E-02, solve time:  3.38190E-03, relative residual:  4.51311E-18
### solver log, setup time:  1.94153E-02, solve time:  2.67370E-03, relative residual:  4.47084E-18
### solver log, setup time:  2.52284E-02, solve time:  3.03600E-03, relative residual:  4.46220E-18
### solver log, setup time:  2.05132E-02, solve time:  2.56620E-03, relative residual:  4.41551E-18
### solver log, setup time:  2.15695E-02, solve time:  3.15960E-03, relative residual:  4.55737E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       5, total time:  5.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.91322E-02, solve time:  2.41330E-03, relative residual:  4.65335E-18
### solver log, setup time:  2.28049E-02, solve time:  3.04260E-03, relative residual:  4.34995E-18
### solver log, setup time:  2.24786E-02, solve time:  2.37270E-03, relative residual:  4.42613E-18
### solver log, setup time:  2.62068E-02, solve time:  2.55540E-03, relative residual:  4.59071E-18
### solver log, setup time:  1.80751E-02, solve time:  2.35360E-03, relative residual:  4.51230E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       6, total time:  6.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.88957E-02, solve time:  2.10680E-03, relative residual:  4.45918E-18
### solver log, setup time:  1.84325E-02, solve time:  3.23850E-03, relative residual:  4.35549E-18
### solver log, setup time:  1.84408E-02, solve time:  2.35780E-03, relative residual:  4.32777E-18
### solver log, setup time:  1.86881E-02, solve time:  2.40830E-03, relative residual:  4.20178E-18
### solver log, setup time:  1.80047E-02, solve time:  2.53990E-03, relative residual:  4.25556E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       7, total time:  7.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.83712E-02, solve time:  2.79110E-03, relative residual:  4.07491E-18
### solver log, setup time:  1.94132E-02, solve time:  2.77810E-03, relative residual:  4.06259E-18
### solver log, setup time:  1.79322E-02, solve time:  2.62520E-03, relative residual:  4.20855E-18
### solver log, setup time:  1.83941E-02, solve time:  2.77820E-03, relative residual:  3.98107E-18
### solver log, setup time:  1.97412E-02, solve time:  2.53280E-03, relative residual:  4.07444E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       8, total time:  8.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.50453E-02, solve time:  4.27000E-03, relative residual:  4.27812E-18
### solver log, setup time:  1.78813E-02, solve time:  2.13980E-03, relative residual:  4.15834E-18
### solver log, setup time:  1.98015E-02, solve time:  2.66120E-03, relative residual:  4.01437E-18
### solver log, setup time:  2.00596E-02, solve time:  2.41700E-03, relative residual:  4.07994E-18
### solver log, setup time:  1.95636E-02, solve time:  2.65280E-03, relative residual:  3.89139E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       9, total time:  9.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.02290E-02, solve time:  2.40150E-03, relative residual:  4.19094E-18
### solver log, setup time:  2.17605E-02, solve time:  3.28380E-03, relative residual:  4.08449E-18
### solver log, setup time:  2.26053E-02, solve time:  2.39510E-03, relative residual:  3.93689E-18
### solver log, setup time:  2.10165E-02, solve time:  2.63170E-03, relative residual:  4.01253E-18
### solver log, setup time:  1.87492E-02, solve time:  2.40830E-03, relative residual:  4.20959E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      10, total time:  1.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.07302E-02, solve time:  2.65260E-03, relative residual:  4.14671E-18
### solver log, setup time:  3.11752E-02, solve time:  3.80650E-03, relative residual:  3.98839E-18
### solver log, setup time:  2.34250E-02, solve time:  2.44550E-03, relative residual:  4.11667E-18
### solver log, setup time:  1.94343E-02, solve time:  2.30620E-03, relative residual:  3.95810E-18
### solver log, setup time:  2.09480E-02, solve time:  2.48790E-03, relative residual:  3.87271E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      11, total time:  1.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79057E-02, solve time:  2.20680E-03, relative residual:  4.12824E-18
### solver log, setup time:  1.83750E-02, solve time:  2.87560E-03, relative residual:  3.83440E-18
### solver log, setup time:  2.00257E-02, solve time:  2.33880E-03, relative residual:  4.09735E-18
### solver log, setup time:  1.98871E-02, solve time:  2.32190E-03, relative residual:  4.03324E-18
### solver log, setup time:  2.42065E-02, solve time:  4.94940E-03, relative residual:  3.95407E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      12, total time:  1.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.56036E-02, solve time:  2.24750E-03, relative residual:  3.95671E-18
### solver log, setup time:  2.81519E-02, solve time:  2.68680E-03, relative residual:  3.79810E-18
### solver log, setup time:  1.82272E-02, solve time:  2.68520E-03, relative residual:  3.90470E-18
### solver log, setup time:  2.40116E-02, solve time:  2.87480E-03, relative residual:  3.85527E-18
### solver log, setup time:  1.92726E-02, solve time:  2.81610E-03, relative residual:  3.99098E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      13, total time:  1.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.20626E-02, solve time:  2.79300E-03, relative residual:  3.89681E-18
### solver log, setup time:  1.84922E-02, solve time:  2.55990E-03, relative residual:  3.82089E-18
### solver log, setup time:  1.77856E-02, solve time:  2.97450E-03, relative residual:  3.82522E-18
### solver log, setup time:  2.98020E-02, solve time:  3.47070E-03, relative residual:  3.86808E-18
### solver log, setup time:  2.28063E-02, solve time:  2.17140E-03, relative residual:  4.03483E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      14, total time:  1.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.20892E-02, solve time:  2.51840E-03, relative residual:  3.74929E-18
### solver log, setup time:  2.05149E-02, solve time:  2.37340E-03, relative residual:  3.69242E-18
### solver log, setup time:  2.10081E-02, solve time:  2.29630E-03, relative residual:  3.82306E-18
### solver log, setup time:  2.24307E-02, solve time:  2.32770E-03, relative residual:  3.91337E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      15, total time:  1.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.45118E-02, solve time:  3.39740E-03, relative residual:  3.80717E-18
### solver log, setup time:  2.27620E-02, solve time:  3.46520E-03, relative residual:  3.75411E-18
### solver log, setup time:  2.05470E-02, solve time:  2.47640E-03, relative residual:  3.76567E-18
### solver log, setup time:  2.10109E-02, solve time:  3.03720E-03, relative residual:  3.71731E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      16, total time:  1.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.42393E-02, solve time:  2.20930E-03, relative residual:  3.83803E-18
### solver log, setup time:  2.10713E-02, solve time:  1.98870E-03, relative residual:  3.86781E-18
### solver log, setup time:  2.15371E-02, solve time:  1.97630E-03, relative residual:  3.61424E-18
### solver log, setup time:  2.69561E-02, solve time:  3.18920E-03, relative residual:  3.59991E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      17, total time:  1.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.19424E-02, solve time:  3.38900E-03, relative residual:  3.77124E-18
### solver log, setup time:  1.87160E-02, solve time:  2.13730E-03, relative residual:  3.67896E-18
### solver log, setup time:  2.00523E-02, solve time:  2.41020E-03, relative residual:  3.42206E-18
### solver log, setup time:  2.11497E-02, solve time:  3.02630E-03, relative residual:  3.69956E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      18, total time:  1.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.97802E-02, solve time:  2.32570E-03, relative residual:  3.82981E-18
### solver log, setup time:  1.90958E-02, solve time:  2.54330E-03, relative residual:  3.62374E-18
### solver log, setup time:  2.08513E-02, solve time:  2.63270E-03, relative residual:  3.59730E-18
### solver log, setup time:  1.98932E-02, solve time:  2.35320E-03, relative residual:  3.46006E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      19, total time:  1.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.18727E-02, solve time:  2.45510E-03, relative residual:  3.66590E-18
### solver log, setup time:  1.89109E-02, solve time:  2.34080E-03, relative residual:  3.66641E-18
### solver log, setup time:  2.05694E-02, solve time:  2.16040E-03, relative residual:  3.55970E-18
### solver log, setup time:  2.04438E-02, solve time:  2.22930E-03, relative residual:  3.68094E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      20, total time:  2.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.21085E-02, solve time:  2.28360E-03, relative residual:  3.57350E-18
### solver log, setup time:  2.14335E-02, solve time:  2.83250E-03, relative residual:  3.75289E-18
### solver log, setup time:  2.15660E-02, solve time:  2.10840E-03, relative residual:  3.52534E-18
### solver log, setup time:  2.14663E-02, solve time:  4.03240E-03, relative residual:  3.36089E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      21, total time:  2.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.13746E-02, solve time:  2.44400E-03, relative residual:  3.62407E-18
### solver log, setup time:  2.38812E-02, solve time:  3.06320E-03, relative residual:  3.51076E-18
### solver log, setup time:  2.18411E-02, solve time:  2.42280E-03, relative residual:  3.73105E-18
### solver log, setup time:  2.38701E-02, solve time:  2.46320E-03, relative residual:  3.67909E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      22, total time:  2.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.93500E-02, solve time:  2.44980E-03, relative residual:  3.45463E-18
### solver log, setup time:  1.97371E-02, solve time:  2.26140E-03, relative residual:  3.61119E-18
### solver log, setup time:  1.83661E-02, solve time:  2.64330E-03, relative residual:  3.51725E-18
### solver log, setup time:  2.14077E-02, solve time:  2.25790E-03, relative residual:  3.56310E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      23, total time:  2.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.85079E-02, solve time:  2.53060E-03, relative residual:  3.40611E-18
### solver log, setup time:  1.94616E-02, solve time:  2.70070E-03, relative residual:  3.27721E-18
### solver log, setup time:  1.90352E-02, solve time:  2.23600E-03, relative residual:  3.59769E-18
### solver log, setup time:  2.01083E-02, solve time:  2.14870E-03, relative residual:  3.46299E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      24, total time:  2.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.23064E-02, solve time:  2.17270E-03, relative residual:  3.48160E-18
### solver log, setup time:  2.75226E-02, solve time:  2.60050E-03, relative residual:  3.33214E-18
### solver log, setup time:  1.99222E-02, solve time:  2.37400E-03, relative residual:  3.50675E-18
### solver log, setup time:  1.91743E-02, solve time:  2.84830E-03, relative residual:  3.55675E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      25, total time:  2.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.39704E-02, solve time:  3.12760E-03, relative residual:  3.50937E-18
### solver log, setup time:  2.21747E-02, solve time:  2.34360E-03, relative residual:  3.40959E-18
### solver log, setup time:  1.90769E-02, solve time:  2.18790E-03, relative residual:  3.45681E-18
### solver log, setup time:  2.08666E-02, solve time:  2.02170E-03, relative residual:  3.35806E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      26, total time:  2.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.32009E-02, solve time:  2.02170E-03, relative residual:  3.32743E-18
### solver log, setup time:  2.35271E-02, solve time:  2.39680E-03, relative residual:  3.48532E-18
### solver log, setup time:  1.85814E-02, solve time:  2.20910E-03, relative residual:  3.64817E-18
### solver log, setup time:  2.45949E-02, solve time:  2.23280E-03, relative residual:  3.42960E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      27, total time:  2.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.04806E-02, solve time:  2.16780E-03, relative residual:  3.28837E-18
### solver log, setup time:  1.95925E-02, solve time:  2.63500E-03, relative residual:  3.46780E-18
### solver log, setup time:  2.42896E-02, solve time:  2.37380E-03, relative residual:  3.41875E-18
### solver log, setup time:  1.99132E-02, solve time:  3.56540E-03, relative residual:  3.32864E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      28, total time:  2.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.27914E-02, solve time:  2.31330E-03, relative residual:  3.42171E-18
### solver log, setup time:  1.80475E-02, solve time:  2.32850E-03, relative residual:  3.52525E-18
### solver log, setup time:  2.25385E-02, solve time:  2.45880E-03, relative residual:  3.47805E-18
### solver log, setup time:  2.41188E-02, solve time:  2.40810E-03, relative residual:  3.34882E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      29, total time:  2.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.02543E-02, solve time:  2.29310E-03, relative residual:  3.63677E-18
### solver log, setup time:  1.97871E-02, solve time:  2.53220E-03, relative residual:  3.41094E-18
### solver log, setup time:  1.83682E-02, solve time:  2.78700E-03, relative residual:  3.45894E-18
### solver log, setup time:  1.97684E-02, solve time:  2.37020E-03, relative residual:  3.65313E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      30, total time:  3.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.99164E-02, solve time:  2.54030E-03, relative residual:  3.31642E-18
### solver log, setup time:  2.43906E-02, solve time:  4.48260E-03, relative residual:  3.66031E-18
### solver log, setup time:  1.78636E-02, solve time:  2.10190E-03, relative residual:  3.35550E-18
### solver log, setup time:  1.80488E-02, solve time:  2.56750E-03, relative residual:  3.33454E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      31, total time:  3.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.88521E-02, solve time:  2.27420E-03, relative residual:  3.51216E-18
### solver log, setup time:  1.85326E-02, solve time:  4.79650E-03, relative residual:  3.29434E-18
### solver log, setup time:  1.95876E-02, solve time:  2.28350E-03, relative residual:  3.29269E-18
### solver log, setup time:  1.98961E-02, solve time:  2.15280E-03, relative residual:  3.43359E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      32, total time:  3.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79895E-02, solve time:  2.20910E-03, relative residual:  3.48807E-18
### solver log, setup time:  2.59498E-02, solve time:  2.89610E-03, relative residual:  3.61820E-18
### solver log, setup time:  1.98290E-02, solve time:  2.28500E-03, relative residual:  3.64174E-18
### solver log, setup time:  2.14607E-02, solve time:  2.74520E-03, relative residual:  3.34001E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      33, total time:  3.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78146E-02, solve time:  2.33530E-03, relative residual:  3.67764E-18
### solver log, setup time:  1.97677E-02, solve time:  2.38990E-03, relative residual:  3.41171E-18
### solver log, setup time:  1.90939E-02, solve time:  2.21410E-03, relative residual:  3.35743E-18
### solver log, setup time:  1.86916E-02, solve time:  2.28230E-03, relative residual:  3.44819E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      34, total time:  3.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80698E-02, solve time:  2.24870E-03, relative residual:  3.30925E-18
### solver log, setup time:  1.90708E-02, solve time:  2.01080E-03, relative residual:  3.35519E-18
### solver log, setup time:  1.76876E-02, solve time:  2.11090E-03, relative residual:  3.51167E-18
### solver log, setup time:  1.80688E-02, solve time:  2.29600E-03, relative residual:  3.33271E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      35, total time:  3.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.32891E-02, solve time:  2.00900E-03, relative residual:  3.31045E-18
### solver log, setup time:  2.09054E-02, solve time:  2.23680E-03, relative residual:  3.48577E-18
### solver log, setup time:  2.41916E-02, solve time:  2.01330E-03, relative residual:  3.42640E-18
### solver log, setup time:  1.82678E-02, solve time:  2.09300E-03, relative residual:  3.55827E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      36, total time:  3.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  4.64539E-02, solve time:  3.20460E-03, relative residual:  3.47388E-18
### solver log, setup time:  2.04842E-02, solve time:  2.06590E-03, relative residual:  3.46600E-18
### solver log, setup time:  2.18528E-02, solve time:  3.85680E-03, relative residual:  3.39363E-18
### solver log, setup time:  3.47735E-02, solve time:  1.41534E-02, relative residual:  3.29978E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      37, total time:  3.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.74521E-02, solve time:  4.15060E-03, relative residual:  3.36368E-18
### solver log, setup time:  4.88694E-02, solve time:  3.93400E-03, relative residual:  3.48440E-18
### solver log, setup time:  2.60033E-02, solve time:  2.27050E-03, relative residual:  3.45073E-18
### solver log, setup time:  2.08223E-02, solve time:  3.13850E-03, relative residual:  3.45724E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      38, total time:  3.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.00184E-02, solve time:  2.32960E-03, relative residual:  3.45866E-18
### solver log, setup time:  1.95898E-02, solve time:  2.10330E-03, relative residual:  3.47369E-18
### solver log, setup time:  1.89153E-02, solve time:  2.14580E-03, relative residual:  3.53180E-18
### solver log, setup time:  1.80364E-02, solve time:  2.10750E-03, relative residual:  3.33820E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      39, total time:  3.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.76079E-02, solve time:  2.29660E-03, relative residual:  3.39340E-18
### solver log, setup time:  1.76393E-02, solve time:  2.27100E-03, relative residual:  3.32525E-18
### solver log, setup time:  1.95943E-02, solve time:  2.20140E-03, relative residual:  3.49488E-18
### solver log, setup time:  1.90482E-02, solve time:  2.81670E-03, relative residual:  3.46494E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      40, total time:  4.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83583E-02, solve time:  2.16500E-03, relative residual:  3.25246E-18
### solver log, setup time:  3.94482E-02, solve time:  3.47280E-03, relative residual:  3.34759E-18
### solver log, setup time:  1.81972E-02, solve time:  2.32460E-03, relative residual:  3.35506E-18
### solver log, setup time:  1.92656E-02, solve time:  2.25790E-03, relative residual:  3.44223E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      41, total time:  4.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.04903E-02, solve time:  2.58620E-03, relative residual:  3.28752E-18
### solver log, setup time:  2.04546E-02, solve time:  2.75490E-03, relative residual:  3.61900E-18
### solver log, setup time:  1.94646E-02, solve time:  2.09920E-03, relative residual:  3.39849E-18
### solver log, setup time:  1.88626E-02, solve time:  2.27310E-03, relative residual:  3.47706E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      42, total time:  4.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.87979E-02, solve time:  2.13250E-03, relative residual:  3.49733E-18
### solver log, setup time:  1.91922E-02, solve time:  2.15900E-03, relative residual:  3.44967E-18
### solver log, setup time:  1.89774E-02, solve time:  2.29660E-03, relative residual:  3.79461E-18
### solver log, setup time:  2.03957E-02, solve time:  2.47580E-03, relative residual:  3.68249E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      43, total time:  4.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  3.08314E-02, solve time:  3.63920E-03, relative residual:  3.59110E-18
### solver log, setup time:  4.13994E-02, solve time:  3.88840E-03, relative residual:  3.38629E-18
### solver log, setup time:  2.20825E-02, solve time:  2.33220E-03, relative residual:  3.33668E-18
### solver log, setup time:  1.89066E-02, solve time:  2.24670E-03, relative residual:  3.51313E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      44, total time:  4.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86817E-02, solve time:  2.38530E-03, relative residual:  3.35022E-18
### solver log, setup time:  3.66778E-02, solve time:  2.16890E-03, relative residual:  3.45843E-18
### solver log, setup time:  2.29238E-02, solve time:  2.73000E-03, relative residual:  3.50646E-18
### solver log, setup time:  1.60864E-02, solve time:  2.58310E-03, relative residual:  3.77267E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      45, total time:  4.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.81646E-02, solve time:  2.51040E-03, relative residual:  3.34325E-18
### solver log, setup time:  1.76775E-02, solve time:  2.46040E-03, relative residual:  3.52317E-18
### solver log, setup time:  1.81348E-02, solve time:  2.80480E-03, relative residual:  3.47402E-18
### solver log, setup time:  1.93456E-02, solve time:  2.56230E-03, relative residual:  3.50849E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      46, total time:  4.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78828E-02, solve time:  2.42690E-03, relative residual:  3.39959E-18
### solver log, setup time:  2.35141E-02, solve time:  4.89940E-03, relative residual:  3.43921E-18
### solver log, setup time:  2.21199E-02, solve time:  2.09870E-03, relative residual:  3.43509E-18
### solver log, setup time:  1.93902E-02, solve time:  2.19110E-03, relative residual:  3.41391E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      47, total time:  4.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.17639E-02, solve time:  2.08380E-03, relative residual:  3.45498E-18
### solver log, setup time:  1.89931E-02, solve time:  3.19710E-03, relative residual:  3.38279E-18
### solver log, setup time:  1.90300E-02, solve time:  2.06590E-03, relative residual:  3.55210E-18
### solver log, setup time:  2.05468E-02, solve time:  2.53160E-03, relative residual:  3.49409E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      48, total time:  4.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.87288E-02, solve time:  2.09000E-03, relative residual:  3.41518E-18
### solver log, setup time:  2.59765E-02, solve time:  3.56750E-03, relative residual:  3.67223E-18
### solver log, setup time:  1.91089E-02, solve time:  2.87350E-03, relative residual:  3.58365E-18
### solver log, setup time:  2.07853E-02, solve time:  2.50050E-03, relative residual:  3.29844E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      49, total time:  4.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.16137E-02, solve time:  2.20150E-03, relative residual:  3.32628E-18
### solver log, setup time:  2.03859E-02, solve time:  2.42520E-03, relative residual:  3.54964E-18
### solver log, setup time:  2.44188E-02, solve time:  2.38850E-03, relative residual:  3.31631E-18
### solver log, setup time:  1.75772E-02, solve time:  2.35440E-03, relative residual:  3.62680E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      50, total time:  5.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.22235E-02, solve time:  2.98650E-03, relative residual:  3.37225E-18
### solver log, setup time:  2.11725E-02, solve time:  2.05390E-03, relative residual:  3.60878E-18
### solver log, setup time:  1.92110E-02, solve time:  2.92850E-03, relative residual:  3.29979E-18
### solver log, setup time:  2.26138E-02, solve time:  2.69220E-03, relative residual:  3.49654E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      51, total time:  5.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.02331E-02, solve time:  1.97390E-03, relative residual:  3.57911E-18
### solver log, setup time:  2.02734E-02, solve time:  2.27520E-03, relative residual:  3.48041E-18
### solver log, setup time:  3.24080E-02, solve time:  4.51010E-03, relative residual:  3.38941E-18
### solver log, setup time:  2.38066E-02, solve time:  2.55550E-03, relative residual:  3.59168E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      52, total time:  5.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.25442E-02, solve time:  2.59710E-03, relative residual:  3.43370E-18
### solver log, setup time:  2.43250E-02, solve time:  3.97690E-03, relative residual:  3.53695E-18
### solver log, setup time:  2.38616E-02, solve time:  2.14150E-03, relative residual:  3.34469E-18
### solver log, setup time:  1.81393E-02, solve time:  2.47530E-03, relative residual:  3.35493E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      53, total time:  5.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.13796E-02, solve time:  2.68840E-03, relative residual:  3.40131E-18
### solver log, setup time:  1.74873E-02, solve time:  2.12150E-03, relative residual:  3.50066E-18
### solver log, setup time:  1.71989E-02, solve time:  2.60540E-03, relative residual:  3.70205E-18
### solver log, setup time:  1.77075E-02, solve time:  2.26930E-03, relative residual:  3.57540E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      54, total time:  5.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.77834E-02, solve time:  2.71020E-03, relative residual:  3.51210E-18
### solver log, setup time:  2.46061E-02, solve time:  1.95100E-03, relative residual:  3.30864E-18
### solver log, setup time:  2.03519E-02, solve time:  2.94350E-03, relative residual:  3.44456E-18
### solver log, setup time:  1.98167E-02, solve time:  2.11880E-03, relative residual:  3.38427E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      55, total time:  5.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.67306E-02, solve time:  3.62870E-03, relative residual:  3.29835E-18
### solver log, setup time:  2.28662E-02, solve time:  2.30360E-03, relative residual:  3.51672E-18
### solver log, setup time:  1.81004E-02, solve time:  2.69950E-03, relative residual:  3.61424E-18
### solver log, setup time:  2.58281E-02, solve time:  3.45390E-03, relative residual:  3.59566E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      56, total time:  5.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.65627E-02, solve time:  2.82240E-03, relative residual:  3.71431E-18
### solver log, setup time:  1.98863E-02, solve time:  2.05310E-03, relative residual:  3.44401E-18
### solver log, setup time:  1.84646E-02, solve time:  2.32990E-03, relative residual:  3.57107E-18
### solver log, setup time:  1.96136E-02, solve time:  2.21020E-03, relative residual:  3.37141E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      57, total time:  5.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.07760E-02, solve time:  2.82510E-03, relative residual:  3.63818E-18
### solver log, setup time:  1.89142E-02, solve time:  2.34300E-03, relative residual:  3.43616E-18
### solver log, setup time:  1.87660E-02, solve time:  2.18580E-03, relative residual:  3.34403E-18
### solver log, setup time:  1.92823E-02, solve time:  2.16570E-03, relative residual:  3.42107E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      58, total time:  5.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.60196E-02, solve time:  3.57870E-03, relative residual:  3.40876E-18
### solver log, setup time:  2.50869E-02, solve time:  3.96430E-03, relative residual:  3.57121E-18
### solver log, setup time:  1.94955E-02, solve time:  2.63570E-03, relative residual:  3.56755E-18
### solver log, setup time:  1.92571E-02, solve time:  2.11450E-03, relative residual:  3.42531E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      59, total time:  5.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83570E-02, solve time:  2.27300E-03, relative residual:  3.65691E-18
### solver log, setup time:  1.88131E-02, solve time:  2.05170E-03, relative residual:  3.38360E-18
### solver log, setup time:  1.87836E-02, solve time:  2.20860E-03, relative residual:  3.74158E-18
### solver log, setup time:  1.83814E-02, solve time:  2.74420E-03, relative residual:  3.58466E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      60, total time:  6.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.98050E-02, solve time:  2.46040E-03, relative residual:  3.50066E-18
### solver log, setup time:  1.91805E-02, solve time:  2.11310E-03, relative residual:  3.60000E-18
### solver log, setup time:  1.78300E-02, solve time:  2.44550E-03, relative residual:  3.50753E-18
### solver log, setup time:  1.81652E-02, solve time:  2.13510E-03, relative residual:  3.68241E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      61, total time:  6.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78008E-02, solve time:  2.35380E-03, relative residual:  3.57893E-18
### solver log, setup time:  2.11182E-02, solve time:  2.43370E-03, relative residual:  3.82718E-18
### solver log, setup time:  1.73093E-02, solve time:  2.29390E-03, relative residual:  3.45377E-18
### solver log, setup time:  1.75246E-02, solve time:  2.36830E-03, relative residual:  3.50451E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      62, total time:  6.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.87436E-02, solve time:  2.46360E-03, relative residual:  3.55874E-18
### solver log, setup time:  1.78285E-02, solve time:  2.12370E-03, relative residual:  3.91532E-18
### solver log, setup time:  1.78130E-02, solve time:  2.25790E-03, relative residual:  3.40207E-18
### solver log, setup time:  1.93915E-02, solve time:  2.43400E-03, relative residual:  3.46598E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      63, total time:  6.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.74973E-02, solve time:  2.26840E-03, relative residual:  3.56582E-18
### solver log, setup time:  1.76502E-02, solve time:  2.55920E-03, relative residual:  3.46874E-18
### solver log, setup time:  2.01510E-02, solve time:  2.24610E-03, relative residual:  3.46058E-18
### solver log, setup time:  2.10617E-02, solve time:  2.04310E-03, relative residual:  3.43021E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      64, total time:  6.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.81834E-02, solve time:  3.19130E-03, relative residual:  3.71091E-18
### solver log, setup time:  2.63458E-02, solve time:  2.80520E-03, relative residual:  3.57251E-18
### solver log, setup time:  1.81116E-02, solve time:  3.27060E-03, relative residual:  3.42639E-18
### solver log, setup time:  1.90546E-02, solve time:  2.23590E-03, relative residual:  3.74548E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      65, total time:  6.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  4.46083E-02, solve time:  2.82400E-03, relative residual:  3.51013E-18
### solver log, setup time:  1.75504E-02, solve time:  2.29290E-03, relative residual:  3.53153E-18
### solver log, setup time:  1.88026E-02, solve time:  2.39650E-03, relative residual:  3.62434E-18
### solver log, setup time:  1.77357E-02, solve time:  2.20330E-03, relative residual:  3.57321E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      66, total time:  6.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.93611E-02, solve time:  2.24860E-03, relative residual:  3.67619E-18
### solver log, setup time:  1.85675E-02, solve time:  2.37920E-03, relative residual:  3.89220E-18
### solver log, setup time:  2.42066E-02, solve time:  2.29890E-03, relative residual:  3.50910E-18
### solver log, setup time:  2.01139E-02, solve time:  2.11690E-03, relative residual:  3.64769E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      67, total time:  6.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.10528E-02, solve time:  2.23290E-03, relative residual:  3.82242E-18
### solver log, setup time:  1.73227E-02, solve time:  2.35010E-03, relative residual:  3.99824E-18
### solver log, setup time:  1.78486E-02, solve time:  2.22760E-03, relative residual:  3.67076E-18
### solver log, setup time:  1.75148E-02, solve time:  2.28470E-03, relative residual:  3.54846E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      68, total time:  6.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.89096E-02, solve time:  2.49870E-03, relative residual:  3.59820E-18
### solver log, setup time:  2.05389E-02, solve time:  2.35490E-03, relative residual:  3.60591E-18
### solver log, setup time:  1.81804E-02, solve time:  2.33900E-03, relative residual:  3.55038E-18
### solver log, setup time:  1.85811E-02, solve time:  2.35190E-03, relative residual:  3.79316E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      69, total time:  6.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86163E-02, solve time:  2.18250E-03, relative residual:  3.88012E-18
### solver log, setup time:  2.03364E-02, solve time:  1.98820E-03, relative residual:  3.69471E-18
### solver log, setup time:  1.88036E-02, solve time:  2.47090E-03, relative residual:  3.83975E-18
### solver log, setup time:  2.16951E-02, solve time:  2.24950E-03, relative residual:  3.69908E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      70, total time:  7.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.73806E-02, solve time:  2.33590E-03, relative residual:  3.67229E-18
### solver log, setup time:  1.81346E-02, solve time:  2.18520E-03, relative residual:  3.86941E-18
### solver log, setup time:  1.85091E-02, solve time:  2.19540E-03, relative residual:  3.59008E-18
### solver log, setup time:  1.88331E-02, solve time:  2.42530E-03, relative residual:  3.76714E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      71, total time:  7.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.77287E-02, solve time:  2.37380E-03, relative residual:  3.93527E-18
### solver log, setup time:  1.76814E-02, solve time:  2.36520E-03, relative residual:  3.62456E-18
### solver log, setup time:  1.99354E-02, solve time:  2.36320E-03, relative residual:  3.79945E-18
### solver log, setup time:  1.73875E-02, solve time:  2.38590E-03, relative residual:  3.45046E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      72, total time:  7.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.77382E-02, solve time:  2.46820E-03, relative residual:  3.66096E-18
### solver log, setup time:  2.08198E-02, solve time:  2.13260E-03, relative residual:  3.59029E-18
### solver log, setup time:  2.20898E-02, solve time:  2.72130E-03, relative residual:  3.60406E-18
### solver log, setup time:  1.75441E-02, solve time:  2.72300E-03, relative residual:  3.71445E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      73, total time:  7.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82904E-02, solve time:  2.52030E-03, relative residual:  3.71702E-18
### solver log, setup time:  1.73531E-02, solve time:  2.20400E-03, relative residual:  3.53101E-18
### solver log, setup time:  1.74579E-02, solve time:  2.81790E-03, relative residual:  3.62730E-18
### solver log, setup time:  1.80390E-02, solve time:  2.21200E-03, relative residual:  3.57313E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      74, total time:  7.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.88813E-02, solve time:  2.30900E-03, relative residual:  3.77401E-18
### solver log, setup time:  1.81043E-02, solve time:  2.19380E-03, relative residual:  3.65824E-18
### solver log, setup time:  1.89337E-02, solve time:  2.10380E-03, relative residual:  3.69495E-18
### solver log, setup time:  1.82141E-02, solve time:  2.14780E-03, relative residual:  3.68883E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      75, total time:  7.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.20058E-02, solve time:  2.35010E-03, relative residual:  3.68207E-18
### solver log, setup time:  2.76712E-02, solve time:  3.62930E-03, relative residual:  3.44487E-18
### solver log, setup time:  1.87853E-02, solve time:  2.31700E-03, relative residual:  3.89753E-18
### solver log, setup time:  1.96063E-02, solve time:  3.28170E-03, relative residual:  3.78226E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      76, total time:  7.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.93793E-02, solve time:  2.36390E-03, relative residual:  3.77135E-18
### solver log, setup time:  2.06332E-02, solve time:  2.80110E-03, relative residual:  3.73373E-18
### solver log, setup time:  2.43565E-02, solve time:  3.29500E-03, relative residual:  3.75524E-18
### solver log, setup time:  3.02320E-02, solve time:  2.68490E-03, relative residual:  3.42464E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      77, total time:  7.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.94244E-02, solve time:  2.26290E-03, relative residual:  3.76020E-18
### solver log, setup time:  2.02760E-02, solve time:  2.40280E-03, relative residual:  3.62564E-18
### solver log, setup time:  2.35751E-02, solve time:  2.23890E-03, relative residual:  3.64766E-18
### solver log, setup time:  2.09702E-02, solve time:  2.22340E-03, relative residual:  3.85297E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      78, total time:  7.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.00629E-02, solve time:  2.20860E-03, relative residual:  3.85091E-18
### solver log, setup time:  1.78280E-02, solve time:  2.28020E-03, relative residual:  3.95725E-18
### solver log, setup time:  1.94390E-02, solve time:  2.97640E-03, relative residual:  3.79337E-18
### solver log, setup time:  1.86866E-02, solve time:  2.26210E-03, relative residual:  3.79436E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      79, total time:  7.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90217E-02, solve time:  2.70320E-03, relative residual:  3.73043E-18
### solver log, setup time:  1.75782E-02, solve time:  2.25840E-03, relative residual:  3.58876E-18
### solver log, setup time:  1.99414E-02, solve time:  3.22110E-03, relative residual:  3.73033E-18
### solver log, setup time:  1.83430E-02, solve time:  2.13030E-03, relative residual:  3.52504E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      80, total time:  8.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.97729E-02, solve time:  2.41630E-03, relative residual:  3.82623E-18
### solver log, setup time:  2.26381E-02, solve time:  2.20080E-03, relative residual:  3.76143E-18
### solver log, setup time:  2.27365E-02, solve time:  3.22700E-03, relative residual:  3.82997E-18
### solver log, setup time:  2.45698E-02, solve time:  2.50730E-03, relative residual:  3.74531E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      81, total time:  8.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.20475E-02, solve time:  2.80140E-03, relative residual:  3.77432E-18
### solver log, setup time:  2.44248E-02, solve time:  3.05510E-03, relative residual:  4.06921E-18
### solver log, setup time:  2.45640E-02, solve time:  2.13850E-03, relative residual:  3.95139E-18
### solver log, setup time:  2.37579E-02, solve time:  2.24170E-03, relative residual:  3.87484E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      82, total time:  8.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.38653E-02, solve time:  2.06950E-03, relative residual:  3.82015E-18
### solver log, setup time:  2.07989E-02, solve time:  4.36330E-03, relative residual:  3.95081E-18
### solver log, setup time:  2.38600E-02, solve time:  2.23380E-03, relative residual:  3.73063E-18
### solver log, setup time:  2.53148E-02, solve time:  3.15200E-03, relative residual:  3.81751E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      83, total time:  8.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.22523E-02, solve time:  2.19200E-03, relative residual:  3.65191E-18
### solver log, setup time:  2.99463E-02, solve time:  2.96350E-03, relative residual:  3.70413E-18
### solver log, setup time:  2.00829E-02, solve time:  2.37070E-03, relative residual:  3.84263E-18
### solver log, setup time:  2.09887E-02, solve time:  2.45710E-03, relative residual:  3.85016E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      84, total time:  8.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.19515E-02, solve time:  2.63670E-03, relative residual:  3.75082E-18
### solver log, setup time:  1.95196E-02, solve time:  2.43220E-03, relative residual:  3.73068E-18
### solver log, setup time:  1.82767E-02, solve time:  1.90900E-03, relative residual:  3.57970E-18
### solver log, setup time:  2.09209E-02, solve time:  2.14230E-03, relative residual:  3.91156E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      85, total time:  8.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.00113E-02, solve time:  2.11620E-03, relative residual:  3.84804E-18
### solver log, setup time:  1.79176E-02, solve time:  2.61590E-03, relative residual:  3.72316E-18
### solver log, setup time:  2.11532E-02, solve time:  2.29200E-03, relative residual:  3.70872E-18
### solver log, setup time:  1.90390E-02, solve time:  2.44880E-03, relative residual:  3.88177E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      86, total time:  8.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.08012E-02, solve time:  2.32890E-03, relative residual:  3.95522E-18
### solver log, setup time:  2.01104E-02, solve time:  2.06450E-03, relative residual:  3.79158E-18
### solver log, setup time:  1.82147E-02, solve time:  2.30480E-03, relative residual:  3.83634E-18
### solver log, setup time:  2.01269E-02, solve time:  2.14040E-03, relative residual:  3.91124E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      87, total time:  8.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.07525E-02, solve time:  2.28920E-03, relative residual:  3.85471E-18
### solver log, setup time:  1.91673E-02, solve time:  3.00950E-03, relative residual:  3.84534E-18
### solver log, setup time:  1.87494E-02, solve time:  2.01230E-03, relative residual:  3.97663E-18
### solver log, setup time:  1.93486E-02, solve time:  2.15000E-03, relative residual:  3.75200E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      88, total time:  8.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.05695E-02, solve time:  2.99650E-03, relative residual:  3.99160E-18
### solver log, setup time:  2.43757E-02, solve time:  2.39650E-03, relative residual:  3.90900E-18
### solver log, setup time:  2.12441E-02, solve time:  3.35920E-03, relative residual:  3.87858E-18
### solver log, setup time:  2.34030E-02, solve time:  2.60470E-03, relative residual:  3.62950E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      89, total time:  8.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.20711E-02, solve time:  2.04910E-03, relative residual:  3.73263E-18
### solver log, setup time:  2.01879E-02, solve time:  2.07450E-03, relative residual:  3.83099E-18
### solver log, setup time:  2.55539E-02, solve time:  2.28840E-03, relative residual:  3.82492E-18
### solver log, setup time:  1.87805E-02, solve time:  2.01200E-03, relative residual:  3.68506E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      90, total time:  9.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.13551E-02, solve time:  3.13810E-03, relative residual:  3.89876E-18
### solver log, setup time:  2.12996E-02, solve time:  2.59400E-03, relative residual:  3.78598E-18
### solver log, setup time:  1.77237E-02, solve time:  2.60950E-03, relative residual:  3.65953E-18
### solver log, setup time:  1.82529E-02, solve time:  2.52010E-03, relative residual:  3.77914E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      91, total time:  9.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.50727E-02, solve time:  2.05710E-03, relative residual:  4.09211E-18
### solver log, setup time:  1.80170E-02, solve time:  2.43700E-03, relative residual:  3.90468E-18
### solver log, setup time:  1.94103E-02, solve time:  2.20290E-03, relative residual:  4.08680E-18
### solver log, setup time:  2.63462E-02, solve time:  6.80990E-03, relative residual:  3.93213E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      92, total time:  9.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.87751E-02, solve time:  2.41100E-03, relative residual:  3.92422E-18
### solver log, setup time:  2.78457E-02, solve time:  3.21730E-03, relative residual:  3.95316E-18
### solver log, setup time:  2.20035E-02, solve time:  2.56290E-03, relative residual:  3.64750E-18
### solver log, setup time:  2.38821E-02, solve time:  2.54300E-03, relative residual:  3.81059E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      93, total time:  9.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95833E-02, solve time:  2.72420E-03, relative residual:  3.91556E-18
### solver log, setup time:  2.29725E-02, solve time:  2.79400E-03, relative residual:  3.79131E-18
### solver log, setup time:  2.41403E-02, solve time:  2.09440E-03, relative residual:  3.82681E-18
### solver log, setup time:  1.82458E-02, solve time:  2.06980E-03, relative residual:  3.68160E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      94, total time:  9.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.97719E-02, solve time:  2.31070E-03, relative residual:  4.01344E-18
### solver log, setup time:  2.00400E-02, solve time:  2.97380E-03, relative residual:  3.93442E-18
### solver log, setup time:  1.95140E-02, solve time:  2.14290E-03, relative residual:  3.77810E-18
### solver log, setup time:  1.93616E-02, solve time:  1.98910E-03, relative residual:  3.73560E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      95, total time:  9.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.72313E-02, solve time:  2.57480E-03, relative residual:  4.13130E-18
### solver log, setup time:  1.95463E-02, solve time:  2.01870E-03, relative residual:  3.87899E-18
### solver log, setup time:  2.10370E-02, solve time:  2.61650E-03, relative residual:  3.90273E-18
### solver log, setup time:  2.16387E-02, solve time:  2.17550E-03, relative residual:  3.71564E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      96, total time:  9.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  3.72024E-02, solve time:  2.57430E-03, relative residual:  3.84596E-18
### solver log, setup time:  2.06262E-02, solve time:  2.85200E-03, relative residual:  4.05941E-18
### solver log, setup time:  2.32321E-02, solve time:  2.11470E-03, relative residual:  3.94951E-18
### solver log, setup time:  2.36496E-02, solve time:  3.40890E-03, relative residual:  3.98061E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      97, total time:  9.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92678E-02, solve time:  2.40900E-03, relative residual:  3.98608E-18
### solver log, setup time:  1.78666E-02, solve time:  2.51130E-03, relative residual:  3.94712E-18
### solver log, setup time:  1.88459E-02, solve time:  2.04710E-03, relative residual:  3.96070E-18
### solver log, setup time:  1.90384E-02, solve time:  2.71340E-03, relative residual:  3.78081E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      98, total time:  9.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.33411E-02, solve time:  2.67800E-03, relative residual:  4.00467E-18
### solver log, setup time:  2.05287E-02, solve time:  2.53000E-03, relative residual:  4.23340E-18
### solver log, setup time:  2.43878E-02, solve time:  3.42100E-03, relative residual:  3.76323E-18
### solver log, setup time:  1.83422E-02, solve time:  2.15930E-03, relative residual:  3.93542E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      99, total time:  9.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.11775E-02, solve time:  1.96910E-03, relative residual:  3.86371E-18
### solver log, setup time:  1.91086E-02, solve time:  2.39120E-03, relative residual:  3.94464E-18
### solver log, setup time:  2.12492E-02, solve time:  3.06290E-03, relative residual:  3.87618E-18
### solver log, setup time:  2.36370E-02, solve time:  1.91780E-03, relative residual:  3.88340E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :     100, total time:  1.00000E+00, delta t:  1.00000E-02
### solver log, setup time:  2.33163E-02, solve time:  2.24830E-03, relative residual:  4.05781E-18
### solver log, setup time:  2.06796E-02, solve time:  2.04860E-03, relative residual:  3.88195E-18
### solver log, setup time:  1.90871E-02, solve time:  2.92070E-03, relative residual:  4.05007E-18
### solver log, setup time:  1.95286E-02, solve time:  2.32710E-03, relative residual:  4.14097E-18
  !!! CONVERGENCE ACHIEVED 
 ====================================
    TOTAL TIME (sec) :    200.57
           pre (sec) :      0.11
         solve (sec) :    200.46
 ====================================



 :========================================:
 :**            END of FSTR             **:
 :========================================:
