image: chainer/chainer:latest-python3

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - pip3 install --upgrade pip
 - "cat << EOF > /usr/bin/pip
import sys
from pip import __main__
if __name__ == '__main__':
    sys.exit(__main__._main())
EOF"
 - cat /usr/bin/pip3
 - pip3 install -r requirements.txt

stages:
  - test

test_gpu:
  stage: test
  script: python3 -m unittest discover tests
  tags:
    - gpu
