image: registry.ritc.jp/ricos/machine_learning/siml

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - cd lib/femio && python3.7 -m poetry config virtualenvs.create false && python3.7 -m poetry install && python3.7 -m poetry build && cd ../..
  - python3.7 -m poetry install
  - python3.7 -m poetry update

stages:
  - preprocess
  - test
  - deploy

preprocess:
  stage: preprocess
  script: python3.7 tests/preprocess.py
  artifacts:
    paths:
      - tests/data/linear/preprocessed
      - tests/data/deform/interim
      - tests/data/deform/preprocessed
    expire_in: 60min

autopep8:
  stage: preprocess
  script:
    - python3.7 -m autopep8 --diff --exit-code $(find siml tests -name "*.py")

pylint:
  stage: preprocess
  script:
    - python3.7 -m pylint --ignore-patterns=setting.py -E $(find siml tests -name "*.py")
  allow_failure: true

pages:
  stage: deploy
  script:
    - python3.7 -m make -C doc html
    - mv doc/_build/html public
  artifacts:
    paths:
      - public
  only:
    - master

.test:
  stage: test

test_gpu:
  extends: .test
  script:
    - python3.7 -m pytest tests/gpu/test_networks_gpu.py --capture=no
    - python3.7 -m pytest tests/gpu/test_trainer_gpu.py --capture=no
  tags:
    - gpu

test_gpu_optimize:
  extends: .test
  script: python3.7 -m pytest tests/gpu/test_optimize_gpu.py --capture=no
  tags:
    - gpu

test_networks:
  extends: .test
  script: python3.7 -m pytest tests/test_networks.py --capture=no

test_optimize:
  extends: .test
  script: python3.7 -m pytest tests/test_optimize.py --capture=no

test_prepost:
  extends: .test
  script: python3.7 -m pytest tests/test_prepost.py --capture=no

test_setting:
  extends: .test
  script: python3.7 -m pytest tests/test_setting.py --capture=no

test_trainer:
  extends: .test
  script: python3.7 -m pytest tests/test_trainer.py --capture=no

test_trainer_long:
  extends: .test
  script: python3.7 -m pytest tests/test_trainer_long.py --capture=no

test_util:
  extends: .test
  script: python3.7 -m pytest tests/test_util.py --capture=no
