image: nvidia/cuda

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - git clone https://github.com/pyenv/pyenv.git ~/.pyenv
 - export PYENV_ROOT="$HOME/.pyenv"
 - export PATH="$PYENV_ROOT/bin:$PATH"
 - if command -v pyenv 1>/dev/null 2>&1; then eval "$(pyenv init -)"; fi
 - pyenv install 3.7.3
 - pyenv global 3.7.3
 - python3 --version; which python3; which pip3
 - pip3 install -r requirements.txt
 - pip3 install cupy-cuda101

stages:
  - test

test_gpu:
  stage: test
  script: python3 -m unittest discover tests
  tags:
    - gpu
