image: chainer/chainer:latest-python3

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - which python3; which pip3
 - pip3 install -r requirements.txt

stages:
  - test

test_gpu:
  stage: test
  script: python3 -m unittest discover tests
  tags:
    - gpu
