image: python:3.7.3-stretch
variables:
  GIT_SUBMODULE_STRATEGY: recursive
before_script:
 - pip3 install -r requirements.txt
stages:
  - test_siml
test_siml:
  stage: test_siml
  script: which pip3; which python3; pip3 freeze; python3 -m unittest discover tests