image: tiangolo/python-machine-learning:cuda9.1-python3.7

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - python3 -V
 - python3 -m pip install -r requirements.txt
 - python3 -m pip install 'cupy-cuda91==7.0.0b2'
 - find / -name 'libcublas*'
 - python3 -c 'import chainer; print(chainer.cuda.available)'
 - python3 -c 'import cupy; print(cupy.is_available())'
stages:
  - test

test_gpu:
  stage: test
  script: python3 -m unittest discover tests
  tags:
    - gpu