image: python:3.7.3-stretch

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - pip3 install -r requirements.txt

stages:
  - test

test_siml:
  stage: test
  script: python3 -m unittest discover tests
  tags:
    - cpu
    - gpu
