image: registry.ritc.jp/ricos/machine_learning/siml

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - pip install pip poetry --upgrade
  - poetry config repositories.ricos https://pypi.ritc.jp
  - poetry config http-basic.ricos ricos ${RICOS_PYPI_KEY}
  - poetry install
  - poetry shell

stages:
  - preprocess
  - test

preprocess:
  stage: preprocess
  script: python3 tests/preprocess.py
  artifacts:
    paths:
      - tests/data/linear/preprocessed
      - tests/data/deform/interim
      - tests/data/deform/preprocessed
    expire_in: 60min

test_gpu:
  stage: test
  script:
    - python3 -m pytest tests/gpu/test_networks_gpu.py --capture=no
    - python3 -m pytest tests/gpu/test_trainer_gpu.py --capture=no
  tags:
    - gpu

test_gpu_optimize:
  stage: test
  script: python3 -m pytest tests/gpu/test_optimize_gpu.py --capture=no
  tags:
    - gpu

test_networks:
  stage: test
  script: python3 -m pytest tests/test_networks.py --capture=no

test_optimize:
  stage: test
  script: python3 -m pytest tests/test_optimize.py --capture=no

test_prepost:
  stage: test
  script: python3 -m pytest tests/test_prepost.py --capture=no

test_setting:
  stage: test
  script: python3 -m pytest tests/test_setting.py --capture=no

test_trainer:
  stage: test
  script: python3 -m pytest tests/test_trainer.py --capture=no

test_trainer_long:
  stage: test
  script: python3 -m pytest tests/test_trainer_long.py --capture=no

test_util:
  stage: test
  script: python3 -m pytest tests/test_util.py --capture=no
