image: registry.ritc.jp/ricos/machine_learning/siml

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - python3 -m pip install -r requirements.txt

stages:
  - test

test_gpu:
  stage: test
  script: python3 -m pytest tests --capture=no
  tags:
    - gpu
