image: tiangolo/python-machine-learning:cuda9.1-python3.7

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - apt -y update
 - apt -y install cuda-libraries-9-1 cuda-nvcc-9-1 cuda-libraries-dev-9-1

stages:
  - test

test_gpu:
  stage: test
  script: python3 -m unittest discover tests
  tags:
    - gpu
