image: registry.ritc.jp/ricos/machine_learning/siml

default:
  before_script:
    - poetry config virtualenvs.create false
    - poetry config repositories.ricos https://pypi.ritc.jp
    - poetry config http-basic.ricos ricos ${RICOS_PYPI_KEY}
    - poetry install

stages:
  - docker
  - preprocess
  - test
  - deploy

docker:
  image: docker:latest
  stage: docker
  inherit:
    default: false
  services:
    - docker:dind
  script:
    - apk add make
    - cd docker && make push key=${RICOS_PYPI_KEY}
  tags:
    - docker
    - gpu
  only:
    - master

preprocess:
  stage: preprocess
  script: python3.7 tests/preprocess.py
  artifacts:
    paths:
      - tests/data/linear/preprocessed
      - tests/data/deform/interim
      - tests/data/deform/preprocessed
      - tests/data/deform_timeseries/preprocessed
      - tests/data/rotation/preprocessed
      - tests/data/large/preprocessed
      - tests/data/ode/interim
      - tests/data/ode/preprocessed
      - tests/data/ode/preprocessed
    expire_in: 60min

autopep8:
  stage: preprocess
  script:
    - python3.7 -m autopep8 --diff --exit-code $(find siml tests -name "*.py")

pylint:
  stage: preprocess
  script:
    - python3.7 -m pylint --ignore-patterns=setting.py __main__ -E $(find siml tests -name "*.py" | grep -v __main__) --init-hook="import sys; sys.setrecursionlimit(2000)"

pages:
  stage: deploy
  script:
    - make -C doc html
    - mv doc/_build/html public
  artifacts:
    paths:
      - public
  only:
    - master

.test:
  stage: test

test_gpu_networks:
  extends: .test
  script:
    - python3.7 -m pytest tests/gpu/test_networks_gpu.py --capture=no
  tags:
    - multi-gpu

test_gpu:
  extends: .test
  script:
    - python3.7 -m pytest tests/gpu/test_optimize_gpu.py --capture=no
    - python3.7 -m pytest tests/gpu/test_trainer_gpu.py --capture=no
  tags:
    - multi-gpu

test_networks:
  extends: .test
  script: python3.7 -m pytest tests/test_networks.py --capture=no

test_optimize:
  extends: .test
  script: python3.7 -m pytest tests/test_optimize.py --capture=no

test_study:
  extends: .test
  script: python3.7 -m pytest tests/test_study.py --capture=no

test_trainer:
  extends: .test
  script: python3.7 -m pytest tests/test_trainer.py --capture=no

test_trainer_long:
  extends: .test
  script: python3.7 -m pytest tests/test_trainer_long.py --capture=no

test_other:
  extends: .test
  script:
    - python3.7 -m pytest tests/test_prepost.py --capture=no
    - python3.7 -m pytest tests/test_setting.py --capture=no
    - python3.7 -m pytest tests/test_util.py --capture=no
    - python3.7 -m pytest tests/test_inferer.py --capture=no

.deploy:wheel:
  stage: deploy
  script:
    - python3.7 -m pip install --upgrade pip
    - poetry version $VERSION
    - poetry config repositories.ricos https://pypi.ritc.jp
    - poetry build -f wheel
    - poetry publish --username ricos --password ${RICOS_PYPI_KEY} -r ricos --no-ansi -n -v
  retry: 2

deploy:wheel:master:
  extends: .deploy:wheel
  before_script:
    - export VERSION=0.2.1.dev$(date +"%Y%m%d%H%M")
  only:
    - master

deploy:wheel:tag:
  extends: .deploy:wheel
  before_script:
    - export VERSION=$CI_COMMIT_REF_NAME
  only:
    - tags
