image: python:3.7.3-stretch

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - pip3 install -r requirements.txt
 - which nvcc
 - if [ -x "$(command -v nvcc )" ]; then pip3 install cupy-cuda101; fi

stages:
  - test

test_gpu:
  stage: test
  script: python3 -m unittest discover tests
  tags:
    - gpu
