image: chainer/chainer:latest-python3

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - pip3 install --upgrade pip
 - "cat << EOF > /usr/bin/pip\nimport sys\nfrom pip import __main__\nif __name__ == '__main__':\n    sys.exit(__main__._main())\nEOF"
 - cat /usr/bin/pip3
 - pip3 install -r requirements.txt

stages:
  - test

test_gpu:
  stage: test
  script: python3 -m unittest discover tests
  tags:
    - gpu
