image: tiangolo/python-machine-learning:cuda9.1-python3.7

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - python3 -V
 - pip3 install -r requirements.txt

stages:
  - test

test_gpu:
  stage: test
  script: python3 -m unittest discover tests
  tags:
    - gpu
