image: chainer/chainer

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
 - python --version; which python; which pip
 - pip install -r requirements.txt
 - pip install cupy-cuda101

stages:
  - test

test_gpu:
  stage: test
  script: python -m unittest discover tests
  tags:
    - gpu
