image: registry.ritc.jp/ricos/machine_learning/siml:0.2.9

default:
  before_script:
    - poetry config virtualenvs.create false
    - poetry build
    - python3.9 -m pip uninstall -y femio pysiml
    - python3.9 -m pip install femio --pre
    - python3.9 -m pip install dist/pysiml-*.whl  # Only install root project, not dependencies
    # - poetry install

stages:
  - docker
  - preprocess
  - test
  - deploy

# docker:
#   image: docker:latest
#   stage: docker
#   inherit:
#     default: false
#   services:
#     - docker:dind
#   script:
#     - apk add make
#     - cd docker && make push key=${RICOS_PYPI_KEY}
#   tags:
#     - docker
#     - gpu
#   only:
#     - master

preprocess:
  stage: preprocess
  script:
    - python3.9 tests/preprocess.py
  artifacts:
    paths:
      - tests/data
    expire_in: 180min

generate_heat_steady:
  stage: preprocess
  script:
    - python3.9 tests/data/heat_steady/generate_data.py tests/data/heat_steady
  artifacts:
    paths:
      - tests/data/heat_steady
    expire_in: 180min

generate_advection:
  stage: preprocess
  script:
    - python3.9 tests/data/advection/generate_data.py tests/data/advection -n 10 -v 2
    - python3.9 tests/data/freeshape_advection/generate_data.py tests/data/freeshape_advection -n 10 -v 2
  artifacts:
    paths:
      - tests/data/advection
      - tests/data/freeshape_advection
    expire_in: 180min

autopep8:
  stage: preprocess
  script:
    - python3.9 -m autopep8 --diff --exit-code $(find siml tests -name "*.py")
  allow_failure: true

.test:
  stage: test
  tags:
    - avx

test_gpu:
  extends: .test
  script:
    - python3.9 -m pytest tests/test_gpu --capture=no
  tags:
    - multi-gpu
    - avx
    - sm_75

test_gpu_parallel:
  extends: .test
  script:
    - python3.9 -m pytest tests/test_gpu_parallel --capture=no
  allow_failure: true
  tags:
    - multi-gpu
    - avx
    - sm_61

test_networks:
  extends: .test
  script: python3.9 -m pytest tests/test_networks --capture=no

test_operation:
  extends: .test
  script: python3.9 -m pytest tests/test_operations --capture=no

test_trainer_wo_pyg:
  extends: .test
  script:
    - python3.9 -m pip uninstall torch-geometric -y
    - python3.9 -m pytest tests/test_operations/test_trainer.py --capture=no -k test_whole_process

test_trainer_long:
  extends: .test
  script: python3.9 -m pytest tests/test_trainer_long.py --capture=no

test_services:
  extends: .test
  script:
    - python3.9 -m pytest tests/test_services --capture=no
  tags:
    - gpu
    - sm_75

test_reproducibility:
  extends: .test
  script:
    - python3.9 tests/test_reproducibility/training_functions.py 11 0
    - python3.9 tests/test_reproducibility/training_functions.py 11 1
    - python3.9 tests/test_reproducibility/training_functions.py 23 0
    - python3.9 -m pytest tests/test_reproducibility/test_reproducibility.py --capture=no
  tags:
    - no-gpu

test_group:
  extends: .test
  script:
    - python3.9 -m pytest tests/test_groups.py --capture=no
  tags:
    - avx
    - gpu
    - sm_86

pages:
  stage: deploy
  script:
    - poetry build
    - python3.9 -m pip install dist/pysiml-*.whl
    - python3.9 -m pip install -r sphinx/requirements.txt
    - sphinx-apidoc -f -o ./sphinx siml
    - sphinx-build ./sphinx ./docs
    - cp -r docs public
    - mv dist/*.whl public/
  artifacts:
    paths:
      - public
      - docs
  tags:
    - avx
  only:
    - master
    - develop
    - fix_sphinx


.deploy:wheel:
  stage: deploy
  script:
    - python3.9 -m pip install --upgrade pip
    - poetry version $VERSION
    - poetry config repositories.ricos https://pypi.ritc.jp
    - poetry build -f wheel
    - poetry publish --username ricos --password ${RICOS_PYPI_KEY} -r ricos --no-ansi -n -v
    - poetry publish --username __token__ --password ${PYPI_ORG_TOKEN} --no-ansi -n -v
  retry: 2

deploy:wheel:master:
  extends: .deploy:wheel
  before_script:
    - export VERSION=$(grep "^version" pyproject.toml | grep -o "[0-9]\.[0-9]\.[0-9]").dev$(date +"%Y%m%d%H%M")
  only:
    - master
    - develop

deploy:wheel:tag:
  extends: .deploy:wheel
  before_script:
    - export VERSION=$CI_COMMIT_REF_NAME
  only:
    - tags
