 :========================================:
 :**   BEGIN FSTR Structural Analysis   **:
 :========================================:
         Total no. of processors:            1



  *    STAGE Initialization and input   **



  ***   STAGE Heat analysis    **
 =============================
   H E A T   T R A N S F E R  
 =============================
* Current step / Total step:        1/       1
* max iteration at each step:      100
* Transient anslysis
 ** Increment No. :       1, total time:  1.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  3.36396E-02, solve time:  3.04340E-03, relative residual:  6.73687E-18
### solver log, setup time:  2.04795E-02, solve time:  3.28430E-03, relative residual:  7.00106E-18
### solver log, setup time:  1.79651E-02, solve time:  2.49920E-03, relative residual:  6.66851E-18
### solver log, setup time:  1.75815E-02, solve time:  2.56670E-03, relative residual:  6.61532E-18
### solver log, setup time:  1.98781E-02, solve time:  2.62350E-03, relative residual:  6.59835E-18
### solver log, setup time:  1.98634E-02, solve time:  2.40200E-03, relative residual:  6.59893E-18
### solver log, setup time:  1.94865E-02, solve time:  2.20980E-03, relative residual:  6.50761E-18
### solver log, setup time:  1.88261E-02, solve time:  2.47440E-03, relative residual:  6.77416E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       2, total time:  2.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.83509E-02, solve time:  2.40990E-03, relative residual:  7.02382E-18
### solver log, setup time:  1.74341E-02, solve time:  2.74010E-03, relative residual:  7.03224E-18
### solver log, setup time:  1.72218E-02, solve time:  2.43970E-03, relative residual:  6.56128E-18
### solver log, setup time:  1.91837E-02, solve time:  2.29820E-03, relative residual:  6.85550E-18
### solver log, setup time:  1.77732E-02, solve time:  2.56460E-03, relative residual:  7.06280E-18
### solver log, setup time:  1.82636E-02, solve time:  2.48530E-03, relative residual:  6.66452E-18
### solver log, setup time:  1.70354E-02, solve time:  2.11880E-03, relative residual:  7.09755E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       3, total time:  3.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.80222E-02, solve time:  3.15160E-03, relative residual:  6.60461E-18
### solver log, setup time:  1.76519E-02, solve time:  2.10210E-03, relative residual:  6.70079E-18
### solver log, setup time:  1.74758E-02, solve time:  2.10980E-03, relative residual:  6.93510E-18
### solver log, setup time:  1.84870E-02, solve time:  2.40290E-03, relative residual:  6.68676E-18
### solver log, setup time:  1.80099E-02, solve time:  2.14460E-03, relative residual:  6.78455E-18
### solver log, setup time:  2.26923E-02, solve time:  2.90680E-03, relative residual:  6.84098E-18
### solver log, setup time:  2.42470E-02, solve time:  3.19470E-03, relative residual:  6.77229E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       4, total time:  4.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.07514E-02, solve time:  2.48270E-03, relative residual:  6.47657E-18
### solver log, setup time:  2.07816E-02, solve time:  2.05880E-03, relative residual:  6.61396E-18
### solver log, setup time:  1.86775E-02, solve time:  2.35030E-03, relative residual:  6.84625E-18
### solver log, setup time:  1.84734E-02, solve time:  2.32790E-03, relative residual:  6.86241E-18
### solver log, setup time:  2.14213E-02, solve time:  3.30980E-03, relative residual:  6.68602E-18
### solver log, setup time:  1.98600E-02, solve time:  2.45700E-03, relative residual:  6.81969E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       5, total time:  5.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.77150E-02, solve time:  2.44870E-03, relative residual:  6.41103E-18
### solver log, setup time:  2.15506E-02, solve time:  2.02270E-03, relative residual:  6.37938E-18
### solver log, setup time:  2.15090E-02, solve time:  2.61940E-03, relative residual:  6.62324E-18
### solver log, setup time:  2.78392E-02, solve time:  3.10650E-03, relative residual:  6.37797E-18
### solver log, setup time:  1.97379E-02, solve time:  2.88480E-03, relative residual:  6.47134E-18
### solver log, setup time:  2.16000E-02, solve time:  2.92250E-03, relative residual:  6.36940E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       6, total time:  6.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.58296E-02, solve time:  2.80720E-03, relative residual:  6.49949E-18
### solver log, setup time:  1.91352E-02, solve time:  1.94760E-03, relative residual:  6.27707E-18
### solver log, setup time:  2.22882E-02, solve time:  2.97670E-03, relative residual:  6.61832E-18
### solver log, setup time:  1.90695E-02, solve time:  2.36070E-03, relative residual:  6.37755E-18
### solver log, setup time:  1.78858E-02, solve time:  2.16870E-03, relative residual:  6.49231E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       7, total time:  7.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.68021E-02, solve time:  3.00830E-03, relative residual:  6.47841E-18
### solver log, setup time:  2.43267E-02, solve time:  3.15020E-03, relative residual:  6.39878E-18
### solver log, setup time:  3.36058E-02, solve time:  4.10360E-03, relative residual:  6.23640E-18
### solver log, setup time:  2.47086E-02, solve time:  2.53980E-03, relative residual:  6.39440E-18
### solver log, setup time:  2.05970E-02, solve time:  1.96010E-03, relative residual:  6.34470E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       8, total time:  8.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.03978E-02, solve time:  1.91010E-03, relative residual:  6.57050E-18
### solver log, setup time:  2.10479E-02, solve time:  2.17220E-03, relative residual:  6.59919E-18
### solver log, setup time:  2.93547E-02, solve time:  4.02540E-03, relative residual:  6.48451E-18
### solver log, setup time:  3.33113E-02, solve time:  2.03290E-03, relative residual:  6.27825E-18
### solver log, setup time:  2.09217E-02, solve time:  2.08540E-03, relative residual:  6.35571E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       9, total time:  9.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.16825E-02, solve time:  2.02250E-03, relative residual:  6.52386E-18
### solver log, setup time:  2.27427E-02, solve time:  2.17760E-03, relative residual:  6.48713E-18
### solver log, setup time:  1.92246E-02, solve time:  2.28060E-03, relative residual:  6.22505E-18
### solver log, setup time:  2.02145E-02, solve time:  2.59900E-03, relative residual:  6.52599E-18
### solver log, setup time:  2.69893E-02, solve time:  3.16370E-03, relative residual:  6.44415E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      10, total time:  1.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.00258E-02, solve time:  2.93270E-03, relative residual:  6.32554E-18
### solver log, setup time:  2.51363E-02, solve time:  2.06900E-03, relative residual:  6.26460E-18
### solver log, setup time:  3.86222E-02, solve time:  5.35170E-03, relative residual:  6.19082E-18
### solver log, setup time:  1.96970E-02, solve time:  3.46250E-03, relative residual:  6.45877E-18
### solver log, setup time:  2.11504E-02, solve time:  2.06100E-03, relative residual:  6.34417E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      11, total time:  1.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.82151E-02, solve time:  2.31630E-03, relative residual:  6.55493E-18
### solver log, setup time:  2.49024E-02, solve time:  2.18200E-03, relative residual:  6.57065E-18
### solver log, setup time:  2.75508E-02, solve time:  3.05570E-03, relative residual:  6.50395E-18
### solver log, setup time:  2.85622E-02, solve time:  2.11630E-03, relative residual:  6.53286E-18
### solver log, setup time:  2.10050E-02, solve time:  2.56720E-03, relative residual:  6.77669E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      12, total time:  1.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.26303E-02, solve time:  2.59990E-03, relative residual:  6.35779E-18
### solver log, setup time:  2.46559E-02, solve time:  2.17820E-03, relative residual:  6.52386E-18
### solver log, setup time:  2.77685E-02, solve time:  4.52230E-03, relative residual:  6.45051E-18
### solver log, setup time:  2.78366E-02, solve time:  2.26240E-03, relative residual:  6.54430E-18
### solver log, setup time:  2.19686E-02, solve time:  2.62560E-03, relative residual:  6.60615E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      13, total time:  1.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.74121E-02, solve time:  3.23070E-03, relative residual:  6.31698E-18
### solver log, setup time:  2.36745E-02, solve time:  2.58420E-03, relative residual:  6.87102E-18
### solver log, setup time:  2.01713E-02, solve time:  3.06120E-03, relative residual:  6.50526E-18
### solver log, setup time:  2.09914E-02, solve time:  1.99930E-03, relative residual:  6.75309E-18
### solver log, setup time:  1.91095E-02, solve time:  2.27140E-03, relative residual:  6.60397E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      14, total time:  1.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.94318E-02, solve time:  2.03490E-03, relative residual:  6.53950E-18
### solver log, setup time:  2.41457E-02, solve time:  2.77090E-03, relative residual:  6.32847E-18
### solver log, setup time:  2.46908E-02, solve time:  3.83900E-03, relative residual:  6.78407E-18
### solver log, setup time:  2.12724E-02, solve time:  2.08280E-03, relative residual:  6.80732E-18
### solver log, setup time:  1.82425E-02, solve time:  3.05530E-03, relative residual:  6.68691E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      15, total time:  1.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.13893E-02, solve time:  2.71120E-03, relative residual:  6.50620E-18
### solver log, setup time:  1.89293E-02, solve time:  2.11340E-03, relative residual:  6.35958E-18
### solver log, setup time:  2.09242E-02, solve time:  2.51020E-03, relative residual:  6.60371E-18
### solver log, setup time:  2.12415E-02, solve time:  1.76080E-03, relative residual:  6.45697E-18
### solver log, setup time:  1.82222E-02, solve time:  2.01480E-03, relative residual:  6.70605E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      16, total time:  1.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.02197E-02, solve time:  2.23750E-03, relative residual:  6.80055E-18
### solver log, setup time:  2.07026E-02, solve time:  1.96620E-03, relative residual:  6.60064E-18
### solver log, setup time:  2.16050E-02, solve time:  2.15220E-03, relative residual:  6.62112E-18
### solver log, setup time:  1.84727E-02, solve time:  2.36590E-03, relative residual:  6.55887E-18
### solver log, setup time:  2.01161E-02, solve time:  2.10330E-03, relative residual:  6.42783E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      17, total time:  1.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79391E-02, solve time:  2.47540E-03, relative residual:  6.65333E-18
### solver log, setup time:  2.02950E-02, solve time:  1.99570E-03, relative residual:  6.58509E-18
### solver log, setup time:  1.91267E-02, solve time:  2.06820E-03, relative residual:  6.72119E-18
### solver log, setup time:  1.83037E-02, solve time:  2.57120E-03, relative residual:  6.84676E-18
### solver log, setup time:  1.99017E-02, solve time:  2.38740E-03, relative residual:  6.65253E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      18, total time:  1.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82207E-02, solve time:  2.40900E-03, relative residual:  7.00587E-18
### solver log, setup time:  1.93487E-02, solve time:  2.04860E-03, relative residual:  6.74077E-18
### solver log, setup time:  1.84390E-02, solve time:  2.08340E-03, relative residual:  6.85110E-18
### solver log, setup time:  2.23619E-02, solve time:  2.28060E-03, relative residual:  6.75117E-18
### solver log, setup time:  1.84797E-02, solve time:  1.91910E-03, relative residual:  6.99692E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      19, total time:  1.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92522E-02, solve time:  2.27980E-03, relative residual:  6.56077E-18
### solver log, setup time:  1.81199E-02, solve time:  2.14100E-03, relative residual:  6.63122E-18
### solver log, setup time:  1.80403E-02, solve time:  2.36500E-03, relative residual:  6.73650E-18
### solver log, setup time:  1.84050E-02, solve time:  2.29660E-03, relative residual:  7.02789E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      20, total time:  2.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.85327E-02, solve time:  2.24950E-03, relative residual:  7.04531E-18
### solver log, setup time:  2.27232E-02, solve time:  2.13590E-03, relative residual:  6.90344E-18
### solver log, setup time:  1.79982E-02, solve time:  2.56130E-03, relative residual:  6.71321E-18
### solver log, setup time:  1.96564E-02, solve time:  2.32860E-03, relative residual:  6.70878E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      21, total time:  2.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.85096E-02, solve time:  2.17270E-03, relative residual:  6.81900E-18
### solver log, setup time:  2.03207E-02, solve time:  2.17760E-03, relative residual:  7.00794E-18
### solver log, setup time:  1.93223E-02, solve time:  2.09700E-03, relative residual:  6.92685E-18
### solver log, setup time:  2.06892E-02, solve time:  2.10170E-03, relative residual:  6.72146E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      22, total time:  2.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83168E-02, solve time:  1.93720E-03, relative residual:  6.90113E-18
### solver log, setup time:  1.80608E-02, solve time:  2.22770E-03, relative residual:  6.81958E-18
### solver log, setup time:  1.99470E-02, solve time:  2.16500E-03, relative residual:  6.83643E-18
### solver log, setup time:  1.83721E-02, solve time:  2.53990E-03, relative residual:  6.79499E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      23, total time:  2.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.87107E-02, solve time:  2.08800E-03, relative residual:  6.84641E-18
### solver log, setup time:  2.18941E-02, solve time:  2.74430E-03, relative residual:  7.07834E-18
### solver log, setup time:  1.81639E-02, solve time:  2.16130E-03, relative residual:  7.10351E-18
### solver log, setup time:  1.81778E-02, solve time:  2.08780E-03, relative residual:  6.60642E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      24, total time:  2.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.85325E-02, solve time:  2.41500E-03, relative residual:  6.81020E-18
### solver log, setup time:  1.88910E-02, solve time:  2.03890E-03, relative residual:  6.80064E-18
### solver log, setup time:  1.85511E-02, solve time:  2.13630E-03, relative residual:  6.97013E-18
### solver log, setup time:  1.83126E-02, solve time:  2.33720E-03, relative residual:  7.03308E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      25, total time:  2.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.01535E-02, solve time:  2.04850E-03, relative residual:  7.08983E-18
### solver log, setup time:  1.78400E-02, solve time:  2.19890E-03, relative residual:  6.98182E-18
### solver log, setup time:  1.79410E-02, solve time:  2.22730E-03, relative residual:  6.81054E-18
### solver log, setup time:  1.80857E-02, solve time:  2.01310E-03, relative residual:  6.92236E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      26, total time:  2.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.25753E-02, solve time:  2.21400E-03, relative residual:  6.86379E-18
### solver log, setup time:  1.80760E-02, solve time:  2.70150E-03, relative residual:  7.08575E-18
### solver log, setup time:  1.93636E-02, solve time:  2.16780E-03, relative residual:  7.07181E-18
### solver log, setup time:  1.97996E-02, solve time:  2.26260E-03, relative residual:  7.00140E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      27, total time:  2.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.98167E-02, solve time:  2.07460E-03, relative residual:  6.84594E-18
### solver log, setup time:  1.84274E-02, solve time:  2.31650E-03, relative residual:  7.20601E-18
### solver log, setup time:  1.95316E-02, solve time:  2.29370E-03, relative residual:  7.26189E-18
### solver log, setup time:  1.87577E-02, solve time:  2.60620E-03, relative residual:  7.15768E-18
### solver log, setup time:  1.82818E-02, solve time:  2.43150E-03, relative residual:  7.28461E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      28, total time:  2.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.91910E-02, solve time:  1.94230E-03, relative residual:  7.10902E-18
### solver log, setup time:  1.84765E-02, solve time:  2.41670E-03, relative residual:  6.90229E-18
### solver log, setup time:  2.00389E-02, solve time:  2.20290E-03, relative residual:  6.99148E-18
### solver log, setup time:  1.84238E-02, solve time:  2.26800E-03, relative residual:  7.10380E-18
### solver log, setup time:  1.80761E-02, solve time:  2.35810E-03, relative residual:  7.47901E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      29, total time:  2.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  3.14565E-02, solve time:  3.03400E-03, relative residual:  7.28752E-18
### solver log, setup time:  2.44226E-02, solve time:  2.28500E-03, relative residual:  6.87975E-18
### solver log, setup time:  1.83641E-02, solve time:  2.18490E-03, relative residual:  6.92798E-18
### solver log, setup time:  1.85167E-02, solve time:  2.33720E-03, relative residual:  7.64509E-18
### solver log, setup time:  2.02174E-02, solve time:  1.93750E-03, relative residual:  7.42729E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      30, total time:  3.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82828E-02, solve time:  2.09560E-03, relative residual:  6.94060E-18
### solver log, setup time:  1.80153E-02, solve time:  2.15160E-03, relative residual:  7.39792E-18
### solver log, setup time:  1.85142E-02, solve time:  2.24050E-03, relative residual:  7.19658E-18
### solver log, setup time:  2.03380E-02, solve time:  2.21420E-03, relative residual:  7.27995E-18
### solver log, setup time:  1.87004E-02, solve time:  1.95800E-03, relative residual:  7.46246E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      31, total time:  3.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.91545E-02, solve time:  2.76220E-03, relative residual:  7.49614E-18
### solver log, setup time:  1.95684E-02, solve time:  2.38370E-03, relative residual:  7.25864E-18
### solver log, setup time:  1.81542E-02, solve time:  2.30090E-03, relative residual:  7.59164E-18
### solver log, setup time:  1.96075E-02, solve time:  2.31160E-03, relative residual:  7.19647E-18
### solver log, setup time:  2.13019E-02, solve time:  2.73660E-03, relative residual:  7.10412E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      32, total time:  3.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.85570E-02, solve time:  2.38880E-03, relative residual:  7.46813E-18
### solver log, setup time:  1.86534E-02, solve time:  2.23570E-03, relative residual:  7.44361E-18
### solver log, setup time:  1.91199E-02, solve time:  2.45270E-03, relative residual:  7.13800E-18
### solver log, setup time:  1.88333E-02, solve time:  2.75970E-03, relative residual:  7.41214E-18
### solver log, setup time:  1.90300E-02, solve time:  2.14870E-03, relative residual:  7.32942E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      33, total time:  3.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86802E-02, solve time:  1.94910E-03, relative residual:  7.52407E-18
### solver log, setup time:  2.18106E-02, solve time:  2.31190E-03, relative residual:  7.43217E-18
### solver log, setup time:  1.82552E-02, solve time:  2.25560E-03, relative residual:  7.43147E-18
### solver log, setup time:  2.04489E-02, solve time:  5.62230E-03, relative residual:  7.31887E-18
### solver log, setup time:  1.93562E-02, solve time:  2.02490E-03, relative residual:  7.23274E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      34, total time:  3.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80686E-02, solve time:  2.52520E-03, relative residual:  7.25004E-18
### solver log, setup time:  1.88684E-02, solve time:  2.41720E-03, relative residual:  7.30318E-18
### solver log, setup time:  1.86200E-02, solve time:  2.20040E-03, relative residual:  7.46970E-18
### solver log, setup time:  1.94819E-02, solve time:  2.29420E-03, relative residual:  7.72909E-18
### solver log, setup time:  2.09943E-02, solve time:  2.62410E-03, relative residual:  7.33550E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      35, total time:  3.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82489E-02, solve time:  2.68350E-03, relative residual:  7.91543E-18
### solver log, setup time:  1.84666E-02, solve time:  2.48100E-03, relative residual:  7.28555E-18
### solver log, setup time:  2.12464E-02, solve time:  2.52940E-03, relative residual:  7.78451E-18
### solver log, setup time:  1.89090E-02, solve time:  2.54350E-03, relative residual:  7.45514E-18
### solver log, setup time:  1.98827E-02, solve time:  2.92660E-03, relative residual:  7.41235E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      36, total time:  3.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82120E-02, solve time:  2.65700E-03, relative residual:  7.43280E-18
### solver log, setup time:  1.93043E-02, solve time:  2.25310E-03, relative residual:  7.44574E-18
### solver log, setup time:  1.83338E-02, solve time:  2.38430E-03, relative residual:  7.59077E-18
### solver log, setup time:  1.83733E-02, solve time:  2.17260E-03, relative residual:  7.64440E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      37, total time:  3.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92200E-02, solve time:  2.73760E-03, relative residual:  7.81358E-18
### solver log, setup time:  2.13079E-02, solve time:  1.71780E-03, relative residual:  7.33272E-18
### solver log, setup time:  1.88790E-02, solve time:  2.10220E-03, relative residual:  7.84741E-18
### solver log, setup time:  1.83306E-02, solve time:  2.32250E-03, relative residual:  7.49018E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      38, total time:  3.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.94478E-02, solve time:  2.34040E-03, relative residual:  7.37443E-18
### solver log, setup time:  2.20290E-02, solve time:  2.09410E-03, relative residual:  7.70376E-18
### solver log, setup time:  1.82458E-02, solve time:  2.18030E-03, relative residual:  7.82735E-18
### solver log, setup time:  1.94763E-02, solve time:  2.53500E-03, relative residual:  7.56448E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      39, total time:  3.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80002E-02, solve time:  1.92180E-03, relative residual:  8.09769E-18
### solver log, setup time:  1.96002E-02, solve time:  2.23480E-03, relative residual:  7.85925E-18
### solver log, setup time:  1.78705E-02, solve time:  2.39510E-03, relative residual:  7.97140E-18
### solver log, setup time:  1.85737E-02, solve time:  2.24110E-03, relative residual:  7.68519E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      40, total time:  4.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.09677E-02, solve time:  2.25850E-03, relative residual:  7.70307E-18
### solver log, setup time:  1.96216E-02, solve time:  2.23080E-03, relative residual:  8.24830E-18
### solver log, setup time:  2.03383E-02, solve time:  2.87590E-03, relative residual:  7.93775E-18
### solver log, setup time:  1.95998E-02, solve time:  2.55790E-03, relative residual:  7.70831E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      41, total time:  4.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.98618E-02, solve time:  2.12070E-03, relative residual:  7.61236E-18
### solver log, setup time:  2.06352E-02, solve time:  2.11490E-03, relative residual:  7.81616E-18
### solver log, setup time:  1.99453E-02, solve time:  2.02930E-03, relative residual:  7.58794E-18
### solver log, setup time:  2.11609E-02, solve time:  2.24270E-03, relative residual:  7.91026E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      42, total time:  4.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83295E-02, solve time:  2.26920E-03, relative residual:  7.82981E-18
### solver log, setup time:  2.01133E-02, solve time:  2.48770E-03, relative residual:  8.10647E-18
### solver log, setup time:  1.77689E-02, solve time:  2.22860E-03, relative residual:  7.79238E-18
### solver log, setup time:  1.81521E-02, solve time:  2.24640E-03, relative residual:  7.88311E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      43, total time:  4.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90072E-02, solve time:  2.30740E-03, relative residual:  8.07692E-18
### solver log, setup time:  2.00539E-02, solve time:  2.38450E-03, relative residual:  7.42726E-18
### solver log, setup time:  1.80234E-02, solve time:  2.19160E-03, relative residual:  7.70112E-18
### solver log, setup time:  1.81034E-02, solve time:  2.39400E-03, relative residual:  7.97146E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      44, total time:  4.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80964E-02, solve time:  2.18930E-03, relative residual:  7.98994E-18
### solver log, setup time:  2.01232E-02, solve time:  2.10190E-03, relative residual:  8.14085E-18
### solver log, setup time:  1.76261E-02, solve time:  2.54450E-03, relative residual:  7.58005E-18
### solver log, setup time:  1.78117E-02, solve time:  2.19300E-03, relative residual:  7.87365E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      45, total time:  4.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.81746E-02, solve time:  2.30130E-03, relative residual:  8.17362E-18
### solver log, setup time:  1.84612E-02, solve time:  2.33930E-03, relative residual:  7.88479E-18
### solver log, setup time:  1.95021E-02, solve time:  2.40400E-03, relative residual:  8.21485E-18
### solver log, setup time:  1.95653E-02, solve time:  1.95220E-03, relative residual:  7.96763E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      46, total time:  4.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.74768E-02, solve time:  1.93750E-03, relative residual:  7.82129E-18
### solver log, setup time:  1.82185E-02, solve time:  2.24840E-03, relative residual:  7.84496E-18
### solver log, setup time:  2.04964E-02, solve time:  3.59420E-03, relative residual:  8.03862E-18
### solver log, setup time:  1.83141E-02, solve time:  2.09980E-03, relative residual:  8.08717E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      47, total time:  4.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.04674E-02, solve time:  2.58040E-03, relative residual:  8.61569E-18
### solver log, setup time:  1.80335E-02, solve time:  2.28410E-03, relative residual:  8.29793E-18
### solver log, setup time:  1.81037E-02, solve time:  2.40870E-03, relative residual:  8.28234E-18
### solver log, setup time:  1.91159E-02, solve time:  2.05870E-03, relative residual:  8.09801E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      48, total time:  4.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90066E-02, solve time:  2.44360E-03, relative residual:  8.16176E-18
### solver log, setup time:  1.84033E-02, solve time:  2.19570E-03, relative residual:  7.67669E-18
### solver log, setup time:  1.92121E-02, solve time:  2.11750E-03, relative residual:  8.11206E-18
### solver log, setup time:  1.87049E-02, solve time:  2.20610E-03, relative residual:  8.13946E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      49, total time:  4.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79501E-02, solve time:  2.11340E-03, relative residual:  8.18160E-18
### solver log, setup time:  1.78267E-02, solve time:  2.52900E-03, relative residual:  7.73824E-18
### solver log, setup time:  1.99075E-02, solve time:  2.32850E-03, relative residual:  7.83054E-18
### solver log, setup time:  1.82790E-02, solve time:  2.17250E-03, relative residual:  8.62069E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      50, total time:  5.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.11302E-02, solve time:  2.02020E-03, relative residual:  8.49361E-18
### solver log, setup time:  2.00716E-02, solve time:  2.49750E-03, relative residual:  8.23096E-18
### solver log, setup time:  1.94613E-02, solve time:  2.55010E-03, relative residual:  8.77299E-18
### solver log, setup time:  1.93540E-02, solve time:  2.33350E-03, relative residual:  8.32503E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      51, total time:  5.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82177E-02, solve time:  2.13120E-03, relative residual:  8.01526E-18
### solver log, setup time:  2.00710E-02, solve time:  2.47260E-03, relative residual:  8.21799E-18
### solver log, setup time:  1.88925E-02, solve time:  2.17700E-03, relative residual:  8.34586E-18
### solver log, setup time:  1.89734E-02, solve time:  2.29320E-03, relative residual:  8.20644E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      52, total time:  5.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.93097E-02, solve time:  2.19510E-03, relative residual:  8.13215E-18
### solver log, setup time:  1.80113E-02, solve time:  2.08910E-03, relative residual:  8.20512E-18
### solver log, setup time:  2.38630E-02, solve time:  2.97390E-03, relative residual:  8.15323E-18
### solver log, setup time:  1.85972E-02, solve time:  2.27370E-03, relative residual:  8.50079E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      53, total time:  5.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80952E-02, solve time:  2.03880E-03, relative residual:  8.61729E-18
### solver log, setup time:  1.83687E-02, solve time:  2.09830E-03, relative residual:  8.60473E-18
### solver log, setup time:  1.81687E-02, solve time:  2.28370E-03, relative residual:  8.58019E-18
### solver log, setup time:  1.83295E-02, solve time:  2.78660E-03, relative residual:  8.30378E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      54, total time:  5.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.81368E-02, solve time:  5.35700E-03, relative residual:  8.53764E-18
### solver log, setup time:  1.84457E-02, solve time:  2.07140E-03, relative residual:  8.45784E-18
### solver log, setup time:  1.97451E-02, solve time:  2.18270E-03, relative residual:  8.42024E-18
### solver log, setup time:  1.91517E-02, solve time:  2.19940E-03, relative residual:  8.25713E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      55, total time:  5.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.81483E-02, solve time:  2.33280E-03, relative residual:  8.55768E-18
### solver log, setup time:  1.80349E-02, solve time:  2.31340E-03, relative residual:  8.35560E-18
### solver log, setup time:  1.80397E-02, solve time:  2.06260E-03, relative residual:  8.35097E-18
### solver log, setup time:  1.89645E-02, solve time:  2.14890E-03, relative residual:  8.48258E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      56, total time:  5.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82372E-02, solve time:  2.22130E-03, relative residual:  8.88813E-18
### solver log, setup time:  1.98517E-02, solve time:  2.64740E-03, relative residual:  8.56724E-18
### solver log, setup time:  1.96711E-02, solve time:  2.32280E-03, relative residual:  8.58825E-18
### solver log, setup time:  1.74361E-02, solve time:  2.12360E-03, relative residual:  8.34901E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      57, total time:  5.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95540E-02, solve time:  2.42070E-03, relative residual:  8.29829E-18
### solver log, setup time:  1.89670E-02, solve time:  2.13550E-03, relative residual:  8.54300E-18
### solver log, setup time:  1.85039E-02, solve time:  2.37320E-03, relative residual:  8.08519E-18
### solver log, setup time:  1.79711E-02, solve time:  2.28230E-03, relative residual:  8.17216E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      58, total time:  5.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.87500E-02, solve time:  2.39590E-03, relative residual:  9.02856E-18
### solver log, setup time:  1.76628E-02, solve time:  1.97720E-03, relative residual:  8.50555E-18
### solver log, setup time:  1.94131E-02, solve time:  2.23980E-03, relative residual:  8.46890E-18
### solver log, setup time:  1.83724E-02, solve time:  2.36600E-03, relative residual:  8.74848E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      59, total time:  5.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.96373E-02, solve time:  2.11580E-03, relative residual:  8.94784E-18
### solver log, setup time:  1.90671E-02, solve time:  2.22820E-03, relative residual:  9.02999E-18
### solver log, setup time:  1.79662E-02, solve time:  2.37420E-03, relative residual:  8.57826E-18
### solver log, setup time:  2.01853E-02, solve time:  2.25430E-03, relative residual:  8.25504E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      60, total time:  6.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95646E-02, solve time:  2.52890E-03, relative residual:  8.27480E-18
### solver log, setup time:  1.90620E-02, solve time:  2.27250E-03, relative residual:  8.35672E-18
### solver log, setup time:  2.00673E-02, solve time:  2.16760E-03, relative residual:  8.58703E-18
### solver log, setup time:  1.80888E-02, solve time:  2.17710E-03, relative residual:  9.23429E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      61, total time:  6.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92986E-02, solve time:  2.28280E-03, relative residual:  8.07301E-18
### solver log, setup time:  1.75746E-02, solve time:  2.02650E-03, relative residual:  9.40634E-18
### solver log, setup time:  1.88919E-02, solve time:  2.24170E-03, relative residual:  8.62344E-18
### solver log, setup time:  1.81831E-02, solve time:  1.98930E-03, relative residual:  9.52375E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      62, total time:  6.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78568E-02, solve time:  2.60730E-03, relative residual:  9.04169E-18
### solver log, setup time:  1.90191E-02, solve time:  2.04890E-03, relative residual:  9.07412E-18
### solver log, setup time:  3.13753E-02, solve time:  2.17930E-03, relative residual:  8.53403E-18
### solver log, setup time:  1.81580E-02, solve time:  2.17820E-03, relative residual:  8.95015E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      63, total time:  6.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.96805E-02, solve time:  2.86960E-03, relative residual:  8.93922E-18
### solver log, setup time:  1.92631E-02, solve time:  1.98690E-03, relative residual:  8.89416E-18
### solver log, setup time:  1.84269E-02, solve time:  2.75150E-03, relative residual:  9.27104E-18
### solver log, setup time:  1.84595E-02, solve time:  2.16260E-03, relative residual:  9.09581E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      64, total time:  6.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80053E-02, solve time:  2.31960E-03, relative residual:  8.79200E-18
### solver log, setup time:  2.10816E-02, solve time:  2.35590E-03, relative residual:  9.42969E-18
### solver log, setup time:  1.94904E-02, solve time:  2.48930E-03, relative residual:  9.06949E-18
### solver log, setup time:  1.78200E-02, solve time:  2.01180E-03, relative residual:  9.38982E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      65, total time:  6.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.49199E-02, solve time:  3.09650E-03, relative residual:  9.10597E-18
### solver log, setup time:  1.91896E-02, solve time:  2.47710E-03, relative residual:  8.81109E-18
### solver log, setup time:  1.79171E-02, solve time:  2.24420E-03, relative residual:  9.22896E-18
### solver log, setup time:  1.80653E-02, solve time:  1.97060E-03, relative residual:  9.50755E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      66, total time:  6.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86807E-02, solve time:  1.89950E-03, relative residual:  9.32363E-18
### solver log, setup time:  1.81819E-02, solve time:  2.11110E-03, relative residual:  9.42082E-18
### solver log, setup time:  1.90721E-02, solve time:  2.22240E-03, relative residual:  8.68757E-18
### solver log, setup time:  1.80798E-02, solve time:  2.68150E-03, relative residual:  9.17441E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      67, total time:  6.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.09574E-02, solve time:  2.60330E-03, relative residual:  9.51272E-18
### solver log, setup time:  1.92395E-02, solve time:  2.29630E-03, relative residual:  9.74912E-18
### solver log, setup time:  1.86788E-02, solve time:  2.59480E-03, relative residual:  9.52736E-18
### solver log, setup time:  1.90929E-02, solve time:  1.92840E-03, relative residual:  9.30638E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      68, total time:  6.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95502E-02, solve time:  2.96290E-03, relative residual:  9.01533E-18
### solver log, setup time:  1.83561E-02, solve time:  2.25410E-03, relative residual:  9.22232E-18
### solver log, setup time:  1.98215E-02, solve time:  2.32230E-03, relative residual:  9.10703E-18
### solver log, setup time:  1.84927E-02, solve time:  1.97080E-03, relative residual:  8.75095E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      69, total time:  6.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.93369E-02, solve time:  2.07230E-03, relative residual:  9.31106E-18
### solver log, setup time:  1.87428E-02, solve time:  2.31050E-03, relative residual:  9.20790E-18
### solver log, setup time:  1.81860E-02, solve time:  2.34880E-03, relative residual:  8.97842E-18
### solver log, setup time:  2.01895E-02, solve time:  2.07420E-03, relative residual:  8.99224E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      70, total time:  7.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.09925E-02, solve time:  2.41270E-03, relative residual:  9.57186E-18
### solver log, setup time:  1.89800E-02, solve time:  2.09770E-03, relative residual:  8.76114E-18
### solver log, setup time:  1.88968E-02, solve time:  2.21330E-03, relative residual:  8.81983E-18
### solver log, setup time:  1.85555E-02, solve time:  2.32740E-03, relative residual:  9.63030E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      71, total time:  7.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.94067E-02, solve time:  2.60840E-03, relative residual:  9.15358E-18
### solver log, setup time:  1.90497E-02, solve time:  5.38110E-03, relative residual:  9.32720E-18
### solver log, setup time:  2.01869E-02, solve time:  2.11150E-03, relative residual:  9.55008E-18
### solver log, setup time:  1.85005E-02, solve time:  2.69110E-03, relative residual:  9.19436E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      72, total time:  7.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.77863E-02, solve time:  2.69580E-03, relative residual:  9.42115E-18
### solver log, setup time:  1.82500E-02, solve time:  2.52740E-03, relative residual:  9.17863E-18
### solver log, setup time:  1.89519E-02, solve time:  2.60520E-03, relative residual:  9.33430E-18
### solver log, setup time:  2.07467E-02, solve time:  2.42440E-03, relative residual:  1.00370E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      73, total time:  7.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90484E-02, solve time:  2.49680E-03, relative residual:  9.34415E-18
### solver log, setup time:  2.01730E-02, solve time:  2.41480E-03, relative residual:  9.86101E-18
### solver log, setup time:  1.82405E-02, solve time:  2.29800E-03, relative residual:  9.35184E-18
### solver log, setup time:  2.04172E-02, solve time:  2.34060E-03, relative residual:  9.27885E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      74, total time:  7.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86213E-02, solve time:  2.19620E-03, relative residual:  9.35664E-18
### solver log, setup time:  2.11574E-02, solve time:  2.29950E-03, relative residual:  9.66266E-18
### solver log, setup time:  2.36688E-02, solve time:  2.36010E-03, relative residual:  1.00496E-17
### solver log, setup time:  1.80476E-02, solve time:  2.08380E-03, relative residual:  9.20970E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      75, total time:  7.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.10701E-02, solve time:  2.20810E-03, relative residual:  9.84042E-18
### solver log, setup time:  1.83355E-02, solve time:  2.07710E-03, relative residual:  9.51264E-18
### solver log, setup time:  2.85451E-02, solve time:  2.38890E-03, relative residual:  9.95725E-18
### solver log, setup time:  1.78132E-02, solve time:  2.58380E-03, relative residual:  1.00970E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      76, total time:  7.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.87595E-02, solve time:  2.50210E-03, relative residual:  9.88026E-18
### solver log, setup time:  2.03005E-02, solve time:  2.57220E-03, relative residual:  9.57992E-18
### solver log, setup time:  1.92602E-02, solve time:  2.52640E-03, relative residual:  9.24108E-18
### solver log, setup time:  1.78411E-02, solve time:  2.30720E-03, relative residual:  9.77189E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      77, total time:  7.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.06362E-02, solve time:  2.87890E-03, relative residual:  1.01331E-17
### solver log, setup time:  1.80773E-02, solve time:  2.70030E-03, relative residual:  9.58216E-18
### solver log, setup time:  1.94687E-02, solve time:  2.17050E-03, relative residual:  9.94096E-18
### solver log, setup time:  1.96543E-02, solve time:  2.21560E-03, relative residual:  9.90327E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      78, total time:  7.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.02860E-02, solve time:  2.32860E-03, relative residual:  9.63206E-18
### solver log, setup time:  1.80737E-02, solve time:  2.29410E-03, relative residual:  1.02278E-17
### solver log, setup time:  2.05805E-02, solve time:  2.16960E-03, relative residual:  1.00620E-17
### solver log, setup time:  2.05406E-02, solve time:  2.44660E-03, relative residual:  9.05154E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      79, total time:  7.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78569E-02, solve time:  2.50830E-03, relative residual:  1.16661E-17
### solver log, setup time:  1.97278E-02, solve time:  2.99220E-03, relative residual:  1.01699E-17
### solver log, setup time:  2.31857E-02, solve time:  2.20750E-03, relative residual:  9.41813E-18
### solver log, setup time:  1.82808E-02, solve time:  2.49960E-03, relative residual:  9.20408E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      80, total time:  8.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.98333E-02, solve time:  2.43050E-03, relative residual:  9.80580E-18
### solver log, setup time:  1.79892E-02, solve time:  2.63600E-03, relative residual:  1.04913E-17
### solver log, setup time:  1.81129E-02, solve time:  2.30000E-03, relative residual:  9.74287E-18
### solver log, setup time:  1.82484E-02, solve time:  2.19060E-03, relative residual:  9.59364E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      81, total time:  8.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.94817E-02, solve time:  2.16000E-03, relative residual:  9.77576E-18
### solver log, setup time:  1.86016E-02, solve time:  2.38910E-03, relative residual:  9.47316E-18
### solver log, setup time:  1.88328E-02, solve time:  2.07900E-03, relative residual:  9.59646E-18
### solver log, setup time:  1.98853E-02, solve time:  2.37940E-03, relative residual:  9.42272E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      82, total time:  8.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.81992E-02, solve time:  2.48430E-03, relative residual:  9.80074E-18
### solver log, setup time:  2.30274E-02, solve time:  2.00410E-03, relative residual:  1.01649E-17
### solver log, setup time:  1.98260E-02, solve time:  2.20390E-03, relative residual:  9.99726E-18
### solver log, setup time:  1.86736E-02, solve time:  2.40700E-03, relative residual:  1.02412E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      83, total time:  8.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80467E-02, solve time:  2.26150E-03, relative residual:  9.93769E-18
### solver log, setup time:  1.81935E-02, solve time:  2.02430E-03, relative residual:  1.02582E-17
### solver log, setup time:  1.89185E-02, solve time:  2.48420E-03, relative residual:  9.95525E-18
### solver log, setup time:  1.84357E-02, solve time:  2.19850E-03, relative residual:  1.02371E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      84, total time:  8.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80033E-02, solve time:  2.33490E-03, relative residual:  9.61538E-18
### solver log, setup time:  1.95101E-02, solve time:  2.20590E-03, relative residual:  1.01494E-17
### solver log, setup time:  2.09245E-02, solve time:  2.33820E-03, relative residual:  1.06229E-17
### solver log, setup time:  1.98038E-02, solve time:  2.27560E-03, relative residual:  1.07552E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      85, total time:  8.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95771E-02, solve time:  2.23240E-03, relative residual:  9.89744E-18
### solver log, setup time:  1.87971E-02, solve time:  2.25980E-03, relative residual:  9.90474E-18
### solver log, setup time:  2.34888E-02, solve time:  2.24470E-03, relative residual:  9.75958E-18
### solver log, setup time:  1.95055E-02, solve time:  3.10850E-03, relative residual:  1.00739E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      86, total time:  8.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.85731E-02, solve time:  2.29010E-03, relative residual:  1.01903E-17
### solver log, setup time:  2.08459E-02, solve time:  2.21860E-03, relative residual:  9.84585E-18
### solver log, setup time:  1.94548E-02, solve time:  2.52740E-03, relative residual:  1.03839E-17
### solver log, setup time:  1.83739E-02, solve time:  2.30830E-03, relative residual:  1.00873E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      87, total time:  8.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.76431E-02, solve time:  2.49420E-03, relative residual:  1.00174E-17
### solver log, setup time:  1.97188E-02, solve time:  2.40120E-03, relative residual:  9.63554E-18
### solver log, setup time:  1.89367E-02, solve time:  2.36930E-03, relative residual:  1.10122E-17
### solver log, setup time:  1.89924E-02, solve time:  2.20640E-03, relative residual:  1.10280E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      88, total time:  8.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92489E-02, solve time:  2.40950E-03, relative residual:  9.97025E-18
### solver log, setup time:  2.01116E-02, solve time:  2.09380E-03, relative residual:  9.78504E-18
### solver log, setup time:  1.98752E-02, solve time:  2.53670E-03, relative residual:  1.01411E-17
### solver log, setup time:  1.80474E-02, solve time:  2.71900E-03, relative residual:  1.07763E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      89, total time:  8.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83088E-02, solve time:  2.09220E-03, relative residual:  1.02946E-17
### solver log, setup time:  1.93668E-02, solve time:  2.12970E-03, relative residual:  1.05263E-17
### solver log, setup time:  2.00342E-02, solve time:  2.44530E-03, relative residual:  1.15205E-17
### solver log, setup time:  1.85564E-02, solve time:  2.38630E-03, relative residual:  1.08363E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      90, total time:  9.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79923E-02, solve time:  2.26000E-03, relative residual:  1.03586E-17
### solver log, setup time:  2.06068E-02, solve time:  2.03180E-03, relative residual:  9.69251E-18
### solver log, setup time:  2.31022E-02, solve time:  2.16570E-03, relative residual:  1.02874E-17
### solver log, setup time:  1.84150E-02, solve time:  2.75190E-03, relative residual:  9.93790E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      91, total time:  9.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83494E-02, solve time:  2.41190E-03, relative residual:  1.02696E-17
### solver log, setup time:  2.09857E-02, solve time:  2.53220E-03, relative residual:  1.03023E-17
### solver log, setup time:  1.94934E-02, solve time:  2.30350E-03, relative residual:  1.04030E-17
### solver log, setup time:  1.88338E-02, solve time:  2.17180E-03, relative residual:  1.01153E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      92, total time:  9.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.59729E-02, solve time:  2.08390E-03, relative residual:  1.07033E-17
### solver log, setup time:  1.78569E-02, solve time:  2.19380E-03, relative residual:  1.03561E-17
### solver log, setup time:  1.82053E-02, solve time:  2.66310E-03, relative residual:  1.02806E-17
### solver log, setup time:  1.87179E-02, solve time:  2.17510E-03, relative residual:  1.00264E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      93, total time:  9.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83854E-02, solve time:  2.48170E-03, relative residual:  1.02064E-17
### solver log, setup time:  1.96870E-02, solve time:  2.16550E-03, relative residual:  1.04953E-17
### solver log, setup time:  1.90602E-02, solve time:  2.78750E-03, relative residual:  1.04244E-17
### solver log, setup time:  1.91226E-02, solve time:  2.02200E-03, relative residual:  1.02261E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      94, total time:  9.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.91662E-02, solve time:  2.36030E-03, relative residual:  9.87003E-18
### solver log, setup time:  1.81507E-02, solve time:  2.26010E-03, relative residual:  1.02412E-17
### solver log, setup time:  2.01152E-02, solve time:  2.53900E-03, relative residual:  1.05446E-17
### solver log, setup time:  1.97060E-02, solve time:  1.97830E-03, relative residual:  1.09070E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      95, total time:  9.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.11550E-02, solve time:  2.08600E-03, relative residual:  1.02230E-17
### solver log, setup time:  2.49627E-02, solve time:  2.97790E-03, relative residual:  1.03315E-17
### solver log, setup time:  1.86419E-02, solve time:  2.28390E-03, relative residual:  1.04325E-17
### solver log, setup time:  2.21853E-02, solve time:  3.17580E-03, relative residual:  1.03280E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      96, total time:  9.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.47451E-02, solve time:  2.23040E-03, relative residual:  1.08830E-17
### solver log, setup time:  2.01462E-02, solve time:  2.21460E-03, relative residual:  1.06760E-17
### solver log, setup time:  2.10897E-02, solve time:  2.98510E-03, relative residual:  1.08223E-17
### solver log, setup time:  2.34844E-02, solve time:  2.20730E-03, relative residual:  1.06831E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      97, total time:  9.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.93648E-02, solve time:  2.08620E-03, relative residual:  1.10966E-17
### solver log, setup time:  3.06385E-02, solve time:  3.54930E-03, relative residual:  1.02708E-17
### solver log, setup time:  2.42645E-02, solve time:  1.91650E-03, relative residual:  1.06607E-17
### solver log, setup time:  2.40619E-02, solve time:  6.89320E-03, relative residual:  1.06792E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      98, total time:  9.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95823E-02, solve time:  2.14470E-03, relative residual:  1.07722E-17
### solver log, setup time:  3.14187E-02, solve time:  2.67830E-03, relative residual:  1.03469E-17
### solver log, setup time:  3.30498E-02, solve time:  2.63830E-03, relative residual:  1.04635E-17
### solver log, setup time:  1.93682E-02, solve time:  2.38570E-03, relative residual:  1.05389E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      99, total time:  9.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.99730E-02, solve time:  2.93240E-03, relative residual:  1.00315E-17
### solver log, setup time:  2.02337E-02, solve time:  3.37250E-03, relative residual:  1.07885E-17
### solver log, setup time:  2.00098E-02, solve time:  2.07100E-03, relative residual:  1.10485E-17
### solver log, setup time:  2.54244E-02, solve time:  2.30280E-03, relative residual:  1.06851E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :     100, total time:  1.00000E+00, delta t:  1.00000E-02
### solver log, setup time:  2.25666E-02, solve time:  2.69040E-03, relative residual:  1.08620E-17
### solver log, setup time:  1.90078E-02, solve time:  2.06700E-03, relative residual:  1.08258E-17
### solver log, setup time:  2.03707E-02, solve time:  2.12050E-03, relative residual:  1.14979E-17
### solver log, setup time:  1.79396E-02, solve time:  2.04580E-03, relative residual:  1.09582E-17
  !!! CONVERGENCE ACHIEVED 
 ====================================
    TOTAL TIME (sec) :    200.30
           pre (sec) :      0.11
         solve (sec) :    200.18
 ====================================



 :========================================:
 :**            END of FSTR             **:
 :========================================:
