 :========================================:
 :**   BEGIN FSTR Structural Analysis   **:
 :========================================:
         Total no. of processors:            1



  *    STAGE Initialization and input   **



  ***   STAGE Heat analysis    **
 =============================
   H E A T   T R A N S F E R  
 =============================
* Current step / Total step:        1/       1
* max iteration at each step:      100
* Transient anslysis
 ** Increment No. :       1, total time:  1.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  3.50258E-02, solve time:  2.62870E-03, relative residual:  5.50180E-18
### solver log, setup time:  2.12402E-02, solve time:  2.60890E-03, relative residual:  5.51922E-18
### solver log, setup time:  1.89260E-02, solve time:  2.49340E-03, relative residual:  5.45050E-18
### solver log, setup time:  1.79342E-02, solve time:  2.28850E-03, relative residual:  5.60048E-18
### solver log, setup time:  1.80997E-02, solve time:  2.26980E-03, relative residual:  5.57626E-18
### solver log, setup time:  2.19235E-02, solve time:  2.72630E-03, relative residual:  5.56161E-18
### solver log, setup time:  1.92697E-02, solve time:  2.32950E-03, relative residual:  5.43227E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       2, total time:  2.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.76961E-02, solve time:  2.43590E-03, relative residual:  5.45234E-18
### solver log, setup time:  2.49511E-02, solve time:  2.22160E-03, relative residual:  5.20510E-18
### solver log, setup time:  2.38508E-02, solve time:  2.37760E-03, relative residual:  5.36341E-18
### solver log, setup time:  1.80183E-02, solve time:  2.12680E-03, relative residual:  5.35150E-18
### solver log, setup time:  2.44831E-02, solve time:  2.66670E-03, relative residual:  5.41755E-18
### solver log, setup time:  1.73909E-02, solve time:  2.36100E-03, relative residual:  5.43791E-18
### solver log, setup time:  1.98088E-02, solve time:  2.35020E-03, relative residual:  5.43239E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       3, total time:  3.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.18652E-02, solve time:  2.19150E-03, relative residual:  5.34934E-18
### solver log, setup time:  2.36410E-02, solve time:  2.75740E-03, relative residual:  5.56447E-18
### solver log, setup time:  2.00796E-02, solve time:  2.20650E-03, relative residual:  5.51336E-18
### solver log, setup time:  2.02676E-02, solve time:  2.12570E-03, relative residual:  5.42422E-18
### solver log, setup time:  2.14658E-02, solve time:  1.92790E-03, relative residual:  5.32791E-18
### solver log, setup time:  2.31601E-02, solve time:  2.76470E-03, relative residual:  5.20250E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       4, total time:  4.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.92313E-02, solve time:  3.56400E-03, relative residual:  5.41151E-18
### solver log, setup time:  2.08875E-02, solve time:  2.45550E-03, relative residual:  5.27460E-18
### solver log, setup time:  2.03578E-02, solve time:  2.19160E-03, relative residual:  4.97616E-18
### solver log, setup time:  2.00960E-02, solve time:  2.30160E-03, relative residual:  5.32008E-18
### solver log, setup time:  1.93515E-02, solve time:  2.13010E-03, relative residual:  5.31665E-18
### solver log, setup time:  2.18273E-02, solve time:  2.11540E-03, relative residual:  5.31425E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       5, total time:  5.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.29332E-02, solve time:  3.00570E-03, relative residual:  5.22504E-18
### solver log, setup time:  2.62666E-02, solve time:  3.48970E-03, relative residual:  5.40792E-18
### solver log, setup time:  1.98994E-02, solve time:  2.91120E-03, relative residual:  5.14426E-18
### solver log, setup time:  1.97435E-02, solve time:  2.12570E-03, relative residual:  5.07358E-18
### solver log, setup time:  2.15009E-02, solve time:  2.41930E-03, relative residual:  4.84523E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       6, total time:  6.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.57693E-02, solve time:  2.51850E-03, relative residual:  5.10079E-18
### solver log, setup time:  2.06186E-02, solve time:  2.18880E-03, relative residual:  5.04627E-18
### solver log, setup time:  1.88452E-02, solve time:  2.52620E-03, relative residual:  5.22071E-18
### solver log, setup time:  2.15115E-02, solve time:  3.77670E-03, relative residual:  5.15175E-18
### solver log, setup time:  2.08698E-02, solve time:  2.48310E-03, relative residual:  5.09871E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       7, total time:  7.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.85691E-02, solve time:  2.53960E-03, relative residual:  5.14144E-18
### solver log, setup time:  2.08107E-02, solve time:  2.87360E-03, relative residual:  5.11112E-18
### solver log, setup time:  2.05343E-02, solve time:  2.34150E-03, relative residual:  5.22500E-18
### solver log, setup time:  1.82899E-02, solve time:  2.58810E-03, relative residual:  5.51046E-18
### solver log, setup time:  2.02076E-02, solve time:  3.36330E-03, relative residual:  5.24081E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       8, total time:  8.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.80877E-02, solve time:  2.93820E-03, relative residual:  4.92335E-18
### solver log, setup time:  1.73895E-02, solve time:  2.60170E-03, relative residual:  5.00767E-18
### solver log, setup time:  1.96557E-02, solve time:  2.31890E-03, relative residual:  4.96577E-18
### solver log, setup time:  2.55599E-02, solve time:  2.52650E-03, relative residual:  4.96700E-18
### solver log, setup time:  2.20876E-02, solve time:  2.63870E-03, relative residual:  5.07151E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       9, total time:  9.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.77962E-02, solve time:  2.18300E-03, relative residual:  5.07914E-18
### solver log, setup time:  2.13077E-02, solve time:  3.27100E-03, relative residual:  5.03398E-18
### solver log, setup time:  2.59880E-02, solve time:  2.24510E-03, relative residual:  4.92079E-18
### solver log, setup time:  2.10654E-02, solve time:  2.93340E-03, relative residual:  5.01267E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      10, total time:  1.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.10220E-02, solve time:  2.51200E-03, relative residual:  5.07771E-18
### solver log, setup time:  2.09901E-02, solve time:  2.64040E-03, relative residual:  4.78084E-18
### solver log, setup time:  2.30942E-02, solve time:  2.63740E-03, relative residual:  4.83035E-18
### solver log, setup time:  1.95297E-02, solve time:  2.22050E-03, relative residual:  4.86281E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      11, total time:  1.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.98642E-02, solve time:  2.65690E-03, relative residual:  4.89048E-18
### solver log, setup time:  2.08971E-02, solve time:  2.50310E-03, relative residual:  4.94479E-18
### solver log, setup time:  2.08619E-02, solve time:  2.19570E-03, relative residual:  4.72516E-18
### solver log, setup time:  2.38475E-02, solve time:  2.34680E-03, relative residual:  4.68427E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      12, total time:  1.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86233E-02, solve time:  2.53500E-03, relative residual:  4.89392E-18
### solver log, setup time:  1.87582E-02, solve time:  2.18090E-03, relative residual:  4.70988E-18
### solver log, setup time:  1.96952E-02, solve time:  2.51550E-03, relative residual:  4.83825E-18
### solver log, setup time:  3.27286E-02, solve time:  2.81490E-03, relative residual:  4.70922E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      13, total time:  1.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.98865E-02, solve time:  4.39370E-03, relative residual:  4.63386E-18
### solver log, setup time:  2.06696E-02, solve time:  2.21280E-03, relative residual:  4.88517E-18
### solver log, setup time:  2.37966E-02, solve time:  2.69740E-03, relative residual:  4.76968E-18
### solver log, setup time:  2.66112E-02, solve time:  3.00320E-03, relative residual:  4.78097E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      14, total time:  1.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.27312E-02, solve time:  2.95380E-03, relative residual:  4.67873E-18
### solver log, setup time:  1.81639E-02, solve time:  2.35670E-03, relative residual:  4.93351E-18
### solver log, setup time:  2.27152E-02, solve time:  3.24960E-03, relative residual:  4.80927E-18
### solver log, setup time:  2.15991E-02, solve time:  2.31880E-03, relative residual:  4.58761E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      15, total time:  1.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.07725E-02, solve time:  3.11600E-03, relative residual:  4.76143E-18
### solver log, setup time:  2.46992E-02, solve time:  2.61590E-03, relative residual:  4.40974E-18
### solver log, setup time:  2.08944E-02, solve time:  2.39810E-03, relative residual:  4.58763E-18
### solver log, setup time:  2.36079E-02, solve time:  3.62850E-03, relative residual:  4.85381E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      16, total time:  1.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.12093E-02, solve time:  2.28810E-03, relative residual:  4.60261E-18
### solver log, setup time:  2.00207E-02, solve time:  2.41770E-03, relative residual:  4.55259E-18
### solver log, setup time:  2.36388E-02, solve time:  2.06370E-03, relative residual:  4.51872E-18
### solver log, setup time:  1.91663E-02, solve time:  2.53330E-03, relative residual:  4.53004E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      17, total time:  1.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82495E-02, solve time:  2.61860E-03, relative residual:  4.55638E-18
### solver log, setup time:  2.14683E-02, solve time:  3.11930E-03, relative residual:  4.66280E-18
### solver log, setup time:  1.89926E-02, solve time:  2.32610E-03, relative residual:  4.72441E-18
### solver log, setup time:  2.23725E-02, solve time:  2.92120E-03, relative residual:  4.43554E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      18, total time:  1.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.28020E-02, solve time:  2.24120E-03, relative residual:  4.41858E-18
### solver log, setup time:  1.95515E-02, solve time:  3.15380E-03, relative residual:  4.50474E-18
### solver log, setup time:  1.92958E-02, solve time:  3.24860E-03, relative residual:  4.51378E-18
### solver log, setup time:  2.16008E-02, solve time:  2.92910E-03, relative residual:  4.32839E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      19, total time:  1.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.22845E-02, solve time:  3.24640E-03, relative residual:  4.34329E-18
### solver log, setup time:  2.38871E-02, solve time:  2.90990E-03, relative residual:  4.48052E-18
### solver log, setup time:  3.00591E-02, solve time:  3.11110E-03, relative residual:  4.37310E-18
### solver log, setup time:  2.34168E-02, solve time:  3.34140E-03, relative residual:  4.53032E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      20, total time:  2.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.50450E-02, solve time:  2.37920E-03, relative residual:  4.64310E-18
### solver log, setup time:  2.58726E-02, solve time:  3.31980E-03, relative residual:  4.71458E-18
### solver log, setup time:  1.96543E-02, solve time:  2.14620E-03, relative residual:  4.39777E-18
### solver log, setup time:  1.84344E-02, solve time:  2.32710E-03, relative residual:  4.44334E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      21, total time:  2.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90602E-02, solve time:  3.27040E-03, relative residual:  4.65683E-18
### solver log, setup time:  1.87368E-02, solve time:  2.13070E-03, relative residual:  4.57125E-18
### solver log, setup time:  2.20456E-02, solve time:  3.08310E-03, relative residual:  4.52455E-18
### solver log, setup time:  2.28500E-02, solve time:  2.49410E-03, relative residual:  4.56330E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      22, total time:  2.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.21899E-02, solve time:  3.24550E-03, relative residual:  4.34238E-18
### solver log, setup time:  2.30315E-02, solve time:  2.13090E-03, relative residual:  4.27781E-18
### solver log, setup time:  1.73831E-02, solve time:  2.53910E-03, relative residual:  4.49925E-18
### solver log, setup time:  2.56697E-02, solve time:  2.75460E-03, relative residual:  4.27257E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      23, total time:  2.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95711E-02, solve time:  2.33230E-03, relative residual:  4.32576E-18
### solver log, setup time:  2.09866E-02, solve time:  2.05360E-03, relative residual:  4.24390E-18
### solver log, setup time:  2.11998E-02, solve time:  2.26610E-03, relative residual:  4.28612E-18
### solver log, setup time:  1.82414E-02, solve time:  3.14480E-03, relative residual:  4.42871E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      24, total time:  2.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.26134E-02, solve time:  2.07020E-03, relative residual:  4.38442E-18
### solver log, setup time:  1.94105E-02, solve time:  2.26460E-03, relative residual:  4.33699E-18
### solver log, setup time:  2.21199E-02, solve time:  2.36630E-03, relative residual:  4.46627E-18
### solver log, setup time:  1.98823E-02, solve time:  2.30470E-03, relative residual:  4.37494E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      25, total time:  2.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.84930E-02, solve time:  3.10800E-03, relative residual:  4.30634E-18
### solver log, setup time:  2.08800E-02, solve time:  2.81900E-03, relative residual:  4.20733E-18
### solver log, setup time:  1.92419E-02, solve time:  2.21820E-03, relative residual:  4.36180E-18
### solver log, setup time:  2.38607E-02, solve time:  2.14130E-03, relative residual:  4.19126E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      26, total time:  2.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.96170E-02, solve time:  2.41640E-03, relative residual:  4.16050E-18
### solver log, setup time:  2.19686E-02, solve time:  2.17960E-03, relative residual:  4.22589E-18
### solver log, setup time:  1.95804E-02, solve time:  3.36140E-03, relative residual:  4.29594E-18
### solver log, setup time:  2.30297E-02, solve time:  2.14620E-03, relative residual:  4.21783E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      27, total time:  2.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82379E-02, solve time:  2.47340E-03, relative residual:  4.38592E-18
### solver log, setup time:  2.63652E-02, solve time:  3.60240E-03, relative residual:  4.11000E-18
### solver log, setup time:  1.76873E-02, solve time:  2.16420E-03, relative residual:  4.35087E-18
### solver log, setup time:  2.01302E-02, solve time:  2.16750E-03, relative residual:  4.27362E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      28, total time:  2.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86483E-02, solve time:  2.21320E-03, relative residual:  4.33799E-18
### solver log, setup time:  2.22390E-02, solve time:  2.12210E-03, relative residual:  4.28434E-18
### solver log, setup time:  1.75627E-02, solve time:  2.22670E-03, relative residual:  4.39645E-18
### solver log, setup time:  2.12591E-02, solve time:  2.04180E-03, relative residual:  4.22617E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      29, total time:  2.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.98267E-02, solve time:  2.39290E-03, relative residual:  4.28386E-18
### solver log, setup time:  1.94069E-02, solve time:  3.63440E-03, relative residual:  4.07046E-18
### solver log, setup time:  2.22017E-02, solve time:  2.13270E-03, relative residual:  4.36120E-18
### solver log, setup time:  1.81618E-02, solve time:  2.14960E-03, relative residual:  4.30650E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      30, total time:  3.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80368E-02, solve time:  2.33100E-03, relative residual:  4.31627E-18
### solver log, setup time:  1.80027E-02, solve time:  2.26480E-03, relative residual:  4.08940E-18
### solver log, setup time:  1.77740E-02, solve time:  2.27600E-03, relative residual:  4.04045E-18
### solver log, setup time:  1.82685E-02, solve time:  2.23690E-03, relative residual:  4.03976E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      31, total time:  3.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.81406E-02, solve time:  2.06360E-03, relative residual:  4.20664E-18
### solver log, setup time:  2.01126E-02, solve time:  2.42310E-03, relative residual:  4.18462E-18
### solver log, setup time:  2.04803E-02, solve time:  2.27240E-03, relative residual:  4.09977E-18
### solver log, setup time:  2.32284E-02, solve time:  2.68220E-03, relative residual:  4.13630E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      32, total time:  3.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.12100E-02, solve time:  3.52750E-03, relative residual:  4.26369E-18
### solver log, setup time:  1.98358E-02, solve time:  2.26390E-03, relative residual:  4.44029E-18
### solver log, setup time:  2.27967E-02, solve time:  3.17210E-03, relative residual:  4.05792E-18
### solver log, setup time:  2.59936E-02, solve time:  2.15150E-03, relative residual:  4.43785E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      33, total time:  3.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.44688E-02, solve time:  3.10600E-03, relative residual:  3.99138E-18
### solver log, setup time:  2.14463E-02, solve time:  2.14110E-03, relative residual:  4.23461E-18
### solver log, setup time:  2.33639E-02, solve time:  2.57360E-03, relative residual:  4.11018E-18
### solver log, setup time:  1.77496E-02, solve time:  2.18040E-03, relative residual:  4.05094E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      34, total time:  3.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.76589E-02, solve time:  2.36430E-03, relative residual:  4.16301E-18
### solver log, setup time:  1.91311E-02, solve time:  2.29160E-03, relative residual:  4.45329E-18
### solver log, setup time:  1.92490E-02, solve time:  2.88740E-03, relative residual:  4.15403E-18
### solver log, setup time:  1.76966E-02, solve time:  2.71580E-03, relative residual:  4.23698E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      35, total time:  3.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.75239E-02, solve time:  2.23100E-03, relative residual:  4.04317E-18
### solver log, setup time:  1.85477E-02, solve time:  2.35110E-03, relative residual:  4.22260E-18
### solver log, setup time:  1.78413E-02, solve time:  2.49560E-03, relative residual:  4.16734E-18
### solver log, setup time:  1.94199E-02, solve time:  2.13350E-03, relative residual:  4.19447E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      36, total time:  3.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.36426E-02, solve time:  2.79260E-03, relative residual:  4.06836E-18
### solver log, setup time:  2.10191E-02, solve time:  2.22110E-03, relative residual:  4.33533E-18
### solver log, setup time:  1.93276E-02, solve time:  2.25270E-03, relative residual:  3.91908E-18
### solver log, setup time:  1.83431E-02, solve time:  2.20030E-03, relative residual:  3.99109E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      37, total time:  3.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79909E-02, solve time:  2.41870E-03, relative residual:  4.09535E-18
### solver log, setup time:  1.89621E-02, solve time:  7.34070E-03, relative residual:  4.12269E-18
### solver log, setup time:  1.88616E-02, solve time:  3.38150E-03, relative residual:  4.17370E-18
### solver log, setup time:  1.96628E-02, solve time:  1.93710E-03, relative residual:  4.12423E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      38, total time:  3.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.77994E-02, solve time:  2.30630E-03, relative residual:  4.41279E-18
### solver log, setup time:  2.17953E-02, solve time:  3.95870E-03, relative residual:  4.05597E-18
### solver log, setup time:  2.23942E-02, solve time:  2.35970E-03, relative residual:  4.04301E-18
### solver log, setup time:  2.28310E-02, solve time:  2.47500E-03, relative residual:  4.15888E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      39, total time:  3.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.03527E-02, solve time:  3.00720E-03, relative residual:  3.87527E-18
### solver log, setup time:  2.13605E-02, solve time:  2.48160E-03, relative residual:  4.06354E-18
### solver log, setup time:  2.33152E-02, solve time:  2.28030E-03, relative residual:  4.18416E-18
### solver log, setup time:  2.20477E-02, solve time:  2.63800E-03, relative residual:  3.90983E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      40, total time:  4.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.21358E-02, solve time:  2.34230E-03, relative residual:  4.14852E-18
### solver log, setup time:  2.07374E-02, solve time:  3.95800E-03, relative residual:  4.07208E-18
### solver log, setup time:  2.00065E-02, solve time:  2.34370E-03, relative residual:  4.17940E-18
### solver log, setup time:  1.76332E-02, solve time:  2.35850E-03, relative residual:  4.34606E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      41, total time:  4.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.11634E-02, solve time:  3.39440E-03, relative residual:  3.94868E-18
### solver log, setup time:  2.45051E-02, solve time:  3.15640E-03, relative residual:  4.20477E-18
### solver log, setup time:  1.94681E-02, solve time:  2.12660E-03, relative residual:  4.31971E-18
### solver log, setup time:  1.92176E-02, solve time:  2.16130E-03, relative residual:  4.19874E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      42, total time:  4.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80344E-02, solve time:  2.59110E-03, relative residual:  3.79430E-18
### solver log, setup time:  1.99626E-02, solve time:  2.23040E-03, relative residual:  4.13598E-18
### solver log, setup time:  1.80185E-02, solve time:  2.19410E-03, relative residual:  4.16867E-18
### solver log, setup time:  1.78696E-02, solve time:  2.40890E-03, relative residual:  4.15926E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      43, total time:  4.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.97474E-02, solve time:  3.71890E-03, relative residual:  4.12277E-18
### solver log, setup time:  2.09169E-02, solve time:  2.17910E-03, relative residual:  4.15697E-18
### solver log, setup time:  1.93745E-02, solve time:  2.29060E-03, relative residual:  4.05023E-18
### solver log, setup time:  2.05374E-02, solve time:  2.16950E-03, relative residual:  4.06288E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      44, total time:  4.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.12933E-02, solve time:  2.31480E-03, relative residual:  3.99980E-18
### solver log, setup time:  2.09359E-02, solve time:  2.42490E-03, relative residual:  4.07255E-18
### solver log, setup time:  2.40913E-02, solve time:  2.40490E-03, relative residual:  4.09881E-18
### solver log, setup time:  1.82269E-02, solve time:  2.37600E-03, relative residual:  3.99765E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      45, total time:  4.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78907E-02, solve time:  2.20960E-03, relative residual:  4.02698E-18
### solver log, setup time:  1.74281E-02, solve time:  2.33310E-03, relative residual:  3.95716E-18
### solver log, setup time:  1.86586E-02, solve time:  2.30420E-03, relative residual:  3.93280E-18
### solver log, setup time:  1.90853E-02, solve time:  2.66190E-03, relative residual:  4.12267E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      46, total time:  4.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.77414E-02, solve time:  2.44290E-03, relative residual:  4.11786E-18
### solver log, setup time:  1.93965E-02, solve time:  2.17520E-03, relative residual:  4.03307E-18
### solver log, setup time:  1.90581E-02, solve time:  2.58470E-03, relative residual:  4.00995E-18
### solver log, setup time:  1.93489E-02, solve time:  2.61980E-03, relative residual:  3.83702E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      47, total time:  4.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82487E-02, solve time:  2.65970E-03, relative residual:  4.35525E-18
### solver log, setup time:  1.92878E-02, solve time:  2.26420E-03, relative residual:  4.08035E-18
### solver log, setup time:  1.81605E-02, solve time:  2.87340E-03, relative residual:  3.98983E-18
### solver log, setup time:  1.83742E-02, solve time:  3.09070E-03, relative residual:  3.70885E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      48, total time:  4.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.05932E-02, solve time:  2.79250E-03, relative residual:  4.11257E-18
### solver log, setup time:  1.76919E-02, solve time:  2.78570E-03, relative residual:  4.03568E-18
### solver log, setup time:  1.91135E-02, solve time:  2.50690E-03, relative residual:  3.79939E-18
### solver log, setup time:  1.73946E-02, solve time:  2.66980E-03, relative residual:  3.96784E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      49, total time:  4.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.84662E-02, solve time:  2.55650E-03, relative residual:  3.77072E-18
### solver log, setup time:  1.82009E-02, solve time:  2.37430E-03, relative residual:  4.10948E-18
### solver log, setup time:  1.86236E-02, solve time:  2.64270E-03, relative residual:  4.05970E-18
### solver log, setup time:  2.09399E-02, solve time:  2.90490E-03, relative residual:  4.06330E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      50, total time:  5.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.97576E-02, solve time:  2.66760E-03, relative residual:  3.90870E-18
### solver log, setup time:  1.79395E-02, solve time:  2.50390E-03, relative residual:  3.75721E-18
### solver log, setup time:  2.08376E-02, solve time:  2.75230E-03, relative residual:  3.96103E-18
### solver log, setup time:  1.84417E-02, solve time:  2.62680E-03, relative residual:  4.21468E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      51, total time:  5.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.24417E-02, solve time:  1.89840E-03, relative residual:  3.81238E-18
### solver log, setup time:  2.10862E-02, solve time:  2.52010E-03, relative residual:  3.90449E-18
### solver log, setup time:  2.14761E-02, solve time:  2.22730E-03, relative residual:  4.01779E-18
### solver log, setup time:  1.89146E-02, solve time:  2.32240E-03, relative residual:  3.85726E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      52, total time:  5.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82681E-02, solve time:  2.29680E-03, relative residual:  3.85831E-18
### solver log, setup time:  2.60820E-02, solve time:  2.34370E-03, relative residual:  3.87860E-18
### solver log, setup time:  2.03411E-02, solve time:  2.48270E-03, relative residual:  3.93722E-18
### solver log, setup time:  1.95033E-02, solve time:  2.04030E-03, relative residual:  4.25687E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      53, total time:  5.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.40780E-02, solve time:  3.03930E-03, relative residual:  3.76480E-18
### solver log, setup time:  2.15909E-02, solve time:  2.38010E-03, relative residual:  3.95156E-18
### solver log, setup time:  1.80642E-02, solve time:  2.34110E-03, relative residual:  4.10514E-18
### solver log, setup time:  2.00390E-02, solve time:  2.67450E-03, relative residual:  3.82899E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      54, total time:  5.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.89404E-02, solve time:  2.32290E-03, relative residual:  3.87017E-18
### solver log, setup time:  1.80583E-02, solve time:  2.50990E-03, relative residual:  3.83708E-18
### solver log, setup time:  1.84657E-02, solve time:  2.64430E-03, relative residual:  4.10334E-18
### solver log, setup time:  1.85435E-02, solve time:  2.51750E-03, relative residual:  3.82609E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      55, total time:  5.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90802E-02, solve time:  2.27460E-03, relative residual:  3.95494E-18
### solver log, setup time:  2.61897E-02, solve time:  2.35330E-03, relative residual:  3.71370E-18
### solver log, setup time:  1.93213E-02, solve time:  2.12720E-03, relative residual:  3.90009E-18
### solver log, setup time:  1.83341E-02, solve time:  2.34490E-03, relative residual:  4.12181E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      56, total time:  5.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.99407E-02, solve time:  2.00810E-03, relative residual:  4.15838E-18
### solver log, setup time:  1.82740E-02, solve time:  2.34080E-03, relative residual:  3.87122E-18
### solver log, setup time:  2.50058E-02, solve time:  2.64680E-03, relative residual:  4.00983E-18
### solver log, setup time:  1.79845E-02, solve time:  2.10640E-03, relative residual:  3.85260E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      57, total time:  5.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.09432E-02, solve time:  3.78010E-03, relative residual:  3.74432E-18
### solver log, setup time:  1.95174E-02, solve time:  2.42070E-03, relative residual:  3.94379E-18
### solver log, setup time:  2.22560E-02, solve time:  2.05490E-03, relative residual:  3.96641E-18
### solver log, setup time:  1.97302E-02, solve time:  2.05460E-03, relative residual:  3.72268E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      58, total time:  5.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.96171E-02, solve time:  2.42530E-03, relative residual:  3.80225E-18
### solver log, setup time:  2.41326E-02, solve time:  2.26800E-03, relative residual:  3.70718E-18
### solver log, setup time:  1.96180E-02, solve time:  2.15280E-03, relative residual:  3.76530E-18
### solver log, setup time:  1.94187E-02, solve time:  2.56430E-03, relative residual:  3.66316E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      59, total time:  5.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.03461E-02, solve time:  2.32550E-03, relative residual:  3.99156E-18
### solver log, setup time:  1.79241E-02, solve time:  2.20380E-03, relative residual:  3.80953E-18
### solver log, setup time:  2.01610E-02, solve time:  2.50490E-03, relative residual:  3.81435E-18
### solver log, setup time:  1.96445E-02, solve time:  2.43000E-03, relative residual:  3.95083E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      60, total time:  6.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.75506E-02, solve time:  2.38310E-03, relative residual:  3.68087E-18
### solver log, setup time:  1.90705E-02, solve time:  2.12460E-03, relative residual:  4.12374E-18
### solver log, setup time:  1.98614E-02, solve time:  2.44480E-03, relative residual:  4.10134E-18
### solver log, setup time:  1.83590E-02, solve time:  2.40510E-03, relative residual:  4.10306E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      61, total time:  6.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.91279E-02, solve time:  2.69440E-03, relative residual:  3.85731E-18
### solver log, setup time:  2.08557E-02, solve time:  2.25290E-03, relative residual:  3.77083E-18
### solver log, setup time:  1.89284E-02, solve time:  2.46260E-03, relative residual:  3.82013E-18
### solver log, setup time:  1.93316E-02, solve time:  2.15650E-03, relative residual:  3.85771E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      62, total time:  6.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.76408E-02, solve time:  2.21280E-03, relative residual:  3.86962E-18
### solver log, setup time:  2.10956E-02, solve time:  2.13560E-03, relative residual:  3.74936E-18
### solver log, setup time:  1.86374E-02, solve time:  2.55950E-03, relative residual:  3.93556E-18
### solver log, setup time:  2.35137E-02, solve time:  2.60360E-03, relative residual:  3.99333E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      63, total time:  6.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.33488E-02, solve time:  4.44650E-03, relative residual:  3.94441E-18
### solver log, setup time:  2.24148E-02, solve time:  2.03310E-03, relative residual:  3.97320E-18
### solver log, setup time:  1.81907E-02, solve time:  1.97310E-03, relative residual:  3.97583E-18
### solver log, setup time:  1.98222E-02, solve time:  2.14640E-03, relative residual:  4.18211E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      64, total time:  6.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.22010E-02, solve time:  2.68740E-03, relative residual:  3.73065E-18
### solver log, setup time:  2.04775E-02, solve time:  2.31370E-03, relative residual:  3.91857E-18
### solver log, setup time:  1.86941E-02, solve time:  2.73860E-03, relative residual:  4.10881E-18
### solver log, setup time:  1.99358E-02, solve time:  2.44870E-03, relative residual:  3.81089E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      65, total time:  6.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82044E-02, solve time:  2.75560E-03, relative residual:  3.71037E-18
### solver log, setup time:  2.20778E-02, solve time:  3.39320E-03, relative residual:  3.90726E-18
### solver log, setup time:  1.63378E-02, solve time:  2.05470E-03, relative residual:  3.91774E-18
### solver log, setup time:  3.03203E-02, solve time:  2.18410E-03, relative residual:  3.67428E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      66, total time:  6.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.98074E-02, solve time:  2.15610E-03, relative residual:  3.62722E-18
### solver log, setup time:  2.25019E-02, solve time:  2.58040E-03, relative residual:  3.66981E-18
### solver log, setup time:  2.18890E-02, solve time:  2.18370E-03, relative residual:  3.92631E-18
### solver log, setup time:  2.49901E-02, solve time:  2.31700E-03, relative residual:  3.83709E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      67, total time:  6.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.18207E-02, solve time:  2.96230E-03, relative residual:  3.84935E-18
### solver log, setup time:  2.26227E-02, solve time:  2.09390E-03, relative residual:  3.80881E-18
### solver log, setup time:  1.80605E-02, solve time:  2.17710E-03, relative residual:  3.94140E-18
### solver log, setup time:  1.84889E-02, solve time:  2.80420E-03, relative residual:  3.77709E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      68, total time:  6.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.81832E-02, solve time:  2.58030E-03, relative residual:  3.74984E-18
### solver log, setup time:  1.81038E-02, solve time:  2.36420E-03, relative residual:  3.84199E-18
### solver log, setup time:  1.80986E-02, solve time:  2.49920E-03, relative residual:  4.08790E-18
### solver log, setup time:  1.85489E-02, solve time:  2.40500E-03, relative residual:  3.88154E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      69, total time:  6.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78244E-02, solve time:  2.21160E-03, relative residual:  3.80440E-18
### solver log, setup time:  2.22089E-02, solve time:  2.41220E-03, relative residual:  3.88370E-18
### solver log, setup time:  1.82652E-02, solve time:  2.23820E-03, relative residual:  3.91719E-18
### solver log, setup time:  2.06929E-02, solve time:  2.19430E-03, relative residual:  4.23711E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      70, total time:  7.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.32383E-02, solve time:  3.41540E-03, relative residual:  3.97546E-18
### solver log, setup time:  1.98024E-02, solve time:  2.24680E-03, relative residual:  3.89947E-18
### solver log, setup time:  2.25015E-02, solve time:  2.17150E-03, relative residual:  3.58440E-18
### solver log, setup time:  2.33320E-02, solve time:  2.75140E-03, relative residual:  3.75735E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      71, total time:  7.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.46157E-02, solve time:  2.60680E-03, relative residual:  3.61567E-18
### solver log, setup time:  2.85654E-02, solve time:  3.52630E-03, relative residual:  3.76738E-18
### solver log, setup time:  2.29617E-02, solve time:  2.46740E-03, relative residual:  3.93062E-18
### solver log, setup time:  2.25891E-02, solve time:  2.13230E-03, relative residual:  3.96052E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      72, total time:  7.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.47935E-02, solve time:  2.13430E-03, relative residual:  3.94711E-18
### solver log, setup time:  2.14774E-02, solve time:  2.41500E-03, relative residual:  3.73516E-18
### solver log, setup time:  2.02827E-02, solve time:  3.61270E-03, relative residual:  3.88543E-18
### solver log, setup time:  2.09815E-02, solve time:  2.39930E-03, relative residual:  4.00449E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      73, total time:  7.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.06430E-02, solve time:  2.57020E-03, relative residual:  4.06663E-18
### solver log, setup time:  2.61417E-02, solve time:  3.05270E-03, relative residual:  3.82673E-18
### solver log, setup time:  2.14886E-02, solve time:  3.76140E-03, relative residual:  3.89253E-18
### solver log, setup time:  2.17027E-02, solve time:  1.93120E-03, relative residual:  3.99983E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      74, total time:  7.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.31440E-02, solve time:  2.03900E-03, relative residual:  3.98143E-18
### solver log, setup time:  2.86053E-02, solve time:  2.44090E-03, relative residual:  3.79321E-18
### solver log, setup time:  2.35792E-02, solve time:  3.31680E-03, relative residual:  3.75646E-18
### solver log, setup time:  2.03667E-02, solve time:  2.26260E-03, relative residual:  3.90158E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      75, total time:  7.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.77939E-02, solve time:  2.37510E-03, relative residual:  3.79515E-18
### solver log, setup time:  1.75986E-02, solve time:  2.46790E-03, relative residual:  3.74840E-18
### solver log, setup time:  2.12203E-02, solve time:  3.79610E-03, relative residual:  3.75536E-18
### solver log, setup time:  2.07404E-02, solve time:  3.29110E-03, relative residual:  3.95289E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      76, total time:  7.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.14122E-02, solve time:  3.08740E-03, relative residual:  3.98667E-18
### solver log, setup time:  2.05644E-02, solve time:  2.72050E-03, relative residual:  3.68620E-18
### solver log, setup time:  2.03085E-02, solve time:  2.56050E-03, relative residual:  3.89842E-18
### solver log, setup time:  1.98090E-02, solve time:  3.41160E-03, relative residual:  3.77513E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      77, total time:  7.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.84754E-02, solve time:  2.34630E-03, relative residual:  3.92274E-18
### solver log, setup time:  2.23563E-02, solve time:  2.43530E-03, relative residual:  3.89052E-18
### solver log, setup time:  1.88101E-02, solve time:  2.25130E-03, relative residual:  3.88994E-18
### solver log, setup time:  1.78784E-02, solve time:  2.24980E-03, relative residual:  3.76719E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      78, total time:  7.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.00310E-02, solve time:  2.58240E-03, relative residual:  3.78940E-18
### solver log, setup time:  2.20313E-02, solve time:  2.40340E-03, relative residual:  3.75413E-18
### solver log, setup time:  1.77442E-02, solve time:  2.54680E-03, relative residual:  3.92052E-18
### solver log, setup time:  2.10044E-02, solve time:  2.42010E-03, relative residual:  4.00162E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      79, total time:  7.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.15948E-02, solve time:  2.42500E-03, relative residual:  3.89013E-18
### solver log, setup time:  1.96706E-02, solve time:  2.70920E-03, relative residual:  3.77503E-18
### solver log, setup time:  1.93124E-02, solve time:  2.29880E-03, relative residual:  3.95997E-18
### solver log, setup time:  1.84369E-02, solve time:  2.75810E-03, relative residual:  3.88175E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      80, total time:  8.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90032E-02, solve time:  2.55870E-03, relative residual:  3.76699E-18
### solver log, setup time:  1.88596E-02, solve time:  2.46440E-03, relative residual:  3.93098E-18
### solver log, setup time:  1.96164E-02, solve time:  2.16970E-03, relative residual:  3.94946E-18
### solver log, setup time:  2.21203E-02, solve time:  2.62240E-03, relative residual:  3.71988E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      81, total time:  8.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  3.06721E-02, solve time:  2.94190E-03, relative residual:  3.74231E-18
### solver log, setup time:  2.12313E-02, solve time:  2.15310E-03, relative residual:  4.01291E-18
### solver log, setup time:  2.02111E-02, solve time:  3.07970E-03, relative residual:  3.77617E-18
### solver log, setup time:  2.17144E-02, solve time:  2.24910E-03, relative residual:  3.55684E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      82, total time:  8.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86305E-02, solve time:  2.53630E-03, relative residual:  3.96487E-18
### solver log, setup time:  1.89074E-02, solve time:  2.33690E-03, relative residual:  3.66595E-18
### solver log, setup time:  2.04040E-02, solve time:  2.66040E-03, relative residual:  3.78118E-18
### solver log, setup time:  1.99018E-02, solve time:  2.22530E-03, relative residual:  3.80354E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      83, total time:  8.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.75978E-02, solve time:  2.27610E-03, relative residual:  3.84784E-18
### solver log, setup time:  4.56755E-02, solve time:  2.45140E-03, relative residual:  3.80655E-18
### solver log, setup time:  6.43326E-02, solve time:  3.44570E-03, relative residual:  3.54706E-18
### solver log, setup time:  2.34087E-02, solve time:  3.79950E-03, relative residual:  3.68035E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      84, total time:  8.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.88389E-02, solve time:  2.34860E-03, relative residual:  3.78157E-18
### solver log, setup time:  1.84043E-02, solve time:  2.25470E-03, relative residual:  3.88118E-18
### solver log, setup time:  1.99597E-02, solve time:  2.21890E-03, relative residual:  3.87163E-18
### solver log, setup time:  2.09789E-02, solve time:  2.30160E-03, relative residual:  3.95851E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      85, total time:  8.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.14392E-02, solve time:  2.61570E-03, relative residual:  3.57811E-18
### solver log, setup time:  1.90876E-02, solve time:  2.30090E-03, relative residual:  3.63155E-18
### solver log, setup time:  2.13427E-02, solve time:  3.24010E-03, relative residual:  3.92159E-18
### solver log, setup time:  1.87914E-02, solve time:  2.83840E-03, relative residual:  4.00987E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      86, total time:  8.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.43246E-02, solve time:  2.79750E-03, relative residual:  3.64605E-18
### solver log, setup time:  2.41818E-02, solve time:  3.32190E-03, relative residual:  3.95044E-18
### solver log, setup time:  1.96074E-02, solve time:  2.30900E-03, relative residual:  3.62756E-18
### solver log, setup time:  2.23638E-02, solve time:  2.20150E-03, relative residual:  3.70741E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      87, total time:  8.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.87980E-02, solve time:  2.52030E-03, relative residual:  3.90461E-18
### solver log, setup time:  1.91425E-02, solve time:  2.21930E-03, relative residual:  3.63321E-18
### solver log, setup time:  1.83280E-02, solve time:  2.48720E-03, relative residual:  4.06386E-18
### solver log, setup time:  1.98762E-02, solve time:  2.41420E-03, relative residual:  3.87854E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      88, total time:  8.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.76821E-02, solve time:  2.34320E-03, relative residual:  3.81012E-18
### solver log, setup time:  1.96396E-02, solve time:  2.07630E-03, relative residual:  4.33485E-18
### solver log, setup time:  1.78233E-02, solve time:  2.24610E-03, relative residual:  3.72833E-18
### solver log, setup time:  2.09030E-02, solve time:  2.63080E-03, relative residual:  3.72669E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      89, total time:  8.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90995E-02, solve time:  2.66910E-03, relative residual:  3.76680E-18
### solver log, setup time:  1.95154E-02, solve time:  2.31660E-03, relative residual:  4.14829E-18
### solver log, setup time:  1.87848E-02, solve time:  2.24200E-03, relative residual:  3.70681E-18
### solver log, setup time:  2.14393E-02, solve time:  2.70630E-03, relative residual:  3.74132E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      90, total time:  9.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92220E-02, solve time:  2.37710E-03, relative residual:  3.91176E-18
### solver log, setup time:  1.96931E-02, solve time:  2.04770E-03, relative residual:  3.83650E-18
### solver log, setup time:  1.95227E-02, solve time:  2.28990E-03, relative residual:  3.99635E-18
### solver log, setup time:  3.66065E-02, solve time:  2.37260E-03, relative residual:  3.93360E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      91, total time:  9.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.19397E-02, solve time:  2.31640E-03, relative residual:  3.92599E-18
### solver log, setup time:  1.86149E-02, solve time:  2.15230E-03, relative residual:  3.82414E-18
### solver log, setup time:  2.26559E-02, solve time:  2.68550E-03, relative residual:  3.84383E-18
### solver log, setup time:  2.05261E-02, solve time:  2.47790E-03, relative residual:  3.77938E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      92, total time:  9.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.28536E-02, solve time:  3.49650E-03, relative residual:  3.66112E-18
### solver log, setup time:  2.01561E-02, solve time:  2.34010E-03, relative residual:  3.88446E-18
### solver log, setup time:  1.96152E-02, solve time:  2.27420E-03, relative residual:  3.97490E-18
### solver log, setup time:  2.00408E-02, solve time:  2.90140E-03, relative residual:  3.83471E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      93, total time:  9.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.93710E-02, solve time:  2.22010E-03, relative residual:  4.07158E-18
### solver log, setup time:  2.23959E-02, solve time:  2.35480E-03, relative residual:  4.04391E-18
### solver log, setup time:  2.18667E-02, solve time:  2.12920E-03, relative residual:  3.83951E-18
### solver log, setup time:  2.05286E-02, solve time:  3.12520E-03, relative residual:  3.89904E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      94, total time:  9.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.09188E-02, solve time:  1.84750E-03, relative residual:  3.94382E-18
### solver log, setup time:  1.86272E-02, solve time:  3.00830E-03, relative residual:  3.90539E-18
### solver log, setup time:  1.82150E-02, solve time:  2.34770E-03, relative residual:  3.87437E-18
### solver log, setup time:  2.27380E-02, solve time:  2.18710E-03, relative residual:  3.83049E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      95, total time:  9.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.12490E-02, solve time:  2.34130E-03, relative residual:  3.83061E-18
### solver log, setup time:  2.18001E-02, solve time:  2.36590E-03, relative residual:  3.76249E-18
### solver log, setup time:  1.91279E-02, solve time:  2.34000E-03, relative residual:  3.91155E-18
### solver log, setup time:  1.95483E-02, solve time:  2.40560E-03, relative residual:  3.67073E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      96, total time:  9.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.85810E-02, solve time:  2.23730E-03, relative residual:  3.76821E-18
### solver log, setup time:  1.96745E-02, solve time:  2.26270E-03, relative residual:  4.03924E-18
### solver log, setup time:  2.06962E-02, solve time:  2.46390E-03, relative residual:  3.61536E-18
### solver log, setup time:  2.26637E-02, solve time:  2.91770E-03, relative residual:  3.76710E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      97, total time:  9.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.89329E-02, solve time:  2.47390E-03, relative residual:  3.88937E-18
### solver log, setup time:  1.93081E-02, solve time:  2.36120E-03, relative residual:  3.73737E-18
### solver log, setup time:  2.03175E-02, solve time:  2.30520E-03, relative residual:  3.84143E-18
### solver log, setup time:  2.02520E-02, solve time:  2.35620E-03, relative residual:  3.90620E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      98, total time:  9.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.05698E-02, solve time:  2.76590E-03, relative residual:  3.80979E-18
### solver log, setup time:  2.02550E-02, solve time:  1.99970E-03, relative residual:  3.80507E-18
### solver log, setup time:  2.12719E-02, solve time:  3.60770E-03, relative residual:  3.80710E-18
### solver log, setup time:  1.87957E-02, solve time:  2.05760E-03, relative residual:  3.82099E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      99, total time:  9.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.26102E-02, solve time:  3.03800E-03, relative residual:  3.64575E-18
### solver log, setup time:  2.38193E-02, solve time:  2.77490E-03, relative residual:  3.74296E-18
### solver log, setup time:  1.74745E-02, solve time:  7.90410E-03, relative residual:  3.91508E-18
### solver log, setup time:  2.33618E-02, solve time:  2.73720E-03, relative residual:  4.02523E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :     100, total time:  1.00000E+00, delta t:  1.00000E-02
### solver log, setup time:  3.01274E-02, solve time:  3.29990E-03, relative residual:  3.79581E-18
### solver log, setup time:  2.78174E-02, solve time:  4.96490E-03, relative residual:  3.83448E-18
### solver log, setup time:  1.88162E-02, solve time:  2.63950E-03, relative residual:  3.92102E-18
### solver log, setup time:  2.11962E-02, solve time:  2.39320E-03, relative residual:  3.89212E-18
  !!! CONVERGENCE ACHIEVED 
 ====================================
    TOTAL TIME (sec) :    201.26
           pre (sec) :      0.08
         solve (sec) :    201.19
 ====================================



 :========================================:
 :**            END of FSTR             **:
 :========================================:
