 :========================================:
 :**   BEGIN FSTR Structural Analysis   **:
 :========================================:
         Total no. of processors:            1



  *    STAGE Initialization and input   **



  ***   STAGE Linear static analysis   **
step, substep, solve (sec) :,       1,       1,      0.02
### stepcount (for output), time :1, 1.00000000E+00
### FSTR_SOLVE_NLGEOM FINISHED!
 ====================================
    TOTAL TIME (sec) :      0.02
           pre (sec) :      0.00
         solve (sec) :      0.02
 ====================================



 :========================================:
 :**            END of FSTR             **:
 :========================================:
