 :========================================:
 :**   BEGIN FSTR Structural Analysis   **:
 :========================================:
         Total no. of processors:            1



  *    STAGE Initialization and input   **



  ***   STAGE Heat analysis    **
 =============================
   H E A T   T R A N S F E R  
 =============================
* Current step / Total step:        1/       1
* max iteration at each step:      100
* Transient anslysis
 ** Increment No. :       1, total time:  1.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  4.39734E-02, solve time:  2.72600E-03, relative residual:  5.35460E-18
### solver log, setup time:  2.36775E-02, solve time:  2.73600E-03, relative residual:  5.58886E-18
### solver log, setup time:  2.33663E-02, solve time:  3.82610E-03, relative residual:  5.17540E-18
### solver log, setup time:  2.71359E-02, solve time:  2.99510E-03, relative residual:  5.07913E-18
### solver log, setup time:  2.39357E-02, solve time:  2.56820E-03, relative residual:  5.20659E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       2, total time:  2.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.99882E-02, solve time:  2.20610E-03, relative residual:  5.33712E-18
### solver log, setup time:  1.92514E-02, solve time:  2.36860E-03, relative residual:  5.26953E-18
### solver log, setup time:  2.44398E-02, solve time:  2.28320E-03, relative residual:  5.10789E-18
### solver log, setup time:  2.23154E-02, solve time:  3.25870E-03, relative residual:  5.40170E-18
### solver log, setup time:  2.41965E-02, solve time:  2.24660E-03, relative residual:  5.27171E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       3, total time:  3.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.82804E-02, solve time:  2.14970E-03, relative residual:  5.31541E-18
### solver log, setup time:  1.74628E-02, solve time:  2.51750E-03, relative residual:  5.53027E-18
### solver log, setup time:  1.82724E-02, solve time:  2.52580E-03, relative residual:  5.03489E-18
### solver log, setup time:  1.81491E-02, solve time:  2.52060E-03, relative residual:  5.44707E-18
### solver log, setup time:  1.79247E-02, solve time:  2.20120E-03, relative residual:  5.28750E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       4, total time:  4.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.41260E-02, solve time:  2.59390E-03, relative residual:  5.19284E-18
### solver log, setup time:  1.86001E-02, solve time:  2.38580E-03, relative residual:  5.04827E-18
### solver log, setup time:  2.14065E-02, solve time:  2.27720E-03, relative residual:  4.80724E-18
### solver log, setup time:  2.26192E-02, solve time:  2.68570E-03, relative residual:  5.24504E-18
### solver log, setup time:  2.26184E-02, solve time:  2.65650E-03, relative residual:  5.09187E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       5, total time:  5.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.11220E-02, solve time:  2.23170E-03, relative residual:  5.01547E-18
### solver log, setup time:  2.29304E-02, solve time:  2.01460E-03, relative residual:  5.29082E-18
### solver log, setup time:  1.90032E-02, solve time:  2.21010E-03, relative residual:  4.86126E-18
### solver log, setup time:  2.01203E-02, solve time:  2.25690E-03, relative residual:  5.14118E-18
### solver log, setup time:  2.01222E-02, solve time:  2.71970E-03, relative residual:  5.13054E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       6, total time:  6.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.77538E-02, solve time:  3.59240E-03, relative residual:  5.28340E-18
### solver log, setup time:  2.15231E-02, solve time:  2.62030E-03, relative residual:  4.86670E-18
### solver log, setup time:  2.04932E-02, solve time:  2.41540E-03, relative residual:  5.22574E-18
### solver log, setup time:  1.76270E-02, solve time:  2.48330E-03, relative residual:  5.05359E-18
### solver log, setup time:  3.50224E-02, solve time:  8.90140E-03, relative residual:  5.07709E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       7, total time:  7.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.47457E-02, solve time:  2.53170E-03, relative residual:  4.96873E-18
### solver log, setup time:  2.06525E-02, solve time:  2.30270E-03, relative residual:  5.01330E-18
### solver log, setup time:  2.07557E-02, solve time:  2.43860E-03, relative residual:  4.89692E-18
### solver log, setup time:  2.09723E-02, solve time:  2.48100E-03, relative residual:  5.11242E-18
### solver log, setup time:  2.90033E-02, solve time:  2.79870E-03, relative residual:  4.92206E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       8, total time:  8.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.02666E-02, solve time:  1.99350E-03, relative residual:  4.99641E-18
### solver log, setup time:  2.03715E-02, solve time:  2.46490E-03, relative residual:  4.75291E-18
### solver log, setup time:  2.17686E-02, solve time:  2.98550E-03, relative residual:  4.95996E-18
### solver log, setup time:  2.14414E-02, solve time:  2.47520E-03, relative residual:  4.94233E-18
### solver log, setup time:  2.21292E-02, solve time:  3.27430E-03, relative residual:  4.76936E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       9, total time:  9.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.14992E-02, solve time:  2.57890E-03, relative residual:  4.73721E-18
### solver log, setup time:  2.22901E-02, solve time:  2.79340E-03, relative residual:  5.31295E-18
### solver log, setup time:  2.29172E-02, solve time:  3.32320E-03, relative residual:  4.79703E-18
### solver log, setup time:  2.35995E-02, solve time:  2.71170E-03, relative residual:  5.09200E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      10, total time:  1.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.38737E-02, solve time:  2.83810E-03, relative residual:  4.70446E-18
### solver log, setup time:  2.75317E-02, solve time:  3.31410E-03, relative residual:  4.79570E-18
### solver log, setup time:  2.97426E-02, solve time:  2.09440E-03, relative residual:  4.74145E-18
### solver log, setup time:  2.05539E-02, solve time:  2.44320E-03, relative residual:  4.64029E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      11, total time:  1.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.00068E-02, solve time:  2.66920E-03, relative residual:  4.69747E-18
### solver log, setup time:  2.77572E-02, solve time:  2.48070E-03, relative residual:  4.38607E-18
### solver log, setup time:  2.89513E-02, solve time:  2.88270E-03, relative residual:  4.48111E-18
### solver log, setup time:  3.16026E-02, solve time:  3.17780E-03, relative residual:  4.94014E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      12, total time:  1.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.69554E-02, solve time:  2.62200E-03, relative residual:  4.64884E-18
### solver log, setup time:  2.20141E-02, solve time:  2.53660E-03, relative residual:  4.56052E-18
### solver log, setup time:  2.94552E-02, solve time:  3.46340E-03, relative residual:  4.98813E-18
### solver log, setup time:  1.80078E-02, solve time:  2.30910E-03, relative residual:  4.58897E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      13, total time:  1.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.98117E-02, solve time:  2.55370E-03, relative residual:  4.66874E-18
### solver log, setup time:  2.22843E-02, solve time:  2.32500E-03, relative residual:  4.52508E-18
### solver log, setup time:  1.94913E-02, solve time:  2.73150E-03, relative residual:  4.66752E-18
### solver log, setup time:  2.03655E-02, solve time:  2.98890E-03, relative residual:  4.81262E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      14, total time:  1.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.81200E-02, solve time:  2.33570E-03, relative residual:  4.54503E-18
### solver log, setup time:  2.25425E-02, solve time:  3.25660E-03, relative residual:  4.80213E-18
### solver log, setup time:  1.83331E-02, solve time:  2.35660E-03, relative residual:  4.65458E-18
### solver log, setup time:  2.16859E-02, solve time:  2.40180E-03, relative residual:  4.55979E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      15, total time:  1.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.49243E-02, solve time:  2.64360E-03, relative residual:  4.73938E-18
### solver log, setup time:  2.14875E-02, solve time:  2.22070E-03, relative residual:  4.51565E-18
### solver log, setup time:  2.00060E-02, solve time:  2.27300E-03, relative residual:  4.69157E-18
### solver log, setup time:  2.15000E-02, solve time:  2.34790E-03, relative residual:  4.78362E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      16, total time:  1.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.19306E-02, solve time:  2.23650E-03, relative residual:  4.33018E-18
### solver log, setup time:  1.73985E-02, solve time:  2.47810E-03, relative residual:  4.34225E-18
### solver log, setup time:  1.75726E-02, solve time:  2.29870E-03, relative residual:  4.48821E-18
### solver log, setup time:  1.79940E-02, solve time:  2.24620E-03, relative residual:  4.77973E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      17, total time:  1.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.99828E-02, solve time:  2.12690E-03, relative residual:  4.53059E-18
### solver log, setup time:  1.80529E-02, solve time:  2.23840E-03, relative residual:  4.44877E-18
### solver log, setup time:  1.81535E-02, solve time:  2.16580E-03, relative residual:  4.50778E-18
### solver log, setup time:  2.48336E-02, solve time:  2.29380E-03, relative residual:  4.67994E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      18, total time:  1.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.15527E-02, solve time:  3.48850E-03, relative residual:  4.53197E-18
### solver log, setup time:  2.19428E-02, solve time:  2.06090E-03, relative residual:  4.30684E-18
### solver log, setup time:  2.30010E-02, solve time:  1.93750E-03, relative residual:  4.67327E-18
### solver log, setup time:  1.92062E-02, solve time:  2.40660E-03, relative residual:  4.58496E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      19, total time:  1.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.88796E-02, solve time:  2.39270E-03, relative residual:  4.44662E-18
### solver log, setup time:  2.21334E-02, solve time:  2.71280E-03, relative residual:  4.36395E-18
### solver log, setup time:  2.12876E-02, solve time:  2.91140E-03, relative residual:  4.25965E-18
### solver log, setup time:  1.87514E-02, solve time:  2.40150E-03, relative residual:  4.38220E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      20, total time:  2.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.05780E-02, solve time:  3.16080E-03, relative residual:  4.64571E-18
### solver log, setup time:  2.05820E-02, solve time:  2.06390E-03, relative residual:  4.71275E-18
### solver log, setup time:  1.84087E-02, solve time:  2.01930E-03, relative residual:  4.31670E-18
### solver log, setup time:  1.92593E-02, solve time:  2.51200E-03, relative residual:  4.30487E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      21, total time:  2.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.87166E-02, solve time:  2.43440E-03, relative residual:  4.47151E-18
### solver log, setup time:  1.90128E-02, solve time:  2.27130E-03, relative residual:  4.42716E-18
### solver log, setup time:  1.75680E-02, solve time:  2.58650E-03, relative residual:  4.52719E-18
### solver log, setup time:  1.84921E-02, solve time:  2.36840E-03, relative residual:  4.60420E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      22, total time:  2.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92810E-02, solve time:  3.15990E-03, relative residual:  3.92559E-18
### solver log, setup time:  1.95428E-02, solve time:  2.60610E-03, relative residual:  4.59197E-18
### solver log, setup time:  1.92354E-02, solve time:  2.53680E-03, relative residual:  4.19593E-18
### solver log, setup time:  1.79025E-02, solve time:  2.49180E-03, relative residual:  4.45603E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      23, total time:  2.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.93656E-02, solve time:  2.28420E-03, relative residual:  4.41818E-18
### solver log, setup time:  1.82551E-02, solve time:  2.92730E-03, relative residual:  4.19150E-18
### solver log, setup time:  1.90977E-02, solve time:  2.64410E-03, relative residual:  4.47883E-18
### solver log, setup time:  1.79956E-02, solve time:  2.39970E-03, relative residual:  4.52768E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      24, total time:  2.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83992E-02, solve time:  2.55300E-03, relative residual:  4.36284E-18
### solver log, setup time:  1.81600E-02, solve time:  2.41370E-03, relative residual:  4.49259E-18
### solver log, setup time:  2.08370E-02, solve time:  2.42610E-03, relative residual:  4.26620E-18
### solver log, setup time:  1.80333E-02, solve time:  2.71890E-03, relative residual:  4.54326E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      25, total time:  2.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83680E-02, solve time:  2.92690E-03, relative residual:  4.46204E-18
### solver log, setup time:  1.99996E-02, solve time:  2.35510E-03, relative residual:  4.28673E-18
### solver log, setup time:  1.85326E-02, solve time:  2.48940E-03, relative residual:  4.32283E-18
### solver log, setup time:  1.90548E-02, solve time:  2.89350E-03, relative residual:  4.30278E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      26, total time:  2.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.91256E-02, solve time:  2.43190E-03, relative residual:  4.31520E-18
### solver log, setup time:  2.13882E-02, solve time:  2.28690E-03, relative residual:  4.14763E-18
### solver log, setup time:  1.85132E-02, solve time:  2.40980E-03, relative residual:  4.34396E-18
### solver log, setup time:  1.97644E-02, solve time:  2.28190E-03, relative residual:  4.29187E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      27, total time:  2.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.89704E-02, solve time:  2.17050E-03, relative residual:  4.18278E-18
### solver log, setup time:  1.85097E-02, solve time:  2.44670E-03, relative residual:  4.18527E-18
### solver log, setup time:  1.86306E-02, solve time:  2.83500E-03, relative residual:  4.26414E-18
### solver log, setup time:  1.82116E-02, solve time:  2.65330E-03, relative residual:  4.07407E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      28, total time:  2.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.97973E-02, solve time:  2.71520E-03, relative residual:  4.41233E-18
### solver log, setup time:  1.93527E-02, solve time:  2.63880E-03, relative residual:  4.45565E-18
### solver log, setup time:  1.90524E-02, solve time:  2.42060E-03, relative residual:  4.19733E-18
### solver log, setup time:  1.85511E-02, solve time:  2.70280E-03, relative residual:  4.34764E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      29, total time:  2.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80094E-02, solve time:  2.76640E-03, relative residual:  4.25648E-18
### solver log, setup time:  1.77282E-02, solve time:  2.23170E-03, relative residual:  4.07398E-18
### solver log, setup time:  1.96912E-02, solve time:  2.60290E-03, relative residual:  4.23456E-18
### solver log, setup time:  1.85708E-02, solve time:  2.53940E-03, relative residual:  4.10999E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      30, total time:  3.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.11043E-02, solve time:  2.56480E-03, relative residual:  4.04529E-18
### solver log, setup time:  2.30629E-02, solve time:  2.33270E-03, relative residual:  4.01550E-18
### solver log, setup time:  2.20493E-02, solve time:  2.77290E-03, relative residual:  4.30454E-18
### solver log, setup time:  2.21166E-02, solve time:  2.24570E-03, relative residual:  4.34531E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      31, total time:  3.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.05757E-02, solve time:  2.30120E-03, relative residual:  4.13235E-18
### solver log, setup time:  1.92083E-02, solve time:  2.46360E-03, relative residual:  4.44411E-18
### solver log, setup time:  2.28922E-02, solve time:  3.00840E-03, relative residual:  4.67996E-18
### solver log, setup time:  2.01280E-02, solve time:  2.25410E-03, relative residual:  4.46270E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      32, total time:  3.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.16947E-02, solve time:  1.97030E-03, relative residual:  4.20863E-18
### solver log, setup time:  2.10870E-02, solve time:  2.11010E-03, relative residual:  4.02429E-18
### solver log, setup time:  1.85810E-02, solve time:  2.43060E-03, relative residual:  4.29150E-18
### solver log, setup time:  1.83319E-02, solve time:  2.20940E-03, relative residual:  4.03855E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      33, total time:  3.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.16574E-02, solve time:  2.09520E-03, relative residual:  4.14179E-18
### solver log, setup time:  1.83749E-02, solve time:  2.23790E-03, relative residual:  4.09865E-18
### solver log, setup time:  2.47561E-02, solve time:  3.08810E-03, relative residual:  4.35652E-18
### solver log, setup time:  1.88350E-02, solve time:  2.58020E-03, relative residual:  4.20311E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      34, total time:  3.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.06408E-02, solve time:  2.38440E-03, relative residual:  4.33756E-18
### solver log, setup time:  2.22462E-02, solve time:  2.94080E-03, relative residual:  4.17439E-18
### solver log, setup time:  2.13342E-02, solve time:  3.13030E-03, relative residual:  3.96231E-18
### solver log, setup time:  1.81679E-02, solve time:  2.62860E-03, relative residual:  3.96484E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      35, total time:  3.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.01812E-02, solve time:  1.97510E-03, relative residual:  4.47958E-18
### solver log, setup time:  2.55581E-02, solve time:  3.20520E-03, relative residual:  4.25775E-18
### solver log, setup time:  4.17313E-02, solve time:  3.60660E-03, relative residual:  4.13752E-18
### solver log, setup time:  3.02739E-02, solve time:  3.27220E-03, relative residual:  4.13685E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      36, total time:  3.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.34614E-02, solve time:  3.07100E-03, relative residual:  4.32633E-18
### solver log, setup time:  2.08214E-02, solve time:  2.21200E-03, relative residual:  4.11035E-18
### solver log, setup time:  2.02297E-02, solve time:  2.58130E-03, relative residual:  4.20685E-18
### solver log, setup time:  2.19815E-02, solve time:  2.06560E-03, relative residual:  4.40913E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      37, total time:  3.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.34974E-02, solve time:  4.58420E-03, relative residual:  4.09000E-18
### solver log, setup time:  2.26183E-02, solve time:  2.30540E-03, relative residual:  4.33216E-18
### solver log, setup time:  2.00040E-02, solve time:  2.40980E-03, relative residual:  4.20402E-18
### solver log, setup time:  2.81380E-02, solve time:  2.46070E-03, relative residual:  4.24233E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      38, total time:  3.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83312E-02, solve time:  2.15360E-03, relative residual:  4.21905E-18
### solver log, setup time:  2.29008E-02, solve time:  2.92330E-03, relative residual:  4.41016E-18
### solver log, setup time:  2.86012E-02, solve time:  3.09900E-03, relative residual:  4.07976E-18
### solver log, setup time:  2.10378E-02, solve time:  2.40360E-03, relative residual:  4.18848E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      39, total time:  3.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.16428E-02, solve time:  2.45440E-03, relative residual:  4.66860E-18
### solver log, setup time:  2.15948E-02, solve time:  2.75450E-03, relative residual:  4.04514E-18
### solver log, setup time:  2.14252E-02, solve time:  2.12520E-03, relative residual:  4.58013E-18
### solver log, setup time:  2.28216E-02, solve time:  2.16700E-03, relative residual:  4.18614E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      40, total time:  4.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95956E-02, solve time:  2.96780E-03, relative residual:  4.08972E-18
### solver log, setup time:  2.19429E-02, solve time:  4.58640E-03, relative residual:  4.12686E-18
### solver log, setup time:  2.60719E-02, solve time:  2.99230E-03, relative residual:  4.03656E-18
### solver log, setup time:  2.44921E-02, solve time:  2.31000E-03, relative residual:  3.98349E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      41, total time:  4.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  3.40296E-02, solve time:  5.52620E-03, relative residual:  4.02655E-18
### solver log, setup time:  1.99960E-02, solve time:  2.20980E-03, relative residual:  4.22610E-18
### solver log, setup time:  2.13970E-02, solve time:  2.09270E-03, relative residual:  4.02290E-18
### solver log, setup time:  2.11615E-02, solve time:  2.00010E-03, relative residual:  4.18343E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      42, total time:  4.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90449E-02, solve time:  3.28160E-03, relative residual:  4.27043E-18
### solver log, setup time:  1.86353E-02, solve time:  2.84850E-03, relative residual:  4.25771E-18
### solver log, setup time:  2.28940E-02, solve time:  2.45140E-03, relative residual:  4.09114E-18
### solver log, setup time:  1.89041E-02, solve time:  2.66410E-03, relative residual:  4.25247E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      43, total time:  4.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.88794E-02, solve time:  2.15870E-03, relative residual:  4.02379E-18
### solver log, setup time:  1.81594E-02, solve time:  2.32680E-03, relative residual:  4.11789E-18
### solver log, setup time:  1.97408E-02, solve time:  2.40410E-03, relative residual:  4.07926E-18
### solver log, setup time:  1.95375E-02, solve time:  2.70320E-03, relative residual:  4.04237E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      44, total time:  4.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78884E-02, solve time:  2.44700E-03, relative residual:  4.24632E-18
### solver log, setup time:  2.14196E-02, solve time:  2.30990E-03, relative residual:  4.14603E-18
### solver log, setup time:  1.75209E-02, solve time:  2.45790E-03, relative residual:  4.15058E-18
### solver log, setup time:  1.78763E-02, solve time:  2.22740E-03, relative residual:  4.31870E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      45, total time:  4.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.88871E-02, solve time:  2.39250E-03, relative residual:  4.08451E-18
### solver log, setup time:  1.76444E-02, solve time:  2.26940E-03, relative residual:  4.28593E-18
### solver log, setup time:  1.94586E-02, solve time:  2.45190E-03, relative residual:  4.12721E-18
### solver log, setup time:  1.91043E-02, solve time:  2.47890E-03, relative residual:  4.22154E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      46, total time:  4.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.76063E-02, solve time:  2.39310E-03, relative residual:  4.04701E-18
### solver log, setup time:  1.82418E-02, solve time:  2.45640E-03, relative residual:  4.52423E-18
### solver log, setup time:  2.07774E-02, solve time:  2.48540E-03, relative residual:  4.07655E-18
### solver log, setup time:  1.98428E-02, solve time:  2.76670E-03, relative residual:  4.09198E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      47, total time:  4.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.56777E-02, solve time:  2.67170E-03, relative residual:  4.00688E-18
### solver log, setup time:  1.88925E-02, solve time:  2.47520E-03, relative residual:  4.30818E-18
### solver log, setup time:  1.79434E-02, solve time:  2.11540E-03, relative residual:  4.25909E-18
### solver log, setup time:  1.91083E-02, solve time:  2.54070E-03, relative residual:  4.11776E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      48, total time:  4.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  3.15323E-02, solve time:  2.21080E-03, relative residual:  3.84422E-18
### solver log, setup time:  1.89029E-02, solve time:  2.72640E-03, relative residual:  3.98294E-18
### solver log, setup time:  1.78328E-02, solve time:  2.36410E-03, relative residual:  4.02555E-18
### solver log, setup time:  2.16780E-02, solve time:  2.31970E-03, relative residual:  3.96698E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      49, total time:  4.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82862E-02, solve time:  2.43000E-03, relative residual:  4.07619E-18
### solver log, setup time:  1.72818E-02, solve time:  1.90900E-03, relative residual:  4.15904E-18
### solver log, setup time:  1.80363E-02, solve time:  2.18090E-03, relative residual:  4.06881E-18
### solver log, setup time:  1.93088E-02, solve time:  3.22480E-03, relative residual:  3.94928E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      50, total time:  5.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.00866E-02, solve time:  2.15720E-03, relative residual:  3.95368E-18
### solver log, setup time:  1.79347E-02, solve time:  2.44040E-03, relative residual:  4.31108E-18
### solver log, setup time:  1.77345E-02, solve time:  4.07230E-03, relative residual:  4.24441E-18
### solver log, setup time:  1.76648E-02, solve time:  2.48300E-03, relative residual:  4.23570E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      51, total time:  5.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.97240E-02, solve time:  2.32060E-03, relative residual:  3.94823E-18
### solver log, setup time:  1.87232E-02, solve time:  2.07240E-03, relative residual:  4.18150E-18
### solver log, setup time:  1.80945E-02, solve time:  2.40150E-03, relative residual:  4.07888E-18
### solver log, setup time:  1.87932E-02, solve time:  2.42280E-03, relative residual:  4.22842E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      52, total time:  5.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.88859E-02, solve time:  2.39530E-03, relative residual:  4.19227E-18
### solver log, setup time:  1.82628E-02, solve time:  2.52490E-03, relative residual:  4.03272E-18
### solver log, setup time:  1.78765E-02, solve time:  2.36890E-03, relative residual:  4.08242E-18
### solver log, setup time:  1.82255E-02, solve time:  2.40590E-03, relative residual:  4.27712E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      53, total time:  5.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92033E-02, solve time:  2.50680E-03, relative residual:  4.07566E-18
### solver log, setup time:  1.77186E-02, solve time:  2.38180E-03, relative residual:  3.91507E-18
### solver log, setup time:  1.93344E-02, solve time:  2.49790E-03, relative residual:  4.24433E-18
### solver log, setup time:  2.20003E-02, solve time:  2.27730E-03, relative residual:  4.17552E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      54, total time:  5.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95298E-02, solve time:  2.69640E-03, relative residual:  4.29398E-18
### solver log, setup time:  2.62109E-02, solve time:  2.52050E-03, relative residual:  4.13691E-18
### solver log, setup time:  1.96791E-02, solve time:  2.74090E-03, relative residual:  4.17922E-18
### solver log, setup time:  2.11971E-02, solve time:  2.07840E-03, relative residual:  4.29933E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      55, total time:  5.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95400E-02, solve time:  1.85420E-03, relative residual:  4.21312E-18
### solver log, setup time:  1.88389E-02, solve time:  2.17890E-03, relative residual:  4.20601E-18
### solver log, setup time:  1.82455E-02, solve time:  2.54830E-03, relative residual:  4.09987E-18
### solver log, setup time:  2.41053E-02, solve time:  2.54330E-03, relative residual:  4.11773E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      56, total time:  5.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.52902E-02, solve time:  2.34580E-03, relative residual:  3.87933E-18
### solver log, setup time:  2.22771E-02, solve time:  2.42800E-03, relative residual:  4.18365E-18
### solver log, setup time:  2.16608E-02, solve time:  2.25120E-03, relative residual:  4.24909E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      57, total time:  5.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79080E-02, solve time:  2.05810E-03, relative residual:  4.23058E-18
### solver log, setup time:  1.91079E-02, solve time:  2.45990E-03, relative residual:  4.21774E-18
### solver log, setup time:  2.00206E-02, solve time:  1.99520E-03, relative residual:  3.94424E-18
### solver log, setup time:  2.03537E-02, solve time:  2.21320E-03, relative residual:  4.18972E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      58, total time:  5.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.47863E-02, solve time:  2.06870E-03, relative residual:  4.10346E-18
### solver log, setup time:  2.31958E-02, solve time:  3.76780E-03, relative residual:  4.10415E-18
### solver log, setup time:  2.09468E-02, solve time:  2.81030E-03, relative residual:  4.21345E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      59, total time:  5.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.20251E-02, solve time:  2.37530E-03, relative residual:  4.12161E-18
### solver log, setup time:  2.16649E-02, solve time:  2.19810E-03, relative residual:  3.84537E-18
### solver log, setup time:  2.36515E-02, solve time:  2.26470E-03, relative residual:  4.41418E-18
### solver log, setup time:  2.02582E-02, solve time:  2.79760E-03, relative residual:  3.90885E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      60, total time:  6.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.96074E-02, solve time:  2.49110E-03, relative residual:  4.15029E-18
### solver log, setup time:  3.58608E-02, solve time:  3.81250E-03, relative residual:  4.06073E-18
### solver log, setup time:  2.62295E-02, solve time:  2.28420E-03, relative residual:  3.98824E-18
### solver log, setup time:  2.49598E-02, solve time:  3.51720E-03, relative residual:  4.14916E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      61, total time:  6.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.43699E-02, solve time:  2.38730E-03, relative residual:  4.09970E-18
### solver log, setup time:  2.97855E-02, solve time:  5.80690E-03, relative residual:  4.09967E-18
### solver log, setup time:  2.26570E-02, solve time:  3.27200E-03, relative residual:  4.02286E-18
### solver log, setup time:  1.96401E-02, solve time:  2.81080E-03, relative residual:  3.93969E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      62, total time:  6.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.59006E-02, solve time:  2.56970E-03, relative residual:  3.67961E-18
### solver log, setup time:  2.40608E-02, solve time:  3.00810E-03, relative residual:  4.16395E-18
### solver log, setup time:  1.91328E-02, solve time:  2.73610E-03, relative residual:  4.18362E-18
### solver log, setup time:  2.01870E-02, solve time:  2.11670E-03, relative residual:  4.44309E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      63, total time:  6.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.98837E-02, solve time:  2.06910E-03, relative residual:  3.99207E-18
### solver log, setup time:  2.42826E-02, solve time:  3.14780E-03, relative residual:  4.00532E-18
### solver log, setup time:  2.53573E-02, solve time:  3.28470E-03, relative residual:  4.02670E-18
### solver log, setup time:  2.10887E-02, solve time:  2.75200E-03, relative residual:  3.95814E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      64, total time:  6.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.63918E-02, solve time:  2.00110E-03, relative residual:  4.33462E-18
### solver log, setup time:  1.82808E-02, solve time:  2.73060E-03, relative residual:  4.09499E-18
### solver log, setup time:  2.03902E-02, solve time:  3.12640E-03, relative residual:  4.32092E-18
### solver log, setup time:  2.43802E-02, solve time:  2.38280E-03, relative residual:  4.37592E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      65, total time:  6.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.27751E-02, solve time:  2.28310E-03, relative residual:  4.04692E-18
### solver log, setup time:  2.06431E-02, solve time:  2.06800E-03, relative residual:  4.07659E-18
### solver log, setup time:  2.16239E-02, solve time:  2.96080E-03, relative residual:  3.95285E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      66, total time:  6.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90538E-02, solve time:  2.06240E-03, relative residual:  3.99222E-18
### solver log, setup time:  2.08455E-02, solve time:  3.31500E-03, relative residual:  4.32042E-18
### solver log, setup time:  2.07013E-02, solve time:  2.39160E-03, relative residual:  4.27128E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      67, total time:  6.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.37659E-02, solve time:  2.52340E-03, relative residual:  4.09607E-18
### solver log, setup time:  2.28617E-02, solve time:  3.46400E-03, relative residual:  4.21322E-18
### solver log, setup time:  2.33683E-02, solve time:  5.31350E-03, relative residual:  4.34406E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      68, total time:  6.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.97335E-02, solve time:  2.43520E-03, relative residual:  4.48632E-18
### solver log, setup time:  2.43821E-02, solve time:  2.10430E-03, relative residual:  4.17171E-18
### solver log, setup time:  2.26146E-02, solve time:  2.54570E-03, relative residual:  4.01626E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      69, total time:  6.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.72424E-02, solve time:  2.42850E-03, relative residual:  3.90315E-18
### solver log, setup time:  3.21256E-02, solve time:  3.02710E-03, relative residual:  4.55899E-18
### solver log, setup time:  1.76378E-02, solve time:  2.26740E-03, relative residual:  4.14269E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      70, total time:  7.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.38280E-02, solve time:  2.72440E-03, relative residual:  4.01878E-18
### solver log, setup time:  1.88830E-02, solve time:  3.03340E-03, relative residual:  4.06866E-18
### solver log, setup time:  2.43166E-02, solve time:  3.11540E-03, relative residual:  4.08148E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      71, total time:  7.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.02200E-02, solve time:  2.33050E-03, relative residual:  4.06080E-18
### solver log, setup time:  1.80575E-02, solve time:  2.19080E-03, relative residual:  4.32872E-18
### solver log, setup time:  2.60002E-02, solve time:  2.36570E-03, relative residual:  4.07995E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      72, total time:  7.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.35634E-02, solve time:  2.41420E-03, relative residual:  4.08218E-18
### solver log, setup time:  2.11084E-02, solve time:  2.31920E-03, relative residual:  4.31711E-18
### solver log, setup time:  2.30226E-02, solve time:  2.25940E-03, relative residual:  4.04773E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      73, total time:  7.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.15811E-02, solve time:  2.47110E-03, relative residual:  4.31535E-18
### solver log, setup time:  2.30415E-02, solve time:  2.48490E-03, relative residual:  4.13946E-18
### solver log, setup time:  2.23712E-02, solve time:  2.58740E-03, relative residual:  4.06509E-18
### solver log, setup time:  2.01823E-02, solve time:  2.44990E-03, relative residual:  4.12221E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      74, total time:  7.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.96905E-02, solve time:  2.75380E-03, relative residual:  4.09055E-18
### solver log, setup time:  2.68395E-02, solve time:  3.92310E-03, relative residual:  3.96383E-18
### solver log, setup time:  1.92931E-02, solve time:  3.58580E-03, relative residual:  4.06657E-18
### solver log, setup time:  2.42153E-02, solve time:  3.41320E-03, relative residual:  4.11299E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      75, total time:  7.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.13009E-02, solve time:  2.20500E-03, relative residual:  4.11628E-18
### solver log, setup time:  2.10190E-02, solve time:  2.71840E-03, relative residual:  3.93893E-18
### solver log, setup time:  2.15445E-02, solve time:  2.15770E-03, relative residual:  4.12677E-18
### solver log, setup time:  2.26040E-02, solve time:  3.37330E-03, relative residual:  4.14132E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      76, total time:  7.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.24523E-02, solve time:  2.21610E-03, relative residual:  4.13347E-18
### solver log, setup time:  2.19146E-02, solve time:  2.11490E-03, relative residual:  3.91297E-18
### solver log, setup time:  2.32164E-02, solve time:  2.01810E-03, relative residual:  3.95651E-18
### solver log, setup time:  2.74035E-02, solve time:  2.33420E-03, relative residual:  4.35396E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      77, total time:  7.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95133E-02, solve time:  3.45650E-03, relative residual:  4.65686E-18
### solver log, setup time:  1.88736E-02, solve time:  2.28100E-03, relative residual:  4.34801E-18
### solver log, setup time:  1.94238E-02, solve time:  2.36500E-03, relative residual:  4.03982E-18
### solver log, setup time:  2.60006E-02, solve time:  2.22360E-03, relative residual:  3.91523E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      78, total time:  7.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.97665E-02, solve time:  2.23330E-03, relative residual:  4.43836E-18
### solver log, setup time:  2.05154E-02, solve time:  2.29410E-03, relative residual:  3.98522E-18
### solver log, setup time:  2.06094E-02, solve time:  2.36830E-03, relative residual:  4.02582E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      79, total time:  7.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.81884E-02, solve time:  2.43870E-03, relative residual:  4.09548E-18
### solver log, setup time:  2.15859E-02, solve time:  2.47080E-03, relative residual:  4.27880E-18
### solver log, setup time:  1.90121E-02, solve time:  2.20980E-03, relative residual:  4.31134E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      80, total time:  8.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.14275E-02, solve time:  2.47330E-03, relative residual:  3.84652E-18
### solver log, setup time:  1.94764E-02, solve time:  1.88360E-03, relative residual:  3.93970E-18
### solver log, setup time:  2.44688E-02, solve time:  2.02950E-03, relative residual:  3.96280E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      81, total time:  8.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.55688E-02, solve time:  2.69380E-03, relative residual:  3.99060E-18
### solver log, setup time:  2.14616E-02, solve time:  2.39560E-03, relative residual:  4.06933E-18
### solver log, setup time:  2.33574E-02, solve time:  3.66560E-03, relative residual:  4.03503E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      82, total time:  8.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.03172E-02, solve time:  2.99360E-03, relative residual:  4.38524E-18
### solver log, setup time:  2.30210E-02, solve time:  2.31050E-03, relative residual:  3.99080E-18
### solver log, setup time:  1.97590E-02, solve time:  3.45460E-03, relative residual:  4.13111E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      83, total time:  8.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80373E-02, solve time:  2.47910E-03, relative residual:  3.97744E-18
### solver log, setup time:  1.85051E-02, solve time:  2.11940E-03, relative residual:  4.34680E-18
### solver log, setup time:  2.42371E-02, solve time:  2.18050E-03, relative residual:  4.28228E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      84, total time:  8.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.24842E-02, solve time:  3.30740E-03, relative residual:  3.97770E-18
### solver log, setup time:  2.03203E-02, solve time:  2.76600E-03, relative residual:  4.18301E-18
### solver log, setup time:  2.02434E-02, solve time:  3.06170E-03, relative residual:  4.12153E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      85, total time:  8.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.84252E-02, solve time:  2.49160E-03, relative residual:  4.20120E-18
### solver log, setup time:  1.83777E-02, solve time:  2.60050E-03, relative residual:  3.95840E-18
### solver log, setup time:  1.95016E-02, solve time:  2.57000E-03, relative residual:  4.04733E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      86, total time:  8.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.03638E-02, solve time:  2.74550E-03, relative residual:  4.19514E-18
### solver log, setup time:  1.93793E-02, solve time:  2.87260E-03, relative residual:  4.07370E-18
### solver log, setup time:  1.88421E-02, solve time:  2.61320E-03, relative residual:  4.21492E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      87, total time:  8.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.37554E-02, solve time:  3.54430E-03, relative residual:  4.23106E-18
### solver log, setup time:  2.10772E-02, solve time:  2.37990E-03, relative residual:  4.21533E-18
### solver log, setup time:  2.49418E-02, solve time:  3.15190E-03, relative residual:  4.46425E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      88, total time:  8.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.26783E-02, solve time:  2.53070E-03, relative residual:  4.19950E-18
### solver log, setup time:  2.21815E-02, solve time:  2.99170E-03, relative residual:  4.21422E-18
### solver log, setup time:  2.28615E-02, solve time:  2.52860E-03, relative residual:  4.17284E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      89, total time:  8.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.97193E-02, solve time:  2.38400E-03, relative residual:  4.16424E-18
### solver log, setup time:  1.94492E-02, solve time:  2.58100E-03, relative residual:  4.05190E-18
### solver log, setup time:  2.17686E-02, solve time:  2.38260E-03, relative residual:  4.00706E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      90, total time:  9.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.30499E-02, solve time:  3.19980E-03, relative residual:  4.27469E-18
### solver log, setup time:  2.27697E-02, solve time:  2.35910E-03, relative residual:  4.06678E-18
### solver log, setup time:  1.96724E-02, solve time:  2.06500E-03, relative residual:  4.30900E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      91, total time:  9.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92307E-02, solve time:  2.41440E-03, relative residual:  4.10767E-18
### solver log, setup time:  2.56697E-02, solve time:  3.02030E-03, relative residual:  4.44609E-18
### solver log, setup time:  2.10559E-02, solve time:  2.35130E-03, relative residual:  4.28265E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      92, total time:  9.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.04155E-02, solve time:  2.47690E-03, relative residual:  4.10268E-18
### solver log, setup time:  2.08689E-02, solve time:  3.46770E-03, relative residual:  4.32278E-18
### solver log, setup time:  2.43959E-02, solve time:  2.82450E-03, relative residual:  4.05606E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      93, total time:  9.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.87373E-02, solve time:  2.34340E-03, relative residual:  3.91456E-18
### solver log, setup time:  1.97249E-02, solve time:  2.77950E-03, relative residual:  4.24721E-18
### solver log, setup time:  1.77796E-02, solve time:  2.31730E-03, relative residual:  4.06204E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      94, total time:  9.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80961E-02, solve time:  2.30130E-03, relative residual:  4.01548E-18
### solver log, setup time:  1.87256E-02, solve time:  2.30680E-03, relative residual:  4.18484E-18
### solver log, setup time:  1.79131E-02, solve time:  2.44910E-03, relative residual:  4.51264E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      95, total time:  9.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.85741E-02, solve time:  1.96190E-03, relative residual:  4.08741E-18
### solver log, setup time:  2.31394E-02, solve time:  3.23190E-03, relative residual:  4.15600E-18
### solver log, setup time:  2.11715E-02, solve time:  2.40180E-03, relative residual:  4.29021E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      96, total time:  9.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79333E-02, solve time:  2.30280E-03, relative residual:  4.33594E-18
### solver log, setup time:  2.17609E-02, solve time:  2.29610E-03, relative residual:  4.28190E-18
### solver log, setup time:  2.23943E-02, solve time:  3.45400E-03, relative residual:  4.27689E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      97, total time:  9.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.85532E-02, solve time:  2.25330E-03, relative residual:  4.07179E-18
### solver log, setup time:  2.11660E-02, solve time:  2.37450E-03, relative residual:  4.20645E-18
### solver log, setup time:  2.59412E-02, solve time:  2.59350E-03, relative residual:  4.04890E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      98, total time:  9.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80180E-02, solve time:  2.09160E-03, relative residual:  4.27355E-18
### solver log, setup time:  1.90645E-02, solve time:  2.06200E-03, relative residual:  4.32878E-18
### solver log, setup time:  1.99655E-02, solve time:  2.28110E-03, relative residual:  4.47269E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      99, total time:  9.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79472E-02, solve time:  2.35470E-03, relative residual:  4.29070E-18
### solver log, setup time:  2.28594E-02, solve time:  2.08110E-03, relative residual:  4.06818E-18
### solver log, setup time:  2.21196E-02, solve time:  2.24160E-03, relative residual:  4.27480E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :     100, total time:  1.00000E+00, delta t:  1.00000E-02
### solver log, setup time:  1.93602E-02, solve time:  2.14590E-03, relative residual:  4.07422E-18
### solver log, setup time:  2.05580E-02, solve time:  2.13220E-03, relative residual:  3.93569E-18
### solver log, setup time:  1.85806E-02, solve time:  2.11040E-03, relative residual:  4.32759E-18
  !!! CONVERGENCE ACHIEVED 
 ====================================
    TOTAL TIME (sec) :    183.18
           pre (sec) :      0.15
         solve (sec) :    183.03
 ====================================



 :========================================:
 :**            END of FSTR             **:
 :========================================:
