 :========================================:
 :**   BEGIN FSTR Structural Analysis   **:
 :========================================:
         Total no. of processors:            1



  *    STAGE Initialization and input   **



  ***   STAGE Heat analysis    **
 =============================
   H E A T   T R A N S F E R  
 =============================
* Current step / Total step:        1/       1
* max iteration at each step:      100
* Transient anslysis
 ** Increment No. :       1, total time:  1.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  3.10463E-02, solve time:  2.42370E-03, relative residual:  6.66027E-18
### solver log, setup time:  1.93219E-02, solve time:  2.74890E-03, relative residual:  5.73185E-18
### solver log, setup time:  1.92655E-02, solve time:  2.43200E-03, relative residual:  6.39745E-18
### solver log, setup time:  1.89869E-02, solve time:  2.74270E-03, relative residual:  6.09870E-18
### solver log, setup time:  1.93738E-02, solve time:  2.34630E-03, relative residual:  6.40352E-18
### solver log, setup time:  1.78211E-02, solve time:  2.40510E-03, relative residual:  6.53481E-18
### solver log, setup time:  2.24904E-02, solve time:  2.20590E-03, relative residual:  6.65347E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       2, total time:  2.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.77009E-02, solve time:  2.34840E-03, relative residual:  6.14770E-18
### solver log, setup time:  2.15509E-02, solve time:  2.26390E-03, relative residual:  6.05791E-18
### solver log, setup time:  2.37565E-02, solve time:  2.35460E-03, relative residual:  6.17115E-18
### solver log, setup time:  2.04556E-02, solve time:  3.13540E-03, relative residual:  5.93063E-18
### solver log, setup time:  1.98312E-02, solve time:  2.29830E-03, relative residual:  6.00627E-18
### solver log, setup time:  2.23194E-02, solve time:  2.23730E-03, relative residual:  6.09717E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       3, total time:  3.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.06241E-02, solve time:  2.60540E-03, relative residual:  6.12188E-18
### solver log, setup time:  2.09090E-02, solve time:  2.18740E-03, relative residual:  5.98430E-18
### solver log, setup time:  2.06187E-02, solve time:  2.41620E-03, relative residual:  5.98811E-18
### solver log, setup time:  2.58436E-02, solve time:  3.13870E-03, relative residual:  5.77419E-18
### solver log, setup time:  2.28969E-02, solve time:  2.44730E-03, relative residual:  6.04134E-18
### solver log, setup time:  1.84054E-02, solve time:  2.49460E-03, relative residual:  5.75572E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       4, total time:  4.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.91560E-02, solve time:  3.06310E-03, relative residual:  5.87181E-18
### solver log, setup time:  1.94192E-02, solve time:  2.34610E-03, relative residual:  5.92574E-18
### solver log, setup time:  1.92013E-02, solve time:  2.44560E-03, relative residual:  5.94930E-18
### solver log, setup time:  1.84242E-02, solve time:  2.52580E-03, relative residual:  5.86658E-18
### solver log, setup time:  2.30667E-02, solve time:  2.14170E-03, relative residual:  5.91552E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       5, total time:  5.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.92224E-02, solve time:  2.50250E-03, relative residual:  5.92218E-18
### solver log, setup time:  2.02591E-02, solve time:  2.47840E-03, relative residual:  5.77017E-18
### solver log, setup time:  2.77802E-02, solve time:  3.48010E-03, relative residual:  6.13101E-18
### solver log, setup time:  1.93874E-02, solve time:  2.37890E-03, relative residual:  5.69752E-18
### solver log, setup time:  1.79619E-02, solve time:  2.19870E-03, relative residual:  5.76447E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       6, total time:  6.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.93150E-02, solve time:  2.16170E-03, relative residual:  5.98141E-18
### solver log, setup time:  1.77385E-02, solve time:  2.41860E-03, relative residual:  5.42843E-18
### solver log, setup time:  1.87706E-02, solve time:  2.22780E-03, relative residual:  5.99840E-18
### solver log, setup time:  1.95864E-02, solve time:  2.23050E-03, relative residual:  5.60527E-18
### solver log, setup time:  1.72342E-02, solve time:  2.11370E-03, relative residual:  5.74292E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       7, total time:  7.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.21814E-02, solve time:  2.18920E-03, relative residual:  5.63033E-18
### solver log, setup time:  1.75617E-02, solve time:  2.27710E-03, relative residual:  5.91037E-18
### solver log, setup time:  1.79709E-02, solve time:  2.22640E-03, relative residual:  5.77897E-18
### solver log, setup time:  2.61321E-02, solve time:  3.06270E-03, relative residual:  5.80262E-18
### solver log, setup time:  2.23025E-02, solve time:  2.37960E-03, relative residual:  5.66744E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       8, total time:  8.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.09309E-02, solve time:  2.75510E-03, relative residual:  6.40616E-18
### solver log, setup time:  1.95213E-02, solve time:  2.39270E-03, relative residual:  5.55503E-18
### solver log, setup time:  2.11033E-02, solve time:  2.26420E-03, relative residual:  5.94043E-18
### solver log, setup time:  3.19290E-02, solve time:  6.03340E-03, relative residual:  5.65738E-18
### solver log, setup time:  2.10327E-02, solve time:  2.28220E-03, relative residual:  6.06499E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       9, total time:  9.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.45835E-02, solve time:  2.49620E-03, relative residual:  5.95214E-18
### solver log, setup time:  1.99834E-02, solve time:  2.47850E-03, relative residual:  5.80795E-18
### solver log, setup time:  2.45371E-02, solve time:  3.35570E-03, relative residual:  5.65519E-18
### solver log, setup time:  2.31140E-02, solve time:  2.34250E-03, relative residual:  5.65281E-18
### solver log, setup time:  1.90891E-02, solve time:  2.69510E-03, relative residual:  5.42599E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      10, total time:  1.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.93831E-02, solve time:  2.39510E-03, relative residual:  6.00809E-18
### solver log, setup time:  1.99297E-02, solve time:  2.69880E-03, relative residual:  5.97497E-18
### solver log, setup time:  2.24023E-02, solve time:  1.94030E-03, relative residual:  6.06140E-18
### solver log, setup time:  1.93216E-02, solve time:  1.96560E-03, relative residual:  5.84843E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      11, total time:  1.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.18275E-02, solve time:  3.27380E-03, relative residual:  5.95665E-18
### solver log, setup time:  2.55115E-02, solve time:  3.56440E-03, relative residual:  5.87811E-18
### solver log, setup time:  2.66224E-02, solve time:  2.45540E-03, relative residual:  5.90428E-18
### solver log, setup time:  2.06999E-02, solve time:  3.94120E-03, relative residual:  5.82640E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      12, total time:  1.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83425E-02, solve time:  1.96410E-03, relative residual:  5.76325E-18
### solver log, setup time:  2.16062E-02, solve time:  2.17540E-03, relative residual:  5.92754E-18
### solver log, setup time:  1.84499E-02, solve time:  2.20790E-03, relative residual:  5.75853E-18
### solver log, setup time:  2.31396E-02, solve time:  2.14890E-03, relative residual:  6.35374E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      13, total time:  1.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.03798E-02, solve time:  2.80280E-03, relative residual:  6.03065E-18
### solver log, setup time:  1.90856E-02, solve time:  2.08790E-03, relative residual:  5.63340E-18
### solver log, setup time:  2.31830E-02, solve time:  2.33030E-03, relative residual:  5.77947E-18
### solver log, setup time:  3.12269E-02, solve time:  2.27000E-03, relative residual:  5.92293E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      14, total time:  1.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.45257E-02, solve time:  2.46750E-03, relative residual:  6.34063E-18
### solver log, setup time:  1.91429E-02, solve time:  2.67200E-03, relative residual:  5.92172E-18
### solver log, setup time:  1.75258E-02, solve time:  2.33800E-03, relative residual:  6.07074E-18
### solver log, setup time:  2.03266E-02, solve time:  3.54000E-03, relative residual:  5.84541E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      15, total time:  1.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.88264E-02, solve time:  2.52580E-03, relative residual:  6.05162E-18
### solver log, setup time:  2.18805E-02, solve time:  2.26380E-03, relative residual:  6.44974E-18
### solver log, setup time:  1.95924E-02, solve time:  2.57520E-03, relative residual:  6.11634E-18
### solver log, setup time:  2.08796E-02, solve time:  3.29270E-03, relative residual:  6.17938E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      16, total time:  1.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.24493E-02, solve time:  2.34120E-03, relative residual:  6.32335E-18
### solver log, setup time:  2.01301E-02, solve time:  2.24090E-03, relative residual:  5.70674E-18
### solver log, setup time:  2.46628E-02, solve time:  2.40600E-03, relative residual:  6.02465E-18
### solver log, setup time:  2.05918E-02, solve time:  2.47010E-03, relative residual:  6.30427E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      17, total time:  1.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.13182E-02, solve time:  2.32760E-03, relative residual:  6.34160E-18
### solver log, setup time:  2.15443E-02, solve time:  3.23940E-03, relative residual:  6.58316E-18
### solver log, setup time:  2.32752E-02, solve time:  2.19500E-03, relative residual:  6.02691E-18
### solver log, setup time:  1.95359E-02, solve time:  2.36850E-03, relative residual:  6.35885E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      18, total time:  1.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.15252E-02, solve time:  2.87610E-03, relative residual:  6.05123E-18
### solver log, setup time:  2.48617E-02, solve time:  4.06920E-03, relative residual:  6.36649E-18
### solver log, setup time:  2.30464E-02, solve time:  2.17980E-03, relative residual:  6.32907E-18
### solver log, setup time:  1.97347E-02, solve time:  2.30070E-03, relative residual:  5.82125E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      19, total time:  1.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.02885E-02, solve time:  3.14310E-03, relative residual:  6.05057E-18
### solver log, setup time:  2.00060E-02, solve time:  2.29630E-03, relative residual:  6.25968E-18
### solver log, setup time:  1.76148E-02, solve time:  2.40960E-03, relative residual:  6.35621E-18
### solver log, setup time:  1.85620E-02, solve time:  2.24870E-03, relative residual:  6.39805E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      20, total time:  2.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79011E-02, solve time:  2.47320E-03, relative residual:  6.54302E-18
### solver log, setup time:  1.72555E-02, solve time:  2.41190E-03, relative residual:  6.22590E-18
### solver log, setup time:  1.81781E-02, solve time:  3.29130E-03, relative residual:  6.15250E-18
### solver log, setup time:  1.84713E-02, solve time:  2.28020E-03, relative residual:  6.11649E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      21, total time:  2.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.94663E-02, solve time:  2.30360E-03, relative residual:  6.52337E-18
### solver log, setup time:  1.93046E-02, solve time:  2.82990E-03, relative residual:  6.23487E-18
### solver log, setup time:  2.12899E-02, solve time:  3.19350E-03, relative residual:  6.59882E-18
### solver log, setup time:  2.84509E-02, solve time:  3.49970E-03, relative residual:  6.74281E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      22, total time:  2.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.30558E-02, solve time:  2.30850E-03, relative residual:  6.51790E-18
### solver log, setup time:  2.28985E-02, solve time:  2.11520E-03, relative residual:  6.96737E-18
### solver log, setup time:  1.99550E-02, solve time:  2.39390E-03, relative residual:  6.58995E-18
### solver log, setup time:  2.65744E-02, solve time:  2.62540E-03, relative residual:  6.46133E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      23, total time:  2.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.93982E-02, solve time:  2.40590E-03, relative residual:  6.83459E-18
### solver log, setup time:  1.88289E-02, solve time:  2.50180E-03, relative residual:  6.40930E-18
### solver log, setup time:  2.89001E-02, solve time:  3.51590E-03, relative residual:  6.76017E-18
### solver log, setup time:  2.26285E-02, solve time:  2.93720E-03, relative residual:  7.00380E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      24, total time:  2.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.76818E-02, solve time:  2.10120E-03, relative residual:  6.39095E-18
### solver log, setup time:  2.48180E-02, solve time:  2.90230E-03, relative residual:  6.55392E-18
### solver log, setup time:  2.01115E-02, solve time:  2.35520E-03, relative residual:  6.31614E-18
### solver log, setup time:  2.35887E-02, solve time:  3.07440E-03, relative residual:  6.25546E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      25, total time:  2.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.25621E-02, solve time:  2.06660E-03, relative residual:  6.80506E-18
### solver log, setup time:  1.89558E-02, solve time:  2.15340E-03, relative residual:  7.15568E-18
### solver log, setup time:  1.86223E-02, solve time:  2.31170E-03, relative residual:  6.38001E-18
### solver log, setup time:  1.87568E-02, solve time:  2.35270E-03, relative residual:  6.98112E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      26, total time:  2.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.20227E-02, solve time:  2.01520E-03, relative residual:  7.39376E-18
### solver log, setup time:  2.02766E-02, solve time:  2.43110E-03, relative residual:  7.00159E-18
### solver log, setup time:  2.34883E-02, solve time:  2.83820E-03, relative residual:  6.57935E-18
### solver log, setup time:  1.79700E-02, solve time:  2.15750E-03, relative residual:  7.37328E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      27, total time:  2.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92859E-02, solve time:  2.31750E-03, relative residual:  7.25012E-18
### solver log, setup time:  2.23266E-02, solve time:  2.43300E-03, relative residual:  7.10876E-18
### solver log, setup time:  2.00659E-02, solve time:  3.18700E-03, relative residual:  7.09942E-18
### solver log, setup time:  2.10181E-02, solve time:  2.01850E-03, relative residual:  7.08067E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      28, total time:  2.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.09348E-02, solve time:  2.35360E-03, relative residual:  7.49669E-18
### solver log, setup time:  1.83816E-02, solve time:  2.22300E-03, relative residual:  6.98304E-18
### solver log, setup time:  1.76674E-02, solve time:  2.14390E-03, relative residual:  7.71816E-18
### solver log, setup time:  2.38183E-02, solve time:  2.17410E-03, relative residual:  7.10742E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      29, total time:  2.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.97078E-02, solve time:  2.55660E-03, relative residual:  6.92613E-18
### solver log, setup time:  1.84568E-02, solve time:  2.68680E-03, relative residual:  6.97471E-18
### solver log, setup time:  2.33301E-02, solve time:  2.17310E-03, relative residual:  7.20887E-18
### solver log, setup time:  2.52317E-02, solve time:  2.32520E-03, relative residual:  7.35659E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      30, total time:  3.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.09744E-02, solve time:  2.58280E-03, relative residual:  7.17213E-18
### solver log, setup time:  2.84479E-02, solve time:  2.35300E-03, relative residual:  7.49649E-18
### solver log, setup time:  1.95987E-02, solve time:  2.37380E-03, relative residual:  6.93512E-18
### solver log, setup time:  1.76068E-02, solve time:  2.17420E-03, relative residual:  6.85103E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      31, total time:  3.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.05155E-02, solve time:  2.59580E-03, relative residual:  7.02104E-18
### solver log, setup time:  2.40881E-02, solve time:  2.39300E-03, relative residual:  7.14198E-18
### solver log, setup time:  2.04360E-02, solve time:  2.20990E-03, relative residual:  7.66132E-18
### solver log, setup time:  1.75908E-02, solve time:  2.37920E-03, relative residual:  7.09099E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      32, total time:  3.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.84091E-02, solve time:  2.92060E-03, relative residual:  7.04283E-18
### solver log, setup time:  1.75212E-02, solve time:  2.13370E-03, relative residual:  7.54835E-18
### solver log, setup time:  1.76950E-02, solve time:  2.41310E-03, relative residual:  6.93937E-18
### solver log, setup time:  1.85975E-02, solve time:  2.02880E-03, relative residual:  6.81894E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      33, total time:  3.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.93710E-02, solve time:  2.20020E-03, relative residual:  8.12706E-18
### solver log, setup time:  1.79716E-02, solve time:  1.97320E-03, relative residual:  6.95326E-18
### solver log, setup time:  1.73949E-02, solve time:  2.35750E-03, relative residual:  7.14417E-18
### solver log, setup time:  1.78256E-02, solve time:  2.31930E-03, relative residual:  7.05317E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      34, total time:  3.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.72347E-02, solve time:  2.07280E-03, relative residual:  7.41025E-18
### solver log, setup time:  1.91516E-02, solve time:  2.62760E-03, relative residual:  7.09598E-18
### solver log, setup time:  1.88775E-02, solve time:  2.18530E-03, relative residual:  7.03038E-18
### solver log, setup time:  1.95190E-02, solve time:  2.23070E-03, relative residual:  7.29245E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      35, total time:  3.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.08832E-02, solve time:  2.29250E-03, relative residual:  7.55588E-18
### solver log, setup time:  2.04884E-02, solve time:  2.24430E-03, relative residual:  7.71749E-18
### solver log, setup time:  1.82261E-02, solve time:  2.19020E-03, relative residual:  7.72904E-18
### solver log, setup time:  1.99483E-02, solve time:  2.19610E-03, relative residual:  7.88581E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      36, total time:  3.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.85575E-02, solve time:  2.37900E-03, relative residual:  7.40487E-18
### solver log, setup time:  2.05070E-02, solve time:  2.59480E-03, relative residual:  7.85572E-18
### solver log, setup time:  2.22435E-02, solve time:  3.25420E-03, relative residual:  7.71750E-18
### solver log, setup time:  2.26380E-02, solve time:  2.47270E-03, relative residual:  7.64343E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      37, total time:  3.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.06372E-02, solve time:  2.72340E-03, relative residual:  7.60216E-18
### solver log, setup time:  1.77630E-02, solve time:  2.37430E-03, relative residual:  7.71045E-18
### solver log, setup time:  1.99680E-02, solve time:  2.91450E-03, relative residual:  8.09262E-18
### solver log, setup time:  1.77070E-02, solve time:  2.57420E-03, relative residual:  7.32781E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      38, total time:  3.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79944E-02, solve time:  2.22360E-03, relative residual:  7.17115E-18
### solver log, setup time:  1.78560E-02, solve time:  2.32110E-03, relative residual:  8.25793E-18
### solver log, setup time:  2.08445E-02, solve time:  2.62650E-03, relative residual:  7.59749E-18
### solver log, setup time:  1.97764E-02, solve time:  1.92270E-03, relative residual:  7.63956E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      39, total time:  3.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.74663E-02, solve time:  2.44530E-03, relative residual:  7.19789E-18
### solver log, setup time:  2.10279E-02, solve time:  2.82290E-03, relative residual:  8.33707E-18
### solver log, setup time:  2.13682E-02, solve time:  2.54100E-03, relative residual:  7.55177E-18
### solver log, setup time:  2.11346E-02, solve time:  2.45720E-03, relative residual:  7.56178E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      40, total time:  4.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83244E-02, solve time:  2.22860E-03, relative residual:  7.89356E-18
### solver log, setup time:  1.86751E-02, solve time:  2.17900E-03, relative residual:  8.66862E-18
### solver log, setup time:  2.14854E-02, solve time:  2.58550E-03, relative residual:  8.14067E-18
### solver log, setup time:  1.76671E-02, solve time:  2.51960E-03, relative residual:  7.05502E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      41, total time:  4.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.18799E-02, solve time:  2.14640E-03, relative residual:  8.27786E-18
### solver log, setup time:  1.77363E-02, solve time:  2.21630E-03, relative residual:  7.62339E-18
### solver log, setup time:  1.97688E-02, solve time:  3.13640E-03, relative residual:  8.06238E-18
### solver log, setup time:  1.87138E-02, solve time:  2.22050E-03, relative residual:  7.60548E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      42, total time:  4.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.74841E-02, solve time:  2.30460E-03, relative residual:  7.82391E-18
### solver log, setup time:  2.00781E-02, solve time:  2.18500E-03, relative residual:  7.71683E-18
### solver log, setup time:  2.02465E-02, solve time:  3.04040E-03, relative residual:  7.75811E-18
### solver log, setup time:  1.91854E-02, solve time:  2.14330E-03, relative residual:  8.37232E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      43, total time:  4.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79270E-02, solve time:  2.23940E-03, relative residual:  8.16453E-18
### solver log, setup time:  1.76097E-02, solve time:  2.39680E-03, relative residual:  7.72285E-18
### solver log, setup time:  1.77886E-02, solve time:  2.21160E-03, relative residual:  8.05946E-18
### solver log, setup time:  1.83380E-02, solve time:  2.20410E-03, relative residual:  7.56927E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      44, total time:  4.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82704E-02, solve time:  2.35450E-03, relative residual:  8.19216E-18
### solver log, setup time:  1.79269E-02, solve time:  2.46640E-03, relative residual:  8.72512E-18
### solver log, setup time:  2.41827E-02, solve time:  2.18110E-03, relative residual:  7.98502E-18
### solver log, setup time:  1.78981E-02, solve time:  2.29990E-03, relative residual:  9.11108E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      45, total time:  4.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.02830E-02, solve time:  2.44260E-03, relative residual:  8.89117E-18
### solver log, setup time:  2.11223E-02, solve time:  2.54800E-03, relative residual:  8.01608E-18
### solver log, setup time:  1.80903E-02, solve time:  2.83310E-03, relative residual:  8.12091E-18
### solver log, setup time:  2.36140E-02, solve time:  2.47980E-03, relative residual:  7.90501E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      46, total time:  4.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90901E-02, solve time:  2.41650E-03, relative residual:  8.63197E-18
### solver log, setup time:  1.92415E-02, solve time:  2.15550E-03, relative residual:  8.12624E-18
### solver log, setup time:  2.08252E-02, solve time:  2.48410E-03, relative residual:  7.78277E-18
### solver log, setup time:  2.17503E-02, solve time:  2.26760E-03, relative residual:  8.62609E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      47, total time:  4.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.11722E-02, solve time:  2.25490E-03, relative residual:  7.73083E-18
### solver log, setup time:  1.90998E-02, solve time:  2.22540E-03, relative residual:  8.58880E-18
### solver log, setup time:  1.73655E-02, solve time:  2.41840E-03, relative residual:  8.24697E-18
### solver log, setup time:  2.51576E-02, solve time:  6.43110E-03, relative residual:  8.64958E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      48, total time:  4.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80629E-02, solve time:  2.55680E-03, relative residual:  8.26287E-18
### solver log, setup time:  2.11173E-02, solve time:  1.97920E-03, relative residual:  9.05284E-18
### solver log, setup time:  1.76993E-02, solve time:  2.10060E-03, relative residual:  8.76862E-18
### solver log, setup time:  1.76543E-02, solve time:  2.22410E-03, relative residual:  8.99544E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      49, total time:  4.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83316E-02, solve time:  2.28940E-03, relative residual:  9.25160E-18
### solver log, setup time:  2.02291E-02, solve time:  2.95600E-03, relative residual:  8.95784E-18
### solver log, setup time:  1.82152E-02, solve time:  2.26660E-03, relative residual:  9.13238E-18
### solver log, setup time:  2.51110E-02, solve time:  1.95370E-03, relative residual:  8.34956E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      50, total time:  5.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.23977E-02, solve time:  2.51120E-03, relative residual:  8.31247E-18
### solver log, setup time:  1.91661E-02, solve time:  2.42600E-03, relative residual:  8.60490E-18
### solver log, setup time:  2.29499E-02, solve time:  2.50250E-03, relative residual:  8.61332E-18
### solver log, setup time:  1.92983E-02, solve time:  2.54380E-03, relative residual:  9.04801E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      51, total time:  5.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.02767E-02, solve time:  2.41160E-03, relative residual:  8.75313E-18
### solver log, setup time:  2.41549E-02, solve time:  2.26540E-03, relative residual:  9.00503E-18
### solver log, setup time:  2.92691E-02, solve time:  2.61810E-03, relative residual:  9.09287E-18
### solver log, setup time:  2.21760E-02, solve time:  3.28570E-03, relative residual:  9.57628E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      52, total time:  5.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.94207E-02, solve time:  2.43660E-03, relative residual:  8.74669E-18
### solver log, setup time:  2.56769E-02, solve time:  3.51970E-03, relative residual:  8.30366E-18
### solver log, setup time:  2.05718E-02, solve time:  3.07600E-03, relative residual:  8.45272E-18
### solver log, setup time:  2.25219E-02, solve time:  2.45390E-03, relative residual:  8.57990E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      53, total time:  5.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.91200E-02, solve time:  2.33100E-03, relative residual:  8.35741E-18
### solver log, setup time:  2.07416E-02, solve time:  2.25940E-03, relative residual:  9.31418E-18
### solver log, setup time:  1.95329E-02, solve time:  2.40400E-03, relative residual:  8.63305E-18
### solver log, setup time:  1.92739E-02, solve time:  2.31940E-03, relative residual:  8.55070E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      54, total time:  5.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92735E-02, solve time:  2.20400E-03, relative residual:  8.92172E-18
### solver log, setup time:  1.88500E-02, solve time:  2.20880E-03, relative residual:  9.04617E-18
### solver log, setup time:  1.74787E-02, solve time:  3.14160E-03, relative residual:  9.58101E-18
### solver log, setup time:  1.74158E-02, solve time:  2.39990E-03, relative residual:  9.80870E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      55, total time:  5.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.77731E-02, solve time:  2.31480E-03, relative residual:  9.79316E-18
### solver log, setup time:  1.83560E-02, solve time:  2.44770E-03, relative residual:  9.53973E-18
### solver log, setup time:  1.81932E-02, solve time:  2.52540E-03, relative residual:  8.96537E-18
### solver log, setup time:  1.76412E-02, solve time:  2.43160E-03, relative residual:  7.98033E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      56, total time:  5.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.70382E-02, solve time:  2.55180E-03, relative residual:  9.22956E-18
### solver log, setup time:  1.92624E-02, solve time:  2.38430E-03, relative residual:  8.74196E-18
### solver log, setup time:  1.77743E-02, solve time:  2.29880E-03, relative residual:  8.23694E-18
### solver log, setup time:  1.84294E-02, solve time:  2.50600E-03, relative residual:  9.06231E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      57, total time:  5.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95501E-02, solve time:  2.24030E-03, relative residual:  8.69372E-18
### solver log, setup time:  1.81984E-02, solve time:  2.41190E-03, relative residual:  9.74610E-18
### solver log, setup time:  1.81225E-02, solve time:  3.08180E-03, relative residual:  8.61080E-18
### solver log, setup time:  1.89158E-02, solve time:  2.22430E-03, relative residual:  9.28169E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      58, total time:  5.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92286E-02, solve time:  2.09390E-03, relative residual:  9.48137E-18
### solver log, setup time:  1.76767E-02, solve time:  2.47330E-03, relative residual:  9.79221E-18
### solver log, setup time:  1.76180E-02, solve time:  2.44270E-03, relative residual:  9.15102E-18
### solver log, setup time:  2.07127E-02, solve time:  2.47880E-03, relative residual:  9.66874E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      59, total time:  5.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92048E-02, solve time:  2.21160E-03, relative residual:  9.59988E-18
### solver log, setup time:  1.78590E-02, solve time:  2.54720E-03, relative residual:  9.98861E-18
### solver log, setup time:  2.00508E-02, solve time:  2.50110E-03, relative residual:  8.51689E-18
### solver log, setup time:  1.67310E-02, solve time:  2.50250E-03, relative residual:  9.27639E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      60, total time:  6.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.91096E-02, solve time:  2.34970E-03, relative residual:  9.54183E-18
### solver log, setup time:  1.80005E-02, solve time:  2.94310E-03, relative residual:  9.85372E-18
### solver log, setup time:  1.81694E-02, solve time:  3.01840E-03, relative residual:  9.19969E-18
### solver log, setup time:  1.84752E-02, solve time:  2.75180E-03, relative residual:  9.23855E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      61, total time:  6.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.81811E-02, solve time:  2.13030E-03, relative residual:  9.75390E-18
### solver log, setup time:  1.74041E-02, solve time:  2.04810E-03, relative residual:  1.00800E-17
### solver log, setup time:  1.92491E-02, solve time:  2.08010E-03, relative residual:  9.89524E-18
### solver log, setup time:  1.88447E-02, solve time:  2.28170E-03, relative residual:  9.01637E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      62, total time:  6.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86111E-02, solve time:  2.35680E-03, relative residual:  1.00286E-17
### solver log, setup time:  1.81812E-02, solve time:  2.82560E-03, relative residual:  9.27864E-18
### solver log, setup time:  1.92740E-02, solve time:  2.20410E-03, relative residual:  9.81716E-18
### solver log, setup time:  1.88303E-02, solve time:  2.40960E-03, relative residual:  9.39162E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      63, total time:  6.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.01942E-02, solve time:  2.35540E-03, relative residual:  9.69669E-18
### solver log, setup time:  1.72213E-02, solve time:  3.09150E-03, relative residual:  9.00572E-18
### solver log, setup time:  1.78608E-02, solve time:  2.47420E-03, relative residual:  9.78492E-18
### solver log, setup time:  1.84272E-02, solve time:  2.37060E-03, relative residual:  9.27077E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      64, total time:  6.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.88087E-02, solve time:  2.27500E-03, relative residual:  1.01841E-17
### solver log, setup time:  1.82178E-02, solve time:  2.18830E-03, relative residual:  1.08032E-17
### solver log, setup time:  2.50407E-02, solve time:  2.54730E-03, relative residual:  1.02317E-17
### solver log, setup time:  1.83319E-02, solve time:  2.76630E-03, relative residual:  1.00615E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      65, total time:  6.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90374E-02, solve time:  2.61450E-03, relative residual:  9.41919E-18
### solver log, setup time:  1.72402E-02, solve time:  2.58450E-03, relative residual:  9.68137E-18
### solver log, setup time:  1.83581E-02, solve time:  2.40890E-03, relative residual:  1.04516E-17
### solver log, setup time:  1.79967E-02, solve time:  2.62230E-03, relative residual:  9.79127E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      66, total time:  6.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.88615E-02, solve time:  2.35170E-03, relative residual:  1.06045E-17
### solver log, setup time:  1.81815E-02, solve time:  2.10210E-03, relative residual:  1.01729E-17
### solver log, setup time:  1.76956E-02, solve time:  2.73060E-03, relative residual:  9.74478E-18
### solver log, setup time:  1.72947E-02, solve time:  2.63560E-03, relative residual:  1.02987E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      67, total time:  6.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90080E-02, solve time:  2.19200E-03, relative residual:  1.02164E-17
### solver log, setup time:  1.74149E-02, solve time:  2.17290E-03, relative residual:  1.01490E-17
### solver log, setup time:  1.96888E-02, solve time:  2.31710E-03, relative residual:  9.98336E-18
### solver log, setup time:  1.72592E-02, solve time:  2.08070E-03, relative residual:  9.47788E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      68, total time:  6.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.77190E-02, solve time:  1.84920E-03, relative residual:  9.23497E-18
### solver log, setup time:  1.79059E-02, solve time:  2.26740E-03, relative residual:  1.01591E-17
### solver log, setup time:  1.90740E-02, solve time:  2.09900E-03, relative residual:  9.71546E-18
### solver log, setup time:  1.92004E-02, solve time:  2.07600E-03, relative residual:  9.73340E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      69, total time:  6.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.72818E-02, solve time:  2.47890E-03, relative residual:  9.88813E-18
### solver log, setup time:  1.89048E-02, solve time:  2.36530E-03, relative residual:  9.92958E-18
### solver log, setup time:  1.78269E-02, solve time:  2.19730E-03, relative residual:  8.86402E-18
### solver log, setup time:  1.67091E-02, solve time:  2.21040E-03, relative residual:  1.04960E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      70, total time:  7.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.84817E-02, solve time:  2.19840E-03, relative residual:  1.02566E-17
### solver log, setup time:  1.87653E-02, solve time:  2.25740E-03, relative residual:  9.75337E-18
### solver log, setup time:  1.91583E-02, solve time:  2.26340E-03, relative residual:  1.04165E-17
### solver log, setup time:  2.10244E-02, solve time:  2.50710E-03, relative residual:  9.35567E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      71, total time:  7.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.98590E-02, solve time:  2.56910E-03, relative residual:  9.75580E-18
### solver log, setup time:  1.99370E-02, solve time:  2.23960E-03, relative residual:  9.85745E-18
### solver log, setup time:  1.97011E-02, solve time:  2.81670E-03, relative residual:  9.65611E-18
### solver log, setup time:  1.75836E-02, solve time:  2.35790E-03, relative residual:  9.68441E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      72, total time:  7.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78201E-02, solve time:  2.84500E-03, relative residual:  1.04738E-17
### solver log, setup time:  1.91174E-02, solve time:  2.19010E-03, relative residual:  9.74430E-18
### solver log, setup time:  2.05869E-02, solve time:  2.00890E-03, relative residual:  1.10612E-17
### solver log, setup time:  2.03575E-02, solve time:  2.61480E-03, relative residual:  9.99480E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      73, total time:  7.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.08732E-02, solve time:  2.13650E-03, relative residual:  1.01350E-17
### solver log, setup time:  2.08749E-02, solve time:  2.32090E-03, relative residual:  1.04916E-17
### solver log, setup time:  1.75731E-02, solve time:  2.98240E-03, relative residual:  1.00942E-17
### solver log, setup time:  1.76003E-02, solve time:  2.47460E-03, relative residual:  1.04889E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      74, total time:  7.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.77413E-02, solve time:  2.16210E-03, relative residual:  1.06766E-17
### solver log, setup time:  1.75510E-02, solve time:  2.27830E-03, relative residual:  1.04321E-17
### solver log, setup time:  1.75877E-02, solve time:  2.65240E-03, relative residual:  1.11121E-17
### solver log, setup time:  1.76767E-02, solve time:  2.30820E-03, relative residual:  9.86394E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      75, total time:  7.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.89779E-02, solve time:  2.51140E-03, relative residual:  1.04146E-17
### solver log, setup time:  1.64518E-02, solve time:  2.51950E-03, relative residual:  9.89526E-18
### solver log, setup time:  1.77921E-02, solve time:  2.71480E-03, relative residual:  9.74694E-18
### solver log, setup time:  1.70193E-02, solve time:  2.51450E-03, relative residual:  9.99795E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      76, total time:  7.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.94063E-02, solve time:  1.93840E-03, relative residual:  1.05211E-17
### solver log, setup time:  1.75113E-02, solve time:  2.55040E-03, relative residual:  1.15896E-17
### solver log, setup time:  2.06976E-02, solve time:  3.08830E-03, relative residual:  1.13245E-17
### solver log, setup time:  1.71878E-02, solve time:  2.59870E-03, relative residual:  1.01216E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      77, total time:  7.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78760E-02, solve time:  2.45140E-03, relative residual:  1.03257E-17
### solver log, setup time:  1.86980E-02, solve time:  2.46670E-03, relative residual:  9.91072E-18
### solver log, setup time:  1.71972E-02, solve time:  2.22940E-03, relative residual:  9.77085E-18
### solver log, setup time:  1.83623E-02, solve time:  2.30240E-03, relative residual:  1.13546E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      78, total time:  7.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.77051E-02, solve time:  2.67130E-03, relative residual:  9.89371E-18
### solver log, setup time:  1.91866E-02, solve time:  2.22660E-03, relative residual:  1.04431E-17
### solver log, setup time:  1.75413E-02, solve time:  2.36690E-03, relative residual:  1.02758E-17
### solver log, setup time:  1.75445E-02, solve time:  2.37200E-03, relative residual:  1.04081E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      79, total time:  7.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.99228E-02, solve time:  2.35800E-03, relative residual:  1.11396E-17
### solver log, setup time:  1.92247E-02, solve time:  2.13580E-03, relative residual:  1.06723E-17
### solver log, setup time:  1.93860E-02, solve time:  2.54350E-03, relative residual:  1.08937E-17
### solver log, setup time:  1.78749E-02, solve time:  2.25910E-03, relative residual:  1.02676E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      80, total time:  8.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.77757E-02, solve time:  2.45060E-03, relative residual:  1.09736E-17
### solver log, setup time:  2.06224E-02, solve time:  1.97220E-03, relative residual:  1.02492E-17
### solver log, setup time:  1.74175E-02, solve time:  2.16570E-03, relative residual:  1.10494E-17
### solver log, setup time:  1.92537E-02, solve time:  2.14520E-03, relative residual:  9.88048E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      81, total time:  8.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.73240E-02, solve time:  2.45880E-03, relative residual:  1.09648E-17
### solver log, setup time:  1.74368E-02, solve time:  2.62490E-03, relative residual:  1.10456E-17
### solver log, setup time:  1.77097E-02, solve time:  2.37800E-03, relative residual:  1.13425E-17
### solver log, setup time:  1.77651E-02, solve time:  2.89260E-03, relative residual:  1.03093E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      82, total time:  8.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.68077E-02, solve time:  2.78290E-03, relative residual:  1.19349E-17
### solver log, setup time:  2.00996E-02, solve time:  2.61320E-03, relative residual:  1.11619E-17
### solver log, setup time:  2.32606E-02, solve time:  2.39840E-03, relative residual:  1.04780E-17
### solver log, setup time:  1.73646E-02, solve time:  2.74870E-03, relative residual:  1.16179E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      83, total time:  8.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86266E-02, solve time:  2.94510E-03, relative residual:  1.15972E-17
### solver log, setup time:  1.88815E-02, solve time:  2.08340E-03, relative residual:  1.05199E-17
### solver log, setup time:  1.86210E-02, solve time:  2.46320E-03, relative residual:  1.05367E-17
### solver log, setup time:  2.03198E-02, solve time:  2.12690E-03, relative residual:  1.09300E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      84, total time:  8.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.62139E-02, solve time:  2.33000E-03, relative residual:  1.16041E-17
### solver log, setup time:  1.86285E-02, solve time:  2.26380E-03, relative residual:  1.12756E-17
### solver log, setup time:  1.82172E-02, solve time:  2.10630E-03, relative residual:  1.10605E-17
### solver log, setup time:  1.82092E-02, solve time:  2.05260E-03, relative residual:  1.13379E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      85, total time:  8.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.75720E-02, solve time:  2.50490E-03, relative residual:  1.16849E-17
### solver log, setup time:  1.78501E-02, solve time:  2.21670E-03, relative residual:  1.15763E-17
### solver log, setup time:  2.04846E-02, solve time:  2.30190E-03, relative residual:  1.14014E-17
### solver log, setup time:  1.89539E-02, solve time:  2.31110E-03, relative residual:  1.12846E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      86, total time:  8.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.74192E-02, solve time:  2.11830E-03, relative residual:  1.07326E-17
### solver log, setup time:  1.97709E-02, solve time:  2.15560E-03, relative residual:  1.16333E-17
### solver log, setup time:  1.82122E-02, solve time:  1.93000E-03, relative residual:  1.18553E-17
### solver log, setup time:  1.78016E-02, solve time:  2.28610E-03, relative residual:  1.14918E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      87, total time:  8.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80114E-02, solve time:  2.79950E-03, relative residual:  1.03519E-17
### solver log, setup time:  1.72283E-02, solve time:  2.08780E-03, relative residual:  1.10552E-17
### solver log, setup time:  1.98100E-02, solve time:  2.16840E-03, relative residual:  1.11828E-17
### solver log, setup time:  2.07377E-02, solve time:  2.18830E-03, relative residual:  1.16925E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      88, total time:  8.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83985E-02, solve time:  2.31230E-03, relative residual:  1.14209E-17
### solver log, setup time:  1.73096E-02, solve time:  2.11880E-03, relative residual:  1.07753E-17
### solver log, setup time:  1.74164E-02, solve time:  1.99950E-03, relative residual:  1.12263E-17
### solver log, setup time:  2.04455E-02, solve time:  2.72810E-03, relative residual:  1.25434E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      89, total time:  8.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.79988E-02, solve time:  2.36960E-03, relative residual:  1.16627E-17
### solver log, setup time:  2.07385E-02, solve time:  2.44470E-03, relative residual:  1.12654E-17
### solver log, setup time:  1.72396E-02, solve time:  2.27000E-03, relative residual:  1.13682E-17
### solver log, setup time:  1.92846E-02, solve time:  1.97770E-03, relative residual:  1.10131E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      90, total time:  9.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.73949E-02, solve time:  2.53660E-03, relative residual:  1.20666E-17
### solver log, setup time:  1.72100E-02, solve time:  2.14130E-03, relative residual:  1.11172E-17
### solver log, setup time:  1.88673E-02, solve time:  2.09850E-03, relative residual:  1.16356E-17
### solver log, setup time:  1.76439E-02, solve time:  2.10570E-03, relative residual:  1.08223E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      91, total time:  9.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90258E-02, solve time:  2.21170E-03, relative residual:  1.10697E-17
### solver log, setup time:  2.15050E-02, solve time:  3.06630E-03, relative residual:  1.26955E-17
### solver log, setup time:  1.74203E-02, solve time:  2.24030E-03, relative residual:  1.14352E-17
### solver log, setup time:  1.90504E-02, solve time:  2.13560E-03, relative residual:  1.15028E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      92, total time:  9.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.75371E-02, solve time:  2.33260E-03, relative residual:  1.20795E-17
### solver log, setup time:  1.75552E-02, solve time:  2.31050E-03, relative residual:  1.09760E-17
### solver log, setup time:  1.77682E-02, solve time:  2.13360E-03, relative residual:  1.22041E-17
### solver log, setup time:  1.90547E-02, solve time:  2.40350E-03, relative residual:  1.23723E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      93, total time:  9.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80259E-02, solve time:  2.59750E-03, relative residual:  1.04152E-17
### solver log, setup time:  1.75927E-02, solve time:  2.08790E-03, relative residual:  1.20409E-17
### solver log, setup time:  1.90066E-02, solve time:  2.34020E-03, relative residual:  1.12864E-17
### solver log, setup time:  1.76010E-02, solve time:  2.43960E-03, relative residual:  1.10884E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      94, total time:  9.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  3.57037E-02, solve time:  2.68330E-03, relative residual:  1.25937E-17
### solver log, setup time:  1.94814E-02, solve time:  2.14390E-03, relative residual:  1.15778E-17
### solver log, setup time:  1.78162E-02, solve time:  2.05740E-03, relative residual:  1.10095E-17
### solver log, setup time:  1.81170E-02, solve time:  2.12010E-03, relative residual:  1.15794E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      95, total time:  9.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.76581E-02, solve time:  2.37670E-03, relative residual:  1.21373E-17
### solver log, setup time:  1.91124E-02, solve time:  2.09480E-03, relative residual:  1.06361E-17
### solver log, setup time:  1.84229E-02, solve time:  2.51070E-03, relative residual:  1.16595E-17
### solver log, setup time:  1.88420E-02, solve time:  2.13110E-03, relative residual:  1.16072E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      96, total time:  9.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.95822E-02, solve time:  2.49700E-03, relative residual:  1.16711E-17
### solver log, setup time:  1.66289E-02, solve time:  2.12620E-03, relative residual:  1.19344E-17
### solver log, setup time:  1.79285E-02, solve time:  2.29950E-03, relative residual:  1.31970E-17
### solver log, setup time:  1.76564E-02, solve time:  2.22380E-03, relative residual:  1.22972E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      97, total time:  9.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.74833E-02, solve time:  2.21330E-03, relative residual:  1.16356E-17
### solver log, setup time:  1.80624E-02, solve time:  2.62220E-03, relative residual:  1.33378E-17
### solver log, setup time:  1.74726E-02, solve time:  2.24940E-03, relative residual:  1.13557E-17
### solver log, setup time:  1.99629E-02, solve time:  2.04300E-03, relative residual:  1.18506E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      98, total time:  9.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82022E-02, solve time:  2.08890E-03, relative residual:  1.20516E-17
### solver log, setup time:  1.86543E-02, solve time:  2.03720E-03, relative residual:  1.23593E-17
### solver log, setup time:  1.73988E-02, solve time:  2.13080E-03, relative residual:  1.13000E-17
### solver log, setup time:  1.61060E-02, solve time:  2.29560E-03, relative residual:  1.20599E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      99, total time:  9.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90325E-02, solve time:  1.96700E-03, relative residual:  1.21208E-17
### solver log, setup time:  1.86097E-02, solve time:  2.44080E-03, relative residual:  1.16416E-17
### solver log, setup time:  1.71882E-02, solve time:  2.30660E-03, relative residual:  1.22478E-17
### solver log, setup time:  1.75640E-02, solve time:  2.41950E-03, relative residual:  1.25207E-17
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :     100, total time:  1.00000E+00, delta t:  1.00000E-02
### solver log, setup time:  1.78151E-02, solve time:  2.36660E-03, relative residual:  1.14282E-17
### solver log, setup time:  1.73501E-02, solve time:  2.11240E-03, relative residual:  1.16335E-17
### solver log, setup time:  1.81318E-02, solve time:  2.32890E-03, relative residual:  1.20341E-17
### solver log, setup time:  1.91516E-02, solve time:  1.93860E-03, relative residual:  1.15206E-17
  !!! CONVERGENCE ACHIEVED 
 ====================================
    TOTAL TIME (sec) :    190.93
           pre (sec) :      0.08
         solve (sec) :    190.84
 ====================================



 :========================================:
 :**            END of FSTR             **:
 :========================================:
