 :========================================:
 :**   BEGIN FSTR Structural Analysis   **:
 :========================================:
         Total no. of processors:            1



  *    STAGE Initialization and input   **



  ***   STAGE Heat analysis    **
 =============================
   H E A T   T R A N S F E R  
 =============================
* Current step / Total step:        1/       1
* max iteration at each step:      100
* Transient anslysis
 ** Increment No. :       1, total time:  1.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  3.30716E-02, solve time:  2.44410E-03, relative residual:  5.57933E-18
### solver log, setup time:  3.60891E-02, solve time:  6.56760E-03, relative residual:  5.59072E-18
### solver log, setup time:  1.94890E-02, solve time:  2.25240E-03, relative residual:  5.47763E-18
### solver log, setup time:  1.95325E-02, solve time:  2.11330E-03, relative residual:  5.62419E-18
### solver log, setup time:  2.16345E-02, solve time:  2.53010E-03, relative residual:  5.57908E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       2, total time:  2.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  2.14974E-02, solve time:  2.35520E-03, relative residual:  5.27023E-18
### solver log, setup time:  2.41456E-02, solve time:  2.63600E-03, relative residual:  4.97880E-18
### solver log, setup time:  2.01432E-02, solve time:  2.56700E-03, relative residual:  6.03385E-18
### solver log, setup time:  1.98320E-02, solve time:  1.98050E-03, relative residual:  4.87172E-18
### solver log, setup time:  2.03911E-02, solve time:  2.17370E-03, relative residual:  5.17596E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       3, total time:  3.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.85954E-02, solve time:  2.10310E-03, relative residual:  4.92090E-18
### solver log, setup time:  1.98660E-02, solve time:  2.23680E-03, relative residual:  5.17564E-18
### solver log, setup time:  2.01393E-02, solve time:  1.98650E-03, relative residual:  5.08688E-18
### solver log, setup time:  1.80096E-02, solve time:  2.04950E-03, relative residual:  5.27971E-18
### solver log, setup time:  1.89144E-02, solve time:  2.17070E-03, relative residual:  5.65474E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       4, total time:  4.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.96854E-02, solve time:  2.22740E-03, relative residual:  4.86100E-18
### solver log, setup time:  2.63498E-02, solve time:  2.05300E-03, relative residual:  4.98222E-18
### solver log, setup time:  2.28437E-02, solve time:  2.79030E-03, relative residual:  5.05561E-18
### solver log, setup time:  1.95601E-02, solve time:  2.40990E-03, relative residual:  5.00976E-18
### solver log, setup time:  7.05396E-02, solve time:  2.07340E-03, relative residual:  5.24052E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       5, total time:  5.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.95104E-02, solve time:  2.30170E-03, relative residual:  5.09597E-18
### solver log, setup time:  7.49992E-02, solve time:  2.75080E-03, relative residual:  4.95800E-18
### solver log, setup time:  1.72465E-02, solve time:  2.23420E-03, relative residual:  5.28527E-18
### solver log, setup time:  1.87090E-02, solve time:  2.09450E-03, relative residual:  4.86779E-18
### solver log, setup time:  1.80660E-02, solve time:  2.00540E-03, relative residual:  5.25108E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       6, total time:  6.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.98551E-02, solve time:  2.29750E-03, relative residual:  4.69040E-18
### solver log, setup time:  2.04446E-02, solve time:  2.29770E-03, relative residual:  4.90306E-18
### solver log, setup time:  1.61313E-02, solve time:  2.12820E-03, relative residual:  4.74908E-18
### solver log, setup time:  1.75080E-02, solve time:  2.39820E-03, relative residual:  4.67340E-18
### solver log, setup time:  1.74144E-02, solve time:  2.23850E-03, relative residual:  4.95274E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       7, total time:  7.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.68175E-02, solve time:  2.39680E-03, relative residual:  4.80898E-18
### solver log, setup time:  1.74829E-02, solve time:  2.25700E-03, relative residual:  5.05502E-18
### solver log, setup time:  1.68085E-02, solve time:  2.13850E-03, relative residual:  4.72617E-18
### solver log, setup time:  1.77182E-02, solve time:  2.34340E-03, relative residual:  4.70433E-18
### solver log, setup time:  2.00151E-02, solve time:  1.97980E-03, relative residual:  4.77502E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       8, total time:  8.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.78486E-02, solve time:  2.16990E-03, relative residual:  4.53186E-18
### solver log, setup time:  1.72572E-02, solve time:  2.30390E-03, relative residual:  4.49611E-18
### solver log, setup time:  1.75393E-02, solve time:  2.40640E-03, relative residual:  4.39086E-18
### solver log, setup time:  1.75154E-02, solve time:  2.22190E-03, relative residual:  5.00016E-18
### solver log, setup time:  1.76281E-02, solve time:  4.06910E-03, relative residual:  4.54335E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :       9, total time:  9.00000E-02, delta t:  1.00000E-02
### solver log, setup time:  1.84036E-02, solve time:  2.12100E-03, relative residual:  4.57988E-18
### solver log, setup time:  1.76722E-02, solve time:  2.42550E-03, relative residual:  4.76355E-18
### solver log, setup time:  1.76115E-02, solve time:  2.18980E-03, relative residual:  4.24460E-18
### solver log, setup time:  1.78110E-02, solve time:  2.07980E-03, relative residual:  4.62919E-18
### solver log, setup time:  1.76306E-02, solve time:  2.22010E-03, relative residual:  4.49319E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      10, total time:  1.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.76502E-02, solve time:  2.49560E-03, relative residual:  4.72151E-18
### solver log, setup time:  1.77587E-02, solve time:  2.36740E-03, relative residual:  4.51896E-18
### solver log, setup time:  1.76627E-02, solve time:  2.58300E-03, relative residual:  4.86649E-18
### solver log, setup time:  1.79242E-02, solve time:  2.33540E-03, relative residual:  4.49156E-18
### solver log, setup time:  1.65048E-02, solve time:  2.54420E-03, relative residual:  4.50322E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      11, total time:  1.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.68027E-02, solve time:  2.04630E-03, relative residual:  4.21365E-18
### solver log, setup time:  1.78132E-02, solve time:  2.06300E-03, relative residual:  4.50060E-18
### solver log, setup time:  1.80709E-02, solve time:  2.61030E-03, relative residual:  4.48186E-18
### solver log, setup time:  1.84983E-02, solve time:  2.35160E-03, relative residual:  4.27824E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      12, total time:  1.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.75693E-02, solve time:  2.36010E-03, relative residual:  4.30336E-18
### solver log, setup time:  1.95070E-02, solve time:  2.44100E-03, relative residual:  4.15711E-18
### solver log, setup time:  1.76859E-02, solve time:  2.01130E-03, relative residual:  4.28150E-18
### solver log, setup time:  1.92828E-02, solve time:  2.08630E-03, relative residual:  4.52148E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      13, total time:  1.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  4.57184E-02, solve time:  3.50250E-03, relative residual:  4.33640E-18
### solver log, setup time:  2.58965E-02, solve time:  2.70200E-03, relative residual:  4.18092E-18
### solver log, setup time:  2.17450E-02, solve time:  2.48180E-03, relative residual:  4.26955E-18
### solver log, setup time:  5.86475E-02, solve time:  3.95900E-03, relative residual:  4.04572E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      14, total time:  1.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.26906E-02, solve time:  2.98330E-03, relative residual:  4.24929E-18
### solver log, setup time:  1.93515E-02, solve time:  5.77680E-03, relative residual:  4.20890E-18
### solver log, setup time:  1.83952E-02, solve time:  2.17150E-03, relative residual:  4.06636E-18
### solver log, setup time:  2.13115E-02, solve time:  2.63880E-03, relative residual:  3.97740E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      15, total time:  1.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.98613E-02, solve time:  1.83930E-03, relative residual:  4.42274E-18
### solver log, setup time:  2.14679E-02, solve time:  2.57780E-03, relative residual:  4.34734E-18
### solver log, setup time:  2.19960E-02, solve time:  2.85350E-03, relative residual:  4.20156E-18
### solver log, setup time:  1.93937E-02, solve time:  2.34490E-03, relative residual:  4.28318E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      16, total time:  1.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.45453E-02, solve time:  3.31340E-03, relative residual:  4.20832E-18
### solver log, setup time:  2.21779E-02, solve time:  3.16490E-03, relative residual:  4.53159E-18
### solver log, setup time:  1.87455E-02, solve time:  2.71450E-03, relative residual:  4.34112E-18
### solver log, setup time:  2.61388E-02, solve time:  3.03840E-03, relative residual:  4.26467E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      17, total time:  1.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.02834E-02, solve time:  2.22800E-03, relative residual:  4.11979E-18
### solver log, setup time:  1.96550E-02, solve time:  1.97250E-03, relative residual:  3.97777E-18
### solver log, setup time:  1.93667E-02, solve time:  1.99480E-03, relative residual:  3.99872E-18
### solver log, setup time:  2.42938E-02, solve time:  2.11180E-03, relative residual:  3.87657E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      18, total time:  1.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78727E-02, solve time:  2.49170E-03, relative residual:  4.25364E-18
### solver log, setup time:  1.78645E-02, solve time:  2.62350E-03, relative residual:  4.13670E-18
### solver log, setup time:  1.86009E-02, solve time:  2.90120E-03, relative residual:  3.99461E-18
### solver log, setup time:  1.78949E-02, solve time:  2.31590E-03, relative residual:  4.11745E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      19, total time:  1.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.04327E-02, solve time:  2.71430E-03, relative residual:  4.06923E-18
### solver log, setup time:  2.08351E-02, solve time:  2.05690E-03, relative residual:  4.27542E-18
### solver log, setup time:  1.79065E-02, solve time:  1.96140E-03, relative residual:  4.28419E-18
### solver log, setup time:  1.78553E-02, solve time:  2.49930E-03, relative residual:  4.06742E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      20, total time:  2.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.83467E-02, solve time:  2.16990E-03, relative residual:  4.03964E-18
### solver log, setup time:  1.99899E-02, solve time:  2.40940E-03, relative residual:  3.96637E-18
### solver log, setup time:  2.00786E-02, solve time:  2.58370E-03, relative residual:  4.10846E-18
### solver log, setup time:  1.78839E-02, solve time:  2.44070E-03, relative residual:  4.08793E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      21, total time:  2.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.12762E-02, solve time:  2.58190E-03, relative residual:  3.90174E-18
### solver log, setup time:  1.81745E-02, solve time:  2.05790E-03, relative residual:  3.92389E-18
### solver log, setup time:  2.09001E-02, solve time:  2.06670E-03, relative residual:  3.91029E-18
### solver log, setup time:  2.06278E-02, solve time:  2.30880E-03, relative residual:  3.97497E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      22, total time:  2.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.02500E-02, solve time:  2.08050E-03, relative residual:  4.41699E-18
### solver log, setup time:  2.13428E-02, solve time:  3.02710E-03, relative residual:  3.90114E-18
### solver log, setup time:  1.05697E-01, solve time:  5.11460E-03, relative residual:  4.16187E-18
### solver log, setup time:  2.27514E-02, solve time:  3.07150E-03, relative residual:  4.13623E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      23, total time:  2.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78755E-02, solve time:  2.04570E-03, relative residual:  3.71839E-18
### solver log, setup time:  1.66063E-02, solve time:  2.41710E-03, relative residual:  4.14695E-18
### solver log, setup time:  2.54386E-02, solve time:  3.03630E-03, relative residual:  3.90163E-18
### solver log, setup time:  3.35126E-02, solve time:  3.20730E-03, relative residual:  3.85362E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      24, total time:  2.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.47174E-02, solve time:  2.78630E-03, relative residual:  3.54219E-18
### solver log, setup time:  2.01483E-02, solve time:  2.13210E-03, relative residual:  3.69153E-18
### solver log, setup time:  1.93598E-02, solve time:  2.33540E-03, relative residual:  3.79999E-18
### solver log, setup time:  1.79470E-02, solve time:  2.17470E-03, relative residual:  3.92642E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      25, total time:  2.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.27319E-02, solve time:  2.13000E-03, relative residual:  3.95334E-18
### solver log, setup time:  2.08362E-02, solve time:  2.33460E-03, relative residual:  3.87901E-18
### solver log, setup time:  2.11649E-02, solve time:  2.81440E-03, relative residual:  3.88040E-18
### solver log, setup time:  2.28762E-02, solve time:  2.86010E-03, relative residual:  4.00684E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      26, total time:  2.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.03412E-02, solve time:  2.70540E-03, relative residual:  3.92562E-18
### solver log, setup time:  2.04715E-02, solve time:  2.09730E-03, relative residual:  4.08497E-18
### solver log, setup time:  1.92466E-02, solve time:  2.41210E-03, relative residual:  4.09875E-18
### solver log, setup time:  2.00128E-02, solve time:  2.40220E-03, relative residual:  3.91916E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      27, total time:  2.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.12414E-02, solve time:  2.03710E-03, relative residual:  4.09391E-18
### solver log, setup time:  1.79135E-02, solve time:  2.10280E-03, relative residual:  4.11410E-18
### solver log, setup time:  2.13065E-02, solve time:  2.81660E-03, relative residual:  3.84777E-18
### solver log, setup time:  1.76391E-02, solve time:  2.23460E-03, relative residual:  3.84940E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      28, total time:  2.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.74249E-02, solve time:  2.25640E-03, relative residual:  4.12463E-18
### solver log, setup time:  2.12575E-02, solve time:  1.90690E-03, relative residual:  3.80817E-18
### solver log, setup time:  1.76826E-02, solve time:  2.16520E-03, relative residual:  3.95709E-18
### solver log, setup time:  1.86971E-02, solve time:  1.96740E-03, relative residual:  4.16000E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      29, total time:  2.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78021E-02, solve time:  2.52720E-03, relative residual:  3.96331E-18
### solver log, setup time:  1.77868E-02, solve time:  2.22690E-03, relative residual:  3.77675E-18
### solver log, setup time:  1.84792E-02, solve time:  2.25100E-03, relative residual:  3.98778E-18
### solver log, setup time:  1.79481E-02, solve time:  2.35210E-03, relative residual:  3.97558E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      30, total time:  3.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.07569E-02, solve time:  2.19550E-03, relative residual:  3.84719E-18
### solver log, setup time:  1.92342E-02, solve time:  2.20800E-03, relative residual:  3.77050E-18
### solver log, setup time:  2.11167E-02, solve time:  2.00510E-03, relative residual:  4.23541E-18
### solver log, setup time:  1.75412E-02, solve time:  2.18630E-03, relative residual:  4.08713E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      31, total time:  3.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.76284E-02, solve time:  2.29900E-03, relative residual:  3.76864E-18
### solver log, setup time:  1.89230E-02, solve time:  2.16690E-03, relative residual:  4.20483E-18
### solver log, setup time:  1.93924E-02, solve time:  2.20490E-03, relative residual:  4.36208E-18
### solver log, setup time:  1.75906E-02, solve time:  2.18430E-03, relative residual:  3.99715E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      32, total time:  3.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.90521E-02, solve time:  2.14650E-03, relative residual:  3.96793E-18
### solver log, setup time:  1.92544E-02, solve time:  2.17990E-03, relative residual:  3.84047E-18
### solver log, setup time:  1.73304E-02, solve time:  2.19930E-03, relative residual:  4.16051E-18
### solver log, setup time:  2.10436E-02, solve time:  2.03510E-03, relative residual:  4.17355E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      33, total time:  3.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80799E-02, solve time:  2.30640E-03, relative residual:  4.05439E-18
### solver log, setup time:  1.89458E-02, solve time:  2.10490E-03, relative residual:  4.00186E-18
### solver log, setup time:  1.75799E-02, solve time:  2.21580E-03, relative residual:  4.00599E-18
### solver log, setup time:  1.76719E-02, solve time:  2.15510E-03, relative residual:  3.80613E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      34, total time:  3.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.84001E-02, solve time:  2.04040E-03, relative residual:  3.99133E-18
### solver log, setup time:  1.75745E-02, solve time:  2.08570E-03, relative residual:  3.92398E-18
### solver log, setup time:  1.66200E-02, solve time:  2.07060E-03, relative residual:  4.25863E-18
### solver log, setup time:  2.28523E-02, solve time:  2.21890E-03, relative residual:  4.01161E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      35, total time:  3.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.80819E-02, solve time:  2.72080E-03, relative residual:  3.88740E-18
### solver log, setup time:  1.87842E-02, solve time:  2.44850E-03, relative residual:  4.04215E-18
### solver log, setup time:  1.86455E-02, solve time:  2.07140E-03, relative residual:  4.07460E-18
### solver log, setup time:  2.44428E-02, solve time:  2.13460E-03, relative residual:  4.11258E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      36, total time:  3.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.13244E-02, solve time:  2.72510E-03, relative residual:  4.03779E-18
### solver log, setup time:  1.80211E-02, solve time:  2.17550E-03, relative residual:  4.07579E-18
### solver log, setup time:  1.96884E-02, solve time:  2.15700E-03, relative residual:  3.81459E-18
### solver log, setup time:  1.76911E-02, solve time:  2.38320E-03, relative residual:  3.88966E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      37, total time:  3.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82144E-02, solve time:  2.27910E-03, relative residual:  4.01601E-18
### solver log, setup time:  1.94631E-02, solve time:  1.96350E-03, relative residual:  4.03554E-18
### solver log, setup time:  1.85137E-02, solve time:  2.45230E-03, relative residual:  4.22610E-18
### solver log, setup time:  1.75776E-02, solve time:  2.34230E-03, relative residual:  4.00223E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      38, total time:  3.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  3.10998E-02, solve time:  2.40150E-03, relative residual:  3.85438E-18
### solver log, setup time:  2.59845E-02, solve time:  2.74450E-03, relative residual:  3.91011E-18
### solver log, setup time:  2.00126E-02, solve time:  2.20360E-03, relative residual:  4.09382E-18
### solver log, setup time:  2.67433E-02, solve time:  1.67920E-03, relative residual:  4.14066E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      39, total time:  3.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.09679E-02, solve time:  2.56270E-03, relative residual:  3.97234E-18
### solver log, setup time:  2.02786E-02, solve time:  2.62360E-03, relative residual:  4.02819E-18
### solver log, setup time:  1.91916E-02, solve time:  2.23260E-03, relative residual:  3.92575E-18
### solver log, setup time:  1.74845E-02, solve time:  2.19830E-03, relative residual:  3.78715E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      40, total time:  4.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.22059E-02, solve time:  2.44640E-03, relative residual:  3.98236E-18
### solver log, setup time:  1.98834E-02, solve time:  2.08960E-03, relative residual:  3.91363E-18
### solver log, setup time:  1.81962E-02, solve time:  2.78610E-03, relative residual:  4.05447E-18
### solver log, setup time:  2.01228E-02, solve time:  2.28600E-03, relative residual:  3.79165E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      41, total time:  4.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.00633E-02, solve time:  2.55180E-03, relative residual:  4.12651E-18
### solver log, setup time:  1.80387E-02, solve time:  2.03390E-03, relative residual:  3.86017E-18
### solver log, setup time:  1.85268E-02, solve time:  2.34930E-03, relative residual:  3.88626E-18
### solver log, setup time:  2.28119E-02, solve time:  2.67980E-03, relative residual:  3.96377E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      42, total time:  4.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.27776E-02, solve time:  2.42610E-03, relative residual:  3.98987E-18
### solver log, setup time:  2.19864E-02, solve time:  2.23400E-03, relative residual:  3.91862E-18
### solver log, setup time:  2.02748E-02, solve time:  2.58060E-03, relative residual:  3.92548E-18
### solver log, setup time:  2.42021E-02, solve time:  3.10900E-03, relative residual:  4.03298E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      43, total time:  4.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  3.16849E-02, solve time:  1.06987E-02, relative residual:  4.08629E-18
### solver log, setup time:  1.91453E-02, solve time:  2.06560E-03, relative residual:  4.21035E-18
### solver log, setup time:  2.78265E-02, solve time:  3.21200E-03, relative residual:  4.04061E-18
### solver log, setup time:  2.03931E-02, solve time:  2.37920E-03, relative residual:  4.25869E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      44, total time:  4.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.72517E-02, solve time:  2.16860E-03, relative residual:  4.24034E-18
### solver log, setup time:  2.54176E-02, solve time:  2.26890E-03, relative residual:  3.66002E-18
### solver log, setup time:  1.98436E-02, solve time:  2.54050E-03, relative residual:  4.43691E-18
### solver log, setup time:  2.30321E-02, solve time:  2.02830E-03, relative residual:  4.23780E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      45, total time:  4.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.41342E-02, solve time:  2.21620E-03, relative residual:  4.02975E-18
### solver log, setup time:  2.23882E-02, solve time:  2.39230E-03, relative residual:  4.12845E-18
### solver log, setup time:  1.79839E-02, solve time:  2.09950E-03, relative residual:  4.09901E-18
### solver log, setup time:  1.88483E-02, solve time:  2.41650E-03, relative residual:  3.97107E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      46, total time:  4.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.33739E-02, solve time:  3.86290E-03, relative residual:  4.01668E-18
### solver log, setup time:  1.89185E-02, solve time:  2.09340E-03, relative residual:  4.24200E-18
### solver log, setup time:  1.81762E-02, solve time:  2.19600E-03, relative residual:  4.22886E-18
### solver log, setup time:  1.94199E-02, solve time:  2.29270E-03, relative residual:  4.28932E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      47, total time:  4.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86060E-02, solve time:  2.21750E-03, relative residual:  4.66734E-18
### solver log, setup time:  1.91833E-02, solve time:  2.62110E-03, relative residual:  4.29705E-18
### solver log, setup time:  2.12625E-02, solve time:  2.47780E-03, relative residual:  4.43595E-18
### solver log, setup time:  1.78117E-02, solve time:  2.49440E-03, relative residual:  4.71882E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      48, total time:  4.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.00981E-02, solve time:  2.32950E-03, relative residual:  4.09279E-18
### solver log, setup time:  1.88792E-02, solve time:  2.57290E-03, relative residual:  4.52774E-18
### solver log, setup time:  2.19724E-02, solve time:  2.38830E-03, relative residual:  4.14722E-18
### solver log, setup time:  2.02985E-02, solve time:  3.25400E-03, relative residual:  4.15189E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      49, total time:  4.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.24922E-02, solve time:  3.26600E-03, relative residual:  4.23394E-18
### solver log, setup time:  1.87227E-02, solve time:  2.07960E-03, relative residual:  4.49211E-18
### solver log, setup time:  2.12407E-02, solve time:  2.40410E-03, relative residual:  4.23186E-18
### solver log, setup time:  2.43950E-02, solve time:  3.44250E-03, relative residual:  4.30371E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      50, total time:  5.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.17345E-02, solve time:  2.21680E-03, relative residual:  4.03448E-18
### solver log, setup time:  2.03272E-02, solve time:  3.41170E-03, relative residual:  4.33065E-18
### solver log, setup time:  2.10054E-02, solve time:  2.23510E-03, relative residual:  3.94124E-18
### solver log, setup time:  2.20102E-02, solve time:  2.31530E-03, relative residual:  4.22389E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      51, total time:  5.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.89505E-02, solve time:  2.50950E-03, relative residual:  3.96685E-18
### solver log, setup time:  1.96347E-02, solve time:  2.59510E-03, relative residual:  4.40107E-18
### solver log, setup time:  2.13209E-02, solve time:  3.24750E-03, relative residual:  4.01833E-18
### solver log, setup time:  1.84657E-02, solve time:  2.74180E-03, relative residual:  4.27888E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      52, total time:  5.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.91176E-02, solve time:  2.50740E-03, relative residual:  4.02835E-18
### solver log, setup time:  1.92775E-02, solve time:  2.09750E-03, relative residual:  4.35318E-18
### solver log, setup time:  1.75811E-02, solve time:  2.09070E-03, relative residual:  4.38794E-18
### solver log, setup time:  1.84964E-02, solve time:  2.24600E-03, relative residual:  4.34900E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      53, total time:  5.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.88985E-02, solve time:  2.22230E-03, relative residual:  4.09484E-18
### solver log, setup time:  1.75919E-02, solve time:  2.19940E-03, relative residual:  4.39320E-18
### solver log, setup time:  1.88609E-02, solve time:  2.52740E-03, relative residual:  4.07305E-18
### solver log, setup time:  1.76079E-02, solve time:  2.46580E-03, relative residual:  3.96161E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      54, total time:  5.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.76222E-02, solve time:  2.18010E-03, relative residual:  4.35439E-18
### solver log, setup time:  1.73520E-02, solve time:  2.02200E-03, relative residual:  4.38740E-18
### solver log, setup time:  1.76994E-02, solve time:  2.68450E-03, relative residual:  4.29911E-18
### solver log, setup time:  2.06866E-02, solve time:  2.18340E-03, relative residual:  4.23702E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      55, total time:  5.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.21335E-02, solve time:  2.29400E-03, relative residual:  4.46935E-18
### solver log, setup time:  1.92316E-02, solve time:  2.70100E-03, relative residual:  4.45815E-18
### solver log, setup time:  1.78128E-02, solve time:  2.42580E-03, relative residual:  4.67239E-18
### solver log, setup time:  2.15970E-02, solve time:  2.34750E-03, relative residual:  4.00377E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      56, total time:  5.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.12843E-02, solve time:  2.34080E-03, relative residual:  4.66786E-18
### solver log, setup time:  1.79571E-02, solve time:  2.30450E-03, relative residual:  4.47389E-18
### solver log, setup time:  2.36322E-02, solve time:  2.35760E-03, relative residual:  4.23598E-18
### solver log, setup time:  1.82886E-02, solve time:  2.27290E-03, relative residual:  4.25726E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      57, total time:  5.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.96390E-02, solve time:  2.42770E-03, relative residual:  4.42836E-18
### solver log, setup time:  1.83256E-02, solve time:  2.84370E-03, relative residual:  4.22730E-18
### solver log, setup time:  6.73839E-02, solve time:  4.16760E-03, relative residual:  4.06833E-18
### solver log, setup time:  2.42225E-02, solve time:  2.75930E-03, relative residual:  4.34535E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      58, total time:  5.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.29417E-02, solve time:  3.33810E-03, relative residual:  4.45775E-18
### solver log, setup time:  2.24065E-02, solve time:  2.55520E-03, relative residual:  4.20447E-18
### solver log, setup time:  1.76696E-02, solve time:  2.98930E-03, relative residual:  4.50296E-18
### solver log, setup time:  2.00455E-02, solve time:  2.02360E-03, relative residual:  4.24768E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      59, total time:  5.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92403E-02, solve time:  2.87190E-03, relative residual:  4.35216E-18
### solver log, setup time:  1.80763E-02, solve time:  2.48600E-03, relative residual:  4.19475E-18
### solver log, setup time:  2.09212E-02, solve time:  2.10320E-03, relative residual:  4.74044E-18
### solver log, setup time:  1.89808E-02, solve time:  2.42610E-03, relative residual:  4.18084E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      60, total time:  6.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.74932E-02, solve time:  2.40830E-03, relative residual:  4.64113E-18
### solver log, setup time:  3.16352E-02, solve time:  2.35460E-03, relative residual:  4.05639E-18
### solver log, setup time:  2.32993E-02, solve time:  2.51910E-03, relative residual:  4.97650E-18
### solver log, setup time:  1.75326E-02, solve time:  2.22320E-03, relative residual:  4.52038E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      61, total time:  6.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.15364E-02, solve time:  2.10030E-03, relative residual:  4.30095E-18
### solver log, setup time:  1.88373E-02, solve time:  1.99430E-03, relative residual:  4.38494E-18
### solver log, setup time:  2.13321E-02, solve time:  2.20070E-03, relative residual:  4.45028E-18
### solver log, setup time:  2.60168E-02, solve time:  1.96840E-03, relative residual:  4.38044E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      62, total time:  6.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  4.11756E-02, solve time:  4.09800E-03, relative residual:  4.84093E-18
### solver log, setup time:  2.10526E-02, solve time:  1.86040E-03, relative residual:  4.33255E-18
### solver log, setup time:  2.21865E-02, solve time:  2.27590E-03, relative residual:  4.54495E-18
### solver log, setup time:  2.25818E-02, solve time:  3.20180E-03, relative residual:  4.29912E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      63, total time:  6.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.76734E-02, solve time:  2.57100E-03, relative residual:  4.45300E-18
### solver log, setup time:  2.41491E-02, solve time:  2.21130E-03, relative residual:  4.50178E-18
### solver log, setup time:  2.73345E-02, solve time:  2.44270E-03, relative residual:  5.13456E-18
### solver log, setup time:  3.06956E-02, solve time:  4.05380E-03, relative residual:  4.35916E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      64, total time:  6.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.97468E-02, solve time:  2.74720E-03, relative residual:  4.54964E-18
### solver log, setup time:  1.83852E-02, solve time:  2.33490E-03, relative residual:  4.14010E-18
### solver log, setup time:  2.06436E-02, solve time:  2.69770E-03, relative residual:  4.70640E-18
### solver log, setup time:  2.26991E-02, solve time:  3.20330E-03, relative residual:  4.73879E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      65, total time:  6.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.54099E-02, solve time:  3.01380E-03, relative residual:  4.58438E-18
### solver log, setup time:  2.17780E-02, solve time:  2.40180E-03, relative residual:  4.58599E-18
### solver log, setup time:  2.28559E-02, solve time:  2.81150E-03, relative residual:  4.62900E-18
### solver log, setup time:  1.81688E-02, solve time:  2.03190E-03, relative residual:  4.34483E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      66, total time:  6.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.34135E-02, solve time:  2.85330E-03, relative residual:  4.81909E-18
### solver log, setup time:  3.34155E-02, solve time:  2.48710E-03, relative residual:  4.31255E-18
### solver log, setup time:  2.36984E-02, solve time:  2.48940E-03, relative residual:  4.52402E-18
### solver log, setup time:  1.99064E-02, solve time:  2.16400E-03, relative residual:  4.52786E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      67, total time:  6.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.91521E-02, solve time:  2.51600E-03, relative residual:  4.53393E-18
### solver log, setup time:  2.33066E-02, solve time:  2.08040E-03, relative residual:  4.11566E-18
### solver log, setup time:  2.02946E-02, solve time:  2.17300E-03, relative residual:  4.48703E-18
### solver log, setup time:  2.39973E-02, solve time:  2.75840E-03, relative residual:  4.39246E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      68, total time:  6.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.08498E-02, solve time:  2.21660E-03, relative residual:  5.04000E-18
### solver log, setup time:  1.80438E-02, solve time:  2.20970E-03, relative residual:  4.63031E-18
### solver log, setup time:  2.17695E-02, solve time:  3.13920E-03, relative residual:  4.60302E-18
### solver log, setup time:  2.14145E-02, solve time:  2.77080E-03, relative residual:  4.33461E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      69, total time:  6.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.41870E-02, solve time:  2.97160E-03, relative residual:  4.45808E-18
### solver log, setup time:  2.47694E-02, solve time:  3.15660E-03, relative residual:  4.45162E-18
### solver log, setup time:  2.26505E-02, solve time:  3.61860E-03, relative residual:  4.24163E-18
### solver log, setup time:  2.10676E-02, solve time:  1.98360E-03, relative residual:  4.77331E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      70, total time:  7.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.36542E-02, solve time:  2.99010E-03, relative residual:  4.89602E-18
### solver log, setup time:  2.62892E-02, solve time:  2.68480E-03, relative residual:  4.82524E-18
### solver log, setup time:  2.27348E-02, solve time:  2.26500E-03, relative residual:  4.56268E-18
### solver log, setup time:  1.87407E-02, solve time:  2.56430E-03, relative residual:  4.53774E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      71, total time:  7.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.05705E-02, solve time:  2.81470E-03, relative residual:  4.58389E-18
### solver log, setup time:  2.14078E-02, solve time:  2.52450E-03, relative residual:  4.69304E-18
### solver log, setup time:  2.41756E-02, solve time:  2.12980E-03, relative residual:  4.30076E-18
### solver log, setup time:  2.45524E-02, solve time:  2.84630E-03, relative residual:  4.56834E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      72, total time:  7.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92424E-02, solve time:  2.72830E-03, relative residual:  4.90189E-18
### solver log, setup time:  1.90081E-02, solve time:  2.32350E-03, relative residual:  4.99240E-18
### solver log, setup time:  1.81282E-02, solve time:  2.34510E-03, relative residual:  4.69570E-18
### solver log, setup time:  2.74370E-02, solve time:  4.19110E-03, relative residual:  4.92231E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      73, total time:  7.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.11285E-02, solve time:  2.07320E-03, relative residual:  4.63947E-18
### solver log, setup time:  2.05794E-02, solve time:  2.44690E-03, relative residual:  4.57119E-18
### solver log, setup time:  2.21825E-02, solve time:  2.16020E-03, relative residual:  4.65828E-18
### solver log, setup time:  2.03752E-02, solve time:  2.74470E-03, relative residual:  5.04687E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      74, total time:  7.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.09178E-02, solve time:  2.38960E-03, relative residual:  4.89774E-18
### solver log, setup time:  2.27216E-02, solve time:  2.15800E-03, relative residual:  4.70711E-18
### solver log, setup time:  2.22387E-02, solve time:  2.71360E-03, relative residual:  4.74188E-18
### solver log, setup time:  2.10582E-02, solve time:  1.96600E-03, relative residual:  4.34834E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      75, total time:  7.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.87509E-02, solve time:  2.08350E-03, relative residual:  4.78523E-18
### solver log, setup time:  2.73584E-02, solve time:  2.14880E-03, relative residual:  5.03471E-18
### solver log, setup time:  2.08097E-02, solve time:  2.06620E-03, relative residual:  4.73240E-18
### solver log, setup time:  2.03285E-02, solve time:  2.26270E-03, relative residual:  4.82897E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      76, total time:  7.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86456E-02, solve time:  2.03470E-03, relative residual:  4.92435E-18
### solver log, setup time:  1.98675E-02, solve time:  2.09250E-03, relative residual:  4.62833E-18
### solver log, setup time:  1.96766E-02, solve time:  2.07660E-03, relative residual:  4.26572E-18
### solver log, setup time:  2.16936E-02, solve time:  2.03200E-03, relative residual:  4.51698E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      77, total time:  7.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.08310E-02, solve time:  2.66630E-03, relative residual:  4.94318E-18
### solver log, setup time:  1.98375E-02, solve time:  2.17130E-03, relative residual:  5.23195E-18
### solver log, setup time:  1.86811E-02, solve time:  2.41520E-03, relative residual:  4.30972E-18
### solver log, setup time:  1.91974E-02, solve time:  2.09990E-03, relative residual:  4.72243E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      78, total time:  7.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.16497E-02, solve time:  1.97370E-03, relative residual:  4.92007E-18
### solver log, setup time:  1.96963E-02, solve time:  2.38540E-03, relative residual:  4.94258E-18
### solver log, setup time:  1.97617E-02, solve time:  3.03230E-03, relative residual:  4.63865E-18
### solver log, setup time:  1.77263E-02, solve time:  2.12720E-03, relative residual:  5.07654E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      79, total time:  7.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86704E-02, solve time:  2.37340E-03, relative residual:  5.00807E-18
### solver log, setup time:  1.87758E-02, solve time:  2.38890E-03, relative residual:  4.98502E-18
### solver log, setup time:  1.87113E-02, solve time:  2.09670E-03, relative residual:  5.15280E-18
### solver log, setup time:  2.56438E-02, solve time:  2.90370E-03, relative residual:  5.22656E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      80, total time:  8.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.25317E-02, solve time:  3.95950E-03, relative residual:  4.57591E-18
### solver log, setup time:  1.96030E-02, solve time:  2.89970E-03, relative residual:  4.71228E-18
### solver log, setup time:  2.56115E-02, solve time:  2.42510E-03, relative residual:  4.46459E-18
### solver log, setup time:  2.12408E-02, solve time:  2.76940E-03, relative residual:  4.78821E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      81, total time:  8.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.06760E-02, solve time:  2.09340E-03, relative residual:  4.83390E-18
### solver log, setup time:  2.14215E-02, solve time:  2.00580E-03, relative residual:  4.83158E-18
### solver log, setup time:  1.79121E-02, solve time:  2.12500E-03, relative residual:  4.88722E-18
### solver log, setup time:  1.92805E-02, solve time:  2.20270E-03, relative residual:  5.01777E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      82, total time:  8.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.85329E-02, solve time:  2.34500E-03, relative residual:  4.79933E-18
### solver log, setup time:  2.09100E-02, solve time:  1.91830E-03, relative residual:  4.91547E-18
### solver log, setup time:  1.87792E-02, solve time:  2.62630E-03, relative residual:  4.94669E-18
### solver log, setup time:  2.05330E-02, solve time:  3.05380E-03, relative residual:  4.64224E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      83, total time:  8.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.82754E-02, solve time:  2.09410E-03, relative residual:  4.83367E-18
### solver log, setup time:  1.80728E-02, solve time:  2.26540E-03, relative residual:  5.15539E-18
### solver log, setup time:  1.82325E-02, solve time:  2.05310E-03, relative residual:  5.24439E-18
### solver log, setup time:  2.00930E-02, solve time:  2.63290E-03, relative residual:  4.93992E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      84, total time:  8.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.92202E-02, solve time:  2.24640E-03, relative residual:  5.08960E-18
### solver log, setup time:  1.89390E-02, solve time:  2.18570E-03, relative residual:  4.61501E-18
### solver log, setup time:  1.87659E-02, solve time:  2.45390E-03, relative residual:  4.83812E-18
### solver log, setup time:  1.95400E-02, solve time:  2.12570E-03, relative residual:  4.90008E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      85, total time:  8.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.23475E-02, solve time:  2.20550E-03, relative residual:  4.94462E-18
### solver log, setup time:  1.78917E-02, solve time:  2.44130E-03, relative residual:  4.87584E-18
### solver log, setup time:  1.75620E-02, solve time:  2.38040E-03, relative residual:  5.46720E-18
### solver log, setup time:  1.72783E-02, solve time:  2.45250E-03, relative residual:  4.92990E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      86, total time:  8.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.73840E-02, solve time:  2.24190E-03, relative residual:  5.12041E-18
### solver log, setup time:  1.87567E-02, solve time:  2.13520E-03, relative residual:  5.11929E-18
### solver log, setup time:  1.66436E-02, solve time:  2.35750E-03, relative residual:  5.33066E-18
### solver log, setup time:  2.21067E-02, solve time:  3.27770E-03, relative residual:  5.08876E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      87, total time:  8.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.87238E-02, solve time:  2.25000E-03, relative residual:  4.57003E-18
### solver log, setup time:  1.80481E-02, solve time:  2.29250E-03, relative residual:  5.30333E-18
### solver log, setup time:  1.91518E-02, solve time:  2.15190E-03, relative residual:  4.99503E-18
### solver log, setup time:  1.75480E-02, solve time:  2.45310E-03, relative residual:  4.91146E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      88, total time:  8.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86587E-02, solve time:  2.17780E-03, relative residual:  5.35321E-18
### solver log, setup time:  1.87176E-02, solve time:  2.50310E-03, relative residual:  5.06386E-18
### solver log, setup time:  1.83603E-02, solve time:  2.43550E-03, relative residual:  5.17106E-18
### solver log, setup time:  1.86246E-02, solve time:  2.57290E-03, relative residual:  5.08531E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      89, total time:  8.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.97909E-02, solve time:  2.06250E-03, relative residual:  4.84285E-18
### solver log, setup time:  1.75292E-02, solve time:  2.09300E-03, relative residual:  5.13426E-18
### solver log, setup time:  1.99783E-02, solve time:  2.25170E-03, relative residual:  4.93322E-18
### solver log, setup time:  1.76378E-02, solve time:  2.23230E-03, relative residual:  4.89482E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      90, total time:  9.00000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.75973E-02, solve time:  2.24640E-03, relative residual:  4.83921E-18
### solver log, setup time:  1.63749E-02, solve time:  2.31960E-03, relative residual:  4.60847E-18
### solver log, setup time:  1.80339E-02, solve time:  2.42180E-03, relative residual:  5.13231E-18
### solver log, setup time:  1.84744E-02, solve time:  2.10730E-03, relative residual:  5.08652E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      91, total time:  9.10000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.04897E-02, solve time:  2.31160E-03, relative residual:  4.95171E-18
### solver log, setup time:  1.95426E-02, solve time:  2.25430E-03, relative residual:  5.33740E-18
### solver log, setup time:  1.94142E-02, solve time:  2.45500E-03, relative residual:  5.07124E-18
### solver log, setup time:  1.85544E-02, solve time:  2.70890E-03, relative residual:  4.73629E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      92, total time:  9.20000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.78970E-02, solve time:  2.07600E-03, relative residual:  4.96575E-18
### solver log, setup time:  1.62032E-02, solve time:  2.17450E-03, relative residual:  4.99191E-18
### solver log, setup time:  1.76111E-02, solve time:  2.18810E-03, relative residual:  4.91766E-18
### solver log, setup time:  1.79519E-02, solve time:  2.21140E-03, relative residual:  5.23326E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      93, total time:  9.30000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.86105E-02, solve time:  2.14200E-03, relative residual:  5.15962E-18
### solver log, setup time:  1.85212E-02, solve time:  2.18090E-03, relative residual:  5.35440E-18
### solver log, setup time:  2.10094E-02, solve time:  2.37180E-03, relative residual:  4.58312E-18
### solver log, setup time:  1.76291E-02, solve time:  2.06280E-03, relative residual:  5.47515E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      94, total time:  9.40000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.67601E-02, solve time:  2.24290E-03, relative residual:  5.11954E-18
### solver log, setup time:  1.88247E-02, solve time:  1.95920E-03, relative residual:  5.52695E-18
### solver log, setup time:  1.77714E-02, solve time:  2.47340E-03, relative residual:  5.08876E-18
### solver log, setup time:  1.93795E-02, solve time:  2.15400E-03, relative residual:  5.22859E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      95, total time:  9.50000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.96784E-02, solve time:  2.35550E-03, relative residual:  5.16125E-18
### solver log, setup time:  1.86457E-02, solve time:  2.29830E-03, relative residual:  5.01491E-18
### solver log, setup time:  1.79481E-02, solve time:  2.42370E-03, relative residual:  5.50563E-18
### solver log, setup time:  1.85117E-02, solve time:  1.99430E-03, relative residual:  4.85363E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      96, total time:  9.60000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.11076E-02, solve time:  2.02580E-03, relative residual:  4.87426E-18
### solver log, setup time:  1.76145E-02, solve time:  2.12730E-03, relative residual:  5.24956E-18
### solver log, setup time:  1.76608E-02, solve time:  2.49860E-03, relative residual:  5.15954E-18
### solver log, setup time:  1.90171E-02, solve time:  2.16950E-03, relative residual:  5.23775E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      97, total time:  9.70000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.89274E-02, solve time:  2.23070E-03, relative residual:  5.27329E-18
### solver log, setup time:  1.77807E-02, solve time:  2.06280E-03, relative residual:  5.89466E-18
### solver log, setup time:  1.74376E-02, solve time:  2.31260E-03, relative residual:  5.77799E-18
### solver log, setup time:  1.77939E-02, solve time:  2.21670E-03, relative residual:  5.11930E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      98, total time:  9.80000E-01, delta t:  1.00000E-02
### solver log, setup time:  1.93190E-02, solve time:  2.49850E-03, relative residual:  5.06643E-18
### solver log, setup time:  1.88666E-02, solve time:  2.16800E-03, relative residual:  5.39908E-18
### solver log, setup time:  1.69532E-02, solve time:  2.12320E-03, relative residual:  4.68266E-18
### solver log, setup time:  1.74916E-02, solve time:  2.33430E-03, relative residual:  5.44520E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :      99, total time:  9.90000E-01, delta t:  1.00000E-02
### solver log, setup time:  2.07997E-02, solve time:  2.27270E-03, relative residual:  5.15452E-18
### solver log, setup time:  1.76881E-02, solve time:  2.21620E-03, relative residual:  5.04339E-18
### solver log, setup time:  1.73261E-02, solve time:  2.04290E-03, relative residual:  5.40823E-18
### solver log, setup time:  1.91264E-02, solve time:  1.90170E-03, relative residual:  5.62967E-18
  !!! CONVERGENCE ACHIEVED 
 ** Increment No. :     100, total time:  1.00000E+00, delta t:  1.00000E-02
### solver log, setup time:  2.02600E-02, solve time:  2.20220E-03, relative residual:  4.88197E-18
### solver log, setup time:  1.77143E-02, solve time:  1.88190E-03, relative residual:  5.15747E-18
### solver log, setup time:  1.74931E-02, solve time:  2.20100E-03, relative residual:  5.00746E-18
### solver log, setup time:  1.77427E-02, solve time:  2.69380E-03, relative residual:  5.03040E-18
  !!! CONVERGENCE ACHIEVED 
 ====================================
    TOTAL TIME (sec) :    198.74
           pre (sec) :      0.08
         solve (sec) :    198.66
 ====================================



 :========================================:
 :**            END of FSTR             **:
 :========================================:
